## Pmoda
## RPi GPIO 7-0 are shared with pmoda_rpi_gpio_tri_io[7:0]
#set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {pmoda_rpi_gpio_tri_io[1]}]
#set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {pmoda_rpi_gpio_tri_io[0]}]
#set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {pmoda_rpi_gpio_tri_io[3]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports rxd]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports lets0]
#set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports {pmoda_rpi_gpio_tri_io[5]}]
#set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {pmoda_rpi_gpio_tri_io[4]}]
#set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {pmoda_rpi_gpio_tri_io[7]}]
#set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {pmoda_rpi_gpio_tri_io[6]}]
set_property PULLTYPE PULLUP [get_ports rxd]
#set_property PULLUP true [get_ports {pmoda_rpi_gpio_tri_io[3]}]
#set_property PULLUP true [get_ports {pmoda_rpi_gpio_tri_io[6]}]
#set_property PULLUP true [get_ports {pmoda_rpi_gpio_tri_io[7]}]


connect_debug_port u_ila_0/probe1 [get_nets [list system_i/wedrowiec_top_0/inst/uart/p_0_in]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/wedrowiec_top_0/inst/uart/bit_cnt[0]} {system_i/wedrowiec_top_0/inst/uart/bit_cnt[1]} {system_i/wedrowiec_top_0/inst/uart/bit_cnt[2]} {system_i/wedrowiec_top_0/inst/uart/bit_cnt[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/wedrowiec_top_0/inst/uart/shreg[0]} {system_i/wedrowiec_top_0/inst/uart/shreg[1]} {system_i/wedrowiec_top_0/inst/uart/shreg[2]} {system_i/wedrowiec_top_0/inst/uart/shreg[3]} {system_i/wedrowiec_top_0/inst/uart/shreg[4]} {system_i/wedrowiec_top_0/inst/uart/shreg[5]} {system_i/wedrowiec_top_0/inst/uart/shreg[6]} {system_i/wedrowiec_top_0/inst/uart/shreg[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {system_i/wedrowiec_top_0/inst/uart/uart_tdata[0]} {system_i/wedrowiec_top_0/inst/uart/uart_tdata[1]} {system_i/wedrowiec_top_0/inst/uart/uart_tdata[2]} {system_i/wedrowiec_top_0/inst/uart/uart_tdata[3]} {system_i/wedrowiec_top_0/inst/uart/uart_tdata[4]} {system_i/wedrowiec_top_0/inst/uart/uart_tdata[5]} {system_i/wedrowiec_top_0/inst/uart/uart_tdata[6]} {system_i/wedrowiec_top_0/inst/uart/uart_tdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {system_i/wedrowiec_top_0/inst/uart/stan[0]} {system_i/wedrowiec_top_0/inst/uart/stan[1]} {system_i/wedrowiec_top_0/inst/uart/stan[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 13 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {system_i/wedrowiec_top_0/inst/uart/timbit[0]} {system_i/wedrowiec_top_0/inst/uart/timbit[1]} {system_i/wedrowiec_top_0/inst/uart/timbit[2]} {system_i/wedrowiec_top_0/inst/uart/timbit[3]} {system_i/wedrowiec_top_0/inst/uart/timbit[4]} {system_i/wedrowiec_top_0/inst/uart/timbit[5]} {system_i/wedrowiec_top_0/inst/uart/timbit[6]} {system_i/wedrowiec_top_0/inst/uart/timbit[7]} {system_i/wedrowiec_top_0/inst/uart/timbit[8]} {system_i/wedrowiec_top_0/inst/uart/timbit[9]} {system_i/wedrowiec_top_0/inst/uart/timbit[10]} {system_i/wedrowiec_top_0/inst/uart/timbit[11]} {system_i/wedrowiec_top_0/inst/uart/timbit[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list system_i/wedrowiec_top_0/inst/uart/din]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list system_i/wedrowiec_top_0/inst/uart/p_1_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list system_i/wedrowiec_top_0/inst/uart/uart_tvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
