// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module wedrowiec_hls_axi_wedrowiec_hls_axi_Pipeline_VITIS_LOOP_31_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_r_TREADY,
        is_last_reload,
        ctype_address0,
        ctype_ce0,
        ctype_q0,
        out_r_TDATA,
        out_r_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   out_r_TREADY;
input  [0:0] is_last_reload;
output  [1:0] ctype_address0;
output   ctype_ce0;
input  [24:0] ctype_q0;
output  [63:0] out_r_TDATA;
output   out_r_TVALID;

reg ap_idle;
reg out_r_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln31_fu_130_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_r_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] last_fu_153_p2;
reg   [0:0] last_reg_413;
reg   [0:0] last_reg_413_pp0_iter1_reg;
wire   [0:0] icmp_ln33_fu_164_p2;
reg   [0:0] icmp_ln33_reg_423;
wire   [0:0] tmp_fu_170_p3;
reg   [0:0] tmp_reg_428;
wire   [24:0] select_ln33_fu_184_p3;
reg   [24:0] select_ln33_reg_433;
wire   [63:0] zext_ln31_fu_142_p1;
wire    ap_block_pp0_stage0;
reg   [2:0] j_fu_92;
wire   [2:0] add_ln31_fu_136_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j_1;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ctype_ce0_local;
wire   [0:0] icmp_ln32_fu_147_p2;
wire   [24:0] sub_ln33_fu_178_p2;
wire   [24:0] tmp_9_fu_192_p3;
wire   [4:0] trunc_ln33_fu_199_p1;
wire   [4:0] sub_ln33_1_fu_203_p2;
wire   [5:0] zext_ln33_fu_209_p1;
wire  signed [5:0] add_ln33_fu_213_p2;
wire   [0:0] tmp_1_fu_223_p3;
wire  signed [31:0] tmp_2_fu_237_p2;
wire   [0:0] tmp_2_fu_237_p3;
wire   [0:0] xor_ln33_fu_231_p2;
wire   [5:0] add_ln33_1_fu_262_p2;
wire  signed [31:0] sext_ln33_1_fu_268_p1;
wire   [63:0] zext_ln33_1_fu_250_p1;
wire   [63:0] zext_ln33_3_fu_272_p1;
wire   [63:0] lshr_ln33_fu_276_p2;
wire   [48:0] zext_ln33_2_fu_253_p1;
wire   [48:0] zext_ln33_4_fu_286_p1;
wire   [0:0] icmp_ln33_1_fu_256_p2;
wire   [48:0] trunc_ln33_1_fu_282_p1;
wire   [48:0] shl_ln33_fu_290_p2;
wire   [0:0] phi_ln33_fu_244_p2;
wire   [48:0] cond50_i_i_fu_296_p3;
wire   [48:0] zext_ln33_5_fu_304_p1;
wire   [48:0] add_ln33_2_fu_308_p2;
wire   [47:0] lshr_ln33_1_fu_314_p4;
wire   [0:0] tmp_3_fu_328_p3;
wire   [4:0] sub_ln33_2_fu_344_p2;
wire   [7:0] select_ln33_1_fu_336_p3;
wire  signed [7:0] sext_ln33_2_fu_350_p1;
wire   [7:0] add_ln33_3_fu_354_p2;
wire   [63:0] zext_ln33_6_fu_324_p1;
wire   [8:0] tmp_s_fu_360_p3;
wire   [63:0] pi_assign_fu_367_p5;
wire   [31:0] LD_fu_379_p1;
wire   [31:0] empty_fu_383_p3;
wire   [32:0] tmp_4_fu_390_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [24:0] tmp_9_fu_192_p0;
wire   [0:0] tmp_9_fu_192_p2;
wire   [0:0] tmp_2_fu_237_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_92 = 3'd0;
#0 ap_done_reg = 1'b0;
end

wedrowiec_hls_axi_ctlz_25_25_1_1 #(
    .din_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
ctlz_25_25_1_1_U925(
    .din(select_ln33_reg_433),
    .dout(tmp_9_fu_192_p3)
);

wedrowiec_hls_axi_bitselect_1ns_25ns_32s_1_1_1 #(
    .DATAWIDTH( 25 ),
    .ADDRWIDTH( 32 ))
bitselect_1ns_25ns_32s_1_1_1_U926(
    .din(select_ln33_reg_433),
    .sel(tmp_2_fu_237_p2),
    .dout(tmp_2_fu_237_p3)
);

wedrowiec_hls_axi_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln31_fu_130_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_92 <= add_ln31_fu_136_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_92 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln33_reg_423 <= icmp_ln33_fu_164_p2;
        last_reg_413 <= last_fu_153_p2;
        last_reg_413_pp0_iter1_reg <= last_reg_413;
        select_ln33_reg_433 <= select_ln33_fu_184_p3;
        tmp_reg_428 <= ctype_q0[32'd24];
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_130_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ctype_ce0_local = 1'b1;
    end else begin
        ctype_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_r_TDATA_blk_n = out_r_TREADY;
    end else begin
        out_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_r_TVALID = 1'b1;
    end else begin
        out_r_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_fu_379_p1 = pi_assign_fu_367_p5[31:0];

assign add_ln31_fu_136_p2 = (ap_sig_allocacmp_j_1 + 3'd1);

assign add_ln33_1_fu_262_p2 = ($signed(zext_ln33_fu_209_p1) + $signed(6'd39));

assign add_ln33_2_fu_308_p2 = (cond50_i_i_fu_296_p3 + zext_ln33_5_fu_304_p1);

assign add_ln33_3_fu_354_p2 = ($signed(select_ln33_1_fu_336_p3) + $signed(sext_ln33_2_fu_350_p1));

assign add_ln33_fu_213_p2 = ($signed(zext_ln33_fu_209_p1) + $signed(6'd40));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((out_r_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((out_r_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((out_r_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((out_r_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cond50_i_i_fu_296_p3 = ((icmp_ln33_1_fu_256_p2[0:0] == 1'b1) ? trunc_ln33_1_fu_282_p1 : shl_ln33_fu_290_p2);

assign ctype_address0 = zext_ln31_fu_142_p1;

assign ctype_ce0 = ctype_ce0_local;

assign empty_fu_383_p3 = ((icmp_ln33_reg_423[0:0] == 1'b1) ? 32'd0 : LD_fu_379_p1);

assign icmp_ln31_fu_130_p2 = ((ap_sig_allocacmp_j_1 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_147_p2 = ((ap_sig_allocacmp_j_1 == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln33_1_fu_256_p2 = (($signed(add_ln33_fu_213_p2) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_164_p2 = ((ctype_q0 == 25'd0) ? 1'b1 : 1'b0);

assign last_fu_153_p2 = (is_last_reload & icmp_ln32_fu_147_p2);

assign lshr_ln33_1_fu_314_p4 = {{add_ln33_2_fu_308_p2[48:1]}};

assign lshr_ln33_fu_276_p2 = zext_ln33_1_fu_250_p1 >> zext_ln33_3_fu_272_p1;

assign out_r_TDATA = tmp_4_fu_390_p3;

assign phi_ln33_fu_244_p2 = (xor_ln33_fu_231_p2 & tmp_2_fu_237_p3);

assign pi_assign_fu_367_p5 = {{zext_ln33_6_fu_324_p1[63:32]}, {tmp_s_fu_360_p3}, {zext_ln33_6_fu_324_p1[22:0]}};

assign select_ln33_1_fu_336_p3 = ((tmp_3_fu_328_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln33_fu_184_p3 = ((tmp_fu_170_p3[0:0] == 1'b1) ? sub_ln33_fu_178_p2 : ctype_q0);

assign sext_ln33_1_fu_268_p1 = $signed(add_ln33_1_fu_262_p2);

assign sext_ln33_2_fu_350_p1 = $signed(sub_ln33_2_fu_344_p2);

assign shl_ln33_fu_290_p2 = zext_ln33_2_fu_253_p1 << zext_ln33_4_fu_286_p1;

assign sub_ln33_1_fu_203_p2 = ($signed(5'd25) - $signed(trunc_ln33_fu_199_p1));

assign sub_ln33_2_fu_344_p2 = (5'd13 - trunc_ln33_fu_199_p1);

assign sub_ln33_fu_178_p2 = (25'd0 - ctype_q0);

assign tmp_1_fu_223_p3 = add_ln33_fu_213_p2[32'd5];

assign tmp_2_fu_237_p2 = add_ln33_fu_213_p2;

assign tmp_3_fu_328_p3 = add_ln33_2_fu_308_p2[32'd25];

assign tmp_4_fu_390_p3 = {{last_reg_413_pp0_iter1_reg}, {empty_fu_383_p3}};

assign tmp_fu_170_p3 = ctype_q0[32'd24];

assign tmp_s_fu_360_p3 = {{tmp_reg_428}, {add_ln33_3_fu_354_p2}};

assign trunc_ln33_1_fu_282_p1 = lshr_ln33_fu_276_p2[48:0];

assign trunc_ln33_fu_199_p1 = tmp_9_fu_192_p3[4:0];

assign xor_ln33_fu_231_p2 = (tmp_1_fu_223_p3 ^ 1'd1);

assign zext_ln31_fu_142_p1 = ap_sig_allocacmp_j_1;

assign zext_ln33_1_fu_250_p1 = select_ln33_reg_433;

assign zext_ln33_2_fu_253_p1 = select_ln33_reg_433;

assign zext_ln33_3_fu_272_p1 = $unsigned(sext_ln33_1_fu_268_p1);

assign zext_ln33_4_fu_286_p1 = tmp_9_fu_192_p3;

assign zext_ln33_5_fu_304_p1 = phi_ln33_fu_244_p2;

assign zext_ln33_6_fu_324_p1 = lshr_ln33_1_fu_314_p4;

assign zext_ln33_fu_209_p1 = sub_ln33_1_fu_203_p2;

endmodule //wedrowiec_hls_axi_wedrowiec_hls_axi_Pipeline_VITIS_LOOP_31_4
