-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity wedrowiec_hls_axi_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer6_out_dout : IN STD_LOGIC_VECTOR (319 downto 0);
    layer6_out_empty_n : IN STD_LOGIC;
    layer6_out_read : OUT STD_LOGIC;
    layer6_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer6_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer7_out_din : OUT STD_LOGIC_VECTOR (415 downto 0);
    layer7_out_full_n : IN STD_LOGIC;
    layer7_out_write : OUT STD_LOGIC;
    layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of wedrowiec_hls_axi_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_45 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000101";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    constant ap_const_lv32_6D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101101";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_81 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000001";
    constant ap_const_lv32_82 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000010";
    constant ap_const_lv32_8B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001011";
    constant ap_const_lv32_8C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001100";
    constant ap_const_lv32_95 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010101";
    constant ap_const_lv32_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010110";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_A9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101001";
    constant ap_const_lv32_AA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101010";
    constant ap_const_lv32_B3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110011";
    constant ap_const_lv32_B4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110100";
    constant ap_const_lv32_BD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111101";
    constant ap_const_lv32_BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111110";
    constant ap_const_lv32_C7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000111";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010001";
    constant ap_const_lv32_D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010010";
    constant ap_const_lv32_DB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011011";
    constant ap_const_lv32_DC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011100";
    constant ap_const_lv32_E5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100101";
    constant ap_const_lv32_E6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100110";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111001";
    constant ap_const_lv32_FA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111010";
    constant ap_const_lv32_103 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000011";
    constant ap_const_lv32_104 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000100";
    constant ap_const_lv32_10D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001101";
    constant ap_const_lv32_10E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001110";
    constant ap_const_lv32_117 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010111";
    constant ap_const_lv32_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011000";
    constant ap_const_lv32_121 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100001";
    constant ap_const_lv32_122 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100010";
    constant ap_const_lv32_12B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101011";
    constant ap_const_lv32_12C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101100";
    constant ap_const_lv32_135 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110101";
    constant ap_const_lv32_136 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110110";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer6_out_blk_n : STD_LOGIC;
    signal layer7_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal data_fu_197_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_reg_612 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal data_61_reg_617 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_31_reg_622 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_32_reg_627 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_33_reg_632 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_34_reg_637 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_35_reg_642 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_36_reg_647 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_37_reg_652 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_38_reg_657 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_39_reg_662 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_40_reg_667 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_41_reg_672 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_42_reg_677 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_43_reg_682 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_44_reg_687 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_45_reg_692 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_46_reg_697 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_47_reg_702 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_48_reg_707 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_49_reg_712 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_50_reg_717 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_51_reg_722 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_52_reg_727 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_53_reg_732 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_54_reg_737 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_55_reg_742 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_56_reg_747 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_57_reg_752 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_58_reg_757 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_59_reg_762 : STD_LOGIC_VECTOR (9 downto 0);
    signal data_60_reg_767 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_start : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_done : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_idle : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_ready : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_3 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_4 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_5 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_6 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_7 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_8 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_9 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_10 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_11 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_12 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_13 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_14 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_15 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm_state2 : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component wedrowiec_hls_axi_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_0_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_1_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_2_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_3_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_4_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_5_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_6_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_7_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_8_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_9_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_10_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_11_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_12_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_13_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_14_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_15_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_16_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_17_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_18_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_19_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_20_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_21_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_22_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_23_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_24_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_25_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_26_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_27_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_28_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_29_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_30_val : IN STD_LOGIC_VECTOR (9 downto 0);
        data_31_val : IN STD_LOGIC_VECTOR (9 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (25 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161 : component wedrowiec_hls_axi_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_start,
        ap_done => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_done,
        ap_idle => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_idle,
        ap_ready => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_ready,
        data_0_val => data_reg_612,
        data_1_val => data_61_reg_617,
        data_2_val => data_31_reg_622,
        data_3_val => data_32_reg_627,
        data_4_val => data_33_reg_632,
        data_5_val => data_34_reg_637,
        data_6_val => data_35_reg_642,
        data_7_val => data_36_reg_647,
        data_8_val => data_37_reg_652,
        data_9_val => data_38_reg_657,
        data_10_val => data_39_reg_662,
        data_11_val => data_40_reg_667,
        data_12_val => data_41_reg_672,
        data_13_val => data_42_reg_677,
        data_14_val => data_43_reg_682,
        data_15_val => data_44_reg_687,
        data_16_val => data_45_reg_692,
        data_17_val => data_46_reg_697,
        data_18_val => data_47_reg_702,
        data_19_val => data_48_reg_707,
        data_20_val => data_49_reg_712,
        data_21_val => data_50_reg_717,
        data_22_val => data_51_reg_722,
        data_23_val => data_52_reg_727,
        data_24_val => data_53_reg_732,
        data_25_val => data_54_reg_737,
        data_26_val => data_55_reg_742,
        data_27_val => data_56_reg_747,
        data_28_val => data_57_reg_752,
        data_29_val => data_58_reg_757,
        data_30_val => data_59_reg_762,
        data_31_val => data_60_reg_767,
        ap_return_0 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_0,
        ap_return_1 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_1,
        ap_return_2 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_2,
        ap_return_3 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_3,
        ap_return_4 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_4,
        ap_return_5 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_5,
        ap_return_6 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_6,
        ap_return_7 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_7,
        ap_return_8 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_8,
        ap_return_9 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_9,
        ap_return_10 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_10,
        ap_return_11 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_11,
        ap_return_12 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_12,
        ap_return_13 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_13,
        ap_return_14 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_14,
        ap_return_15 => grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_15);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_NS_fsm_state2))) then 
                    grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_ready = ap_const_logic_1)) then 
                    grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                data_31_reg_622 <= layer6_out_dout(29 downto 20);
                data_32_reg_627 <= layer6_out_dout(39 downto 30);
                data_33_reg_632 <= layer6_out_dout(49 downto 40);
                data_34_reg_637 <= layer6_out_dout(59 downto 50);
                data_35_reg_642 <= layer6_out_dout(69 downto 60);
                data_36_reg_647 <= layer6_out_dout(79 downto 70);
                data_37_reg_652 <= layer6_out_dout(89 downto 80);
                data_38_reg_657 <= layer6_out_dout(99 downto 90);
                data_39_reg_662 <= layer6_out_dout(109 downto 100);
                data_40_reg_667 <= layer6_out_dout(119 downto 110);
                data_41_reg_672 <= layer6_out_dout(129 downto 120);
                data_42_reg_677 <= layer6_out_dout(139 downto 130);
                data_43_reg_682 <= layer6_out_dout(149 downto 140);
                data_44_reg_687 <= layer6_out_dout(159 downto 150);
                data_45_reg_692 <= layer6_out_dout(169 downto 160);
                data_46_reg_697 <= layer6_out_dout(179 downto 170);
                data_47_reg_702 <= layer6_out_dout(189 downto 180);
                data_48_reg_707 <= layer6_out_dout(199 downto 190);
                data_49_reg_712 <= layer6_out_dout(209 downto 200);
                data_50_reg_717 <= layer6_out_dout(219 downto 210);
                data_51_reg_722 <= layer6_out_dout(229 downto 220);
                data_52_reg_727 <= layer6_out_dout(239 downto 230);
                data_53_reg_732 <= layer6_out_dout(249 downto 240);
                data_54_reg_737 <= layer6_out_dout(259 downto 250);
                data_55_reg_742 <= layer6_out_dout(269 downto 260);
                data_56_reg_747 <= layer6_out_dout(279 downto 270);
                data_57_reg_752 <= layer6_out_dout(289 downto 280);
                data_58_reg_757 <= layer6_out_dout(299 downto 290);
                data_59_reg_762 <= layer6_out_dout(309 downto 300);
                data_60_reg_767 <= layer6_out_dout(319 downto 310);
                data_61_reg_617 <= layer6_out_dout(19 downto 10);
                data_reg_612 <= data_fu_197_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer7_out_full_n, ap_CS_fsm_state4, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_NS_fsm_state2 <= ap_NS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(layer7_out_full_n)
    begin
        if ((layer7_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer6_out_empty_n)
    begin
                ap_block_state1 <= ((layer6_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer7_out_full_n, ap_CS_fsm_state4)
    begin
        if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    data_fu_197_p1 <= layer6_out_dout(10 - 1 downto 0);
    grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_start <= grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_start_reg;

    internal_ap_ready_assign_proc : process(layer7_out_full_n, ap_CS_fsm_state4)
    begin
        if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer6_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer6_out_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer6_out_blk_n <= layer6_out_empty_n;
        else 
            layer6_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer6_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer6_out_read <= ap_const_logic_1;
        else 
            layer6_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer7_out_blk_n_assign_proc : process(layer7_out_full_n, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            layer7_out_blk_n <= layer7_out_full_n;
        else 
            layer7_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer7_out_din <= (((((((((((((((grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_15 & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_14) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_13) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_12) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_11) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_10) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_9) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_8) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_7) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_6) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_5) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_4) 
    & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_3) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_2) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_1) & grp_dense_latency_ap_fixed_10_4_0_0_0_ap_fixed_26_14_5_3_0_config7_s_fu_161_ap_return_0);

    layer7_out_write_assign_proc : process(layer7_out_full_n, ap_CS_fsm_state4)
    begin
        if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            layer7_out_write <= ap_const_logic_1;
        else 
            layer7_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
