-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity wedrowiec_hls_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer8_out_dout : IN STD_LOGIC_VECTOR (95 downto 0);
    layer8_out_empty_n : IN STD_LOGIC;
    layer8_out_read : OUT STD_LOGIC;
    layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer9_out_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    layer9_out_TVALID : OUT STD_LOGIC;
    layer9_out_TREADY : IN STD_LOGIC );
end;


architecture behav of wedrowiec_hls_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000010";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_53 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010011";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal layer8_out_blk_n : STD_LOGIC;
    signal layer9_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal data_fu_125_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_reg_314 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal data_75_reg_319 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_61_reg_324 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_62_reg_329 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_63_reg_334 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_64_reg_339 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_65_reg_344 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_66_reg_349 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_67_reg_354 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_68_reg_359 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_69_reg_364 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_70_reg_369 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_71_reg_374 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_72_reg_379 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_73_reg_384 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_74_reg_389 : STD_LOGIC_VECTOR (5 downto 0);
    signal res_reg_394 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_done : STD_LOGIC;
    signal res_1_reg_399 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_2_reg_404 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_3_reg_409 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_start : STD_LOGIC;
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_idle : STD_LOGIC;
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_ready : STD_LOGIC;
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_2 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_fu_295_p8 : STD_LOGIC_VECTOR (112 downto 0);
    signal regslice_both_layer9_out_U_apdone_blk : STD_LOGIC;
    signal ap_block_state5 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal layer9_out_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal layer9_out_TVALID_int_regslice : STD_LOGIC;
    signal layer9_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_layer9_out_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component wedrowiec_hls_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_0_val1 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_1_val2 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_2_val3 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_3_val4 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_4_val5 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_5_val6 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_6_val7 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_7_val8 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_8_val9 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_9_val10 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_10_val11 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_11_val12 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_12_val13 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_13_val14 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_14_val15 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_15_val16 : IN STD_LOGIC_VECTOR (5 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (16 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component wedrowiec_hls_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105 : component wedrowiec_hls_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_start,
        ap_done => grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_done,
        ap_idle => grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_idle,
        ap_ready => grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_ready,
        data_0_val1 => data_reg_314,
        data_1_val2 => data_75_reg_319,
        data_2_val3 => data_61_reg_324,
        data_3_val4 => data_62_reg_329,
        data_4_val5 => data_63_reg_334,
        data_5_val6 => data_64_reg_339,
        data_6_val7 => data_65_reg_344,
        data_7_val8 => data_66_reg_349,
        data_8_val9 => data_67_reg_354,
        data_9_val10 => data_68_reg_359,
        data_10_val11 => data_69_reg_364,
        data_11_val12 => data_70_reg_369,
        data_12_val13 => data_71_reg_374,
        data_13_val14 => data_72_reg_379,
        data_14_val15 => data_73_reg_384,
        data_15_val16 => data_74_reg_389,
        ap_return_0 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_0,
        ap_return_1 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_1,
        ap_return_2 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_2,
        ap_return_3 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_3);

    regslice_both_layer9_out_U : component wedrowiec_hls_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => layer9_out_TDATA_int_regslice,
        vld_in => layer9_out_TVALID_int_regslice,
        ack_in => layer9_out_TREADY_int_regslice,
        data_out => layer9_out_TDATA,
        vld_out => regslice_both_layer9_out_U_vld_out,
        ack_out => layer9_out_TREADY,
        apdone_blk => regslice_both_layer9_out_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_ready = ap_const_logic_1)) then 
                    grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                data_61_reg_324 <= layer8_out_dout(17 downto 12);
                data_62_reg_329 <= layer8_out_dout(23 downto 18);
                data_63_reg_334 <= layer8_out_dout(29 downto 24);
                data_64_reg_339 <= layer8_out_dout(35 downto 30);
                data_65_reg_344 <= layer8_out_dout(41 downto 36);
                data_66_reg_349 <= layer8_out_dout(47 downto 42);
                data_67_reg_354 <= layer8_out_dout(53 downto 48);
                data_68_reg_359 <= layer8_out_dout(59 downto 54);
                data_69_reg_364 <= layer8_out_dout(65 downto 60);
                data_70_reg_369 <= layer8_out_dout(71 downto 66);
                data_71_reg_374 <= layer8_out_dout(77 downto 72);
                data_72_reg_379 <= layer8_out_dout(83 downto 78);
                data_73_reg_384 <= layer8_out_dout(89 downto 84);
                data_74_reg_389 <= layer8_out_dout(95 downto 90);
                data_75_reg_319 <= layer8_out_dout(11 downto 6);
                data_reg_314 <= data_fu_125_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_1_reg_399 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_1;
                res_2_reg_404 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_2;
                res_3_reg_409 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_3;
                res_reg_394 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_return_0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_block_state1, ap_CS_fsm_state3, grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_done, ap_block_state5, layer9_out_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((layer9_out_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_done)
    begin
        if ((grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(layer9_out_TREADY_int_regslice)
    begin
        if ((layer9_out_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5)
    begin
        if ((ap_const_boolean_1 = ap_block_state5)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, layer8_out_empty_n)
    begin
                ap_block_state1 <= ((layer8_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state5_assign_proc : process(regslice_both_layer9_out_U_apdone_blk, layer9_out_TREADY_int_regslice)
    begin
                ap_block_state5 <= ((layer9_out_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_layer9_out_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, ap_block_state5)
    begin
        if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, ap_block_state5)
    begin
        if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    data_fu_125_p1 <= layer8_out_dout(6 - 1 downto 0);
    grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_start <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105_ap_start_reg;

    layer8_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, layer8_out_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer8_out_blk_n <= layer8_out_empty_n;
        else 
            layer8_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer8_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer8_out_read <= ap_const_logic_1;
        else 
            layer8_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer9_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, layer9_out_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            layer9_out_TDATA_blk_n <= layer9_out_TREADY_int_regslice;
        else 
            layer9_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer9_out_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_295_p8),128));
    layer9_out_TVALID <= regslice_both_layer9_out_U_vld_out;

    layer9_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state4, layer9_out_TREADY_int_regslice)
    begin
        if (((layer9_out_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            layer9_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            layer9_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_295_p8 <= ((((((res_3_reg_409 & ap_const_lv15_0) & res_2_reg_404) & ap_const_lv15_0) & res_1_reg_399) & ap_const_lv15_0) & res_reg_394);
end behav;
