-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity wedrowiec_hls_axi_wedrowiec_hls is
port (
    in_local_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    in_local_empty_n : IN STD_LOGIC;
    in_local_read : OUT STD_LOGIC;
    out_local_din : OUT STD_LOGIC_VECTOR (99 downto 0);
    out_local_full_n : IN STD_LOGIC;
    out_local_write : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of wedrowiec_hls_axi_wedrowiec_hls is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_start : STD_LOGIC;
    signal dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_done : STD_LOGIC;
    signal dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_continue : STD_LOGIC;
    signal dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_idle : STD_LOGIC;
    signal dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_ready : STD_LOGIC;
    signal dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_start_out : STD_LOGIC;
    signal dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_start_write : STD_LOGIC;
    signal dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_in_local_read : STD_LOGIC;
    signal dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_layer3_out_din : STD_LOGIC_VECTOR (799 downto 0);
    signal dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_layer3_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_start_out : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_start_write : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_layer3_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_layer4_out_din : STD_LOGIC_VECTOR (319 downto 0);
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_layer4_out_write : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_start : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_done : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_continue : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_idle : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_ready : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_start_out : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_start_write : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_layer4_out_read : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_layer5_out_din : STD_LOGIC_VECTOR (831 downto 0);
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_layer5_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_start_out : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_start_write : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_layer5_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_layer6_out_din : STD_LOGIC_VECTOR (319 downto 0);
    signal relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_layer6_out_write : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_start : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_done : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_continue : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_idle : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_ready : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_start_out : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_start_write : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_layer6_out_read : STD_LOGIC;
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_layer7_out_din : STD_LOGIC_VECTOR (415 downto 0);
    signal dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_layer7_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_start_out : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_start_write : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_layer7_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_layer8_out_din : STD_LOGIC_VECTOR (159 downto 0);
    signal relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_layer8_out_write : STD_LOGIC;
    signal dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_start : STD_LOGIC;
    signal dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_done : STD_LOGIC;
    signal dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_continue : STD_LOGIC;
    signal dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_idle : STD_LOGIC;
    signal dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_ready : STD_LOGIC;
    signal dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_layer8_out_read : STD_LOGIC;
    signal dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_out_local_din : STD_LOGIC_VECTOR (99 downto 0);
    signal dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_out_local_write : STD_LOGIC;
    signal layer3_out_full_n : STD_LOGIC;
    signal layer3_out_dout : STD_LOGIC_VECTOR (799 downto 0);
    signal layer3_out_empty_n : STD_LOGIC;
    signal layer3_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer3_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_full_n : STD_LOGIC;
    signal layer4_out_dout : STD_LOGIC_VECTOR (319 downto 0);
    signal layer4_out_empty_n : STD_LOGIC;
    signal layer4_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer5_out_full_n : STD_LOGIC;
    signal layer5_out_dout : STD_LOGIC_VECTOR (831 downto 0);
    signal layer5_out_empty_n : STD_LOGIC;
    signal layer5_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer5_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer6_out_full_n : STD_LOGIC;
    signal layer6_out_dout : STD_LOGIC_VECTOR (319 downto 0);
    signal layer6_out_empty_n : STD_LOGIC;
    signal layer6_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer6_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_full_n : STD_LOGIC;
    signal layer7_out_dout : STD_LOGIC_VECTOR (415 downto 0);
    signal layer7_out_empty_n : STD_LOGIC;
    signal layer7_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer8_out_full_n : STD_LOGIC;
    signal layer8_out_dout : STD_LOGIC_VECTOR (159 downto 0);
    signal layer8_out_empty_n : STD_LOGIC;
    signal layer8_out_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer8_out_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_empty_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_full_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_empty_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_empty_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_full_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_empty_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_empty_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_full_n : STD_LOGIC;
    signal start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_empty_n : STD_LOGIC;

    component wedrowiec_hls_axi_dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        in_local_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        in_local_empty_n : IN STD_LOGIC;
        in_local_read : OUT STD_LOGIC;
        layer3_out_din : OUT STD_LOGIC_VECTOR (799 downto 0);
        layer3_out_full_n : IN STD_LOGIC;
        layer3_out_write : OUT STD_LOGIC;
        layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component wedrowiec_hls_axi_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer3_out_dout : IN STD_LOGIC_VECTOR (799 downto 0);
        layer3_out_empty_n : IN STD_LOGIC;
        layer3_out_read : OUT STD_LOGIC;
        layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer4_out_din : OUT STD_LOGIC_VECTOR (319 downto 0);
        layer4_out_full_n : IN STD_LOGIC;
        layer4_out_write : OUT STD_LOGIC;
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component wedrowiec_hls_axi_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer4_out_dout : IN STD_LOGIC_VECTOR (319 downto 0);
        layer4_out_empty_n : IN STD_LOGIC;
        layer4_out_read : OUT STD_LOGIC;
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer5_out_din : OUT STD_LOGIC_VECTOR (831 downto 0);
        layer5_out_full_n : IN STD_LOGIC;
        layer5_out_write : OUT STD_LOGIC;
        layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component wedrowiec_hls_axi_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer5_out_dout : IN STD_LOGIC_VECTOR (831 downto 0);
        layer5_out_empty_n : IN STD_LOGIC;
        layer5_out_read : OUT STD_LOGIC;
        layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer6_out_din : OUT STD_LOGIC_VECTOR (319 downto 0);
        layer6_out_full_n : IN STD_LOGIC;
        layer6_out_write : OUT STD_LOGIC;
        layer6_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer6_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component wedrowiec_hls_axi_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer6_out_dout : IN STD_LOGIC_VECTOR (319 downto 0);
        layer6_out_empty_n : IN STD_LOGIC;
        layer6_out_read : OUT STD_LOGIC;
        layer6_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer6_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer7_out_din : OUT STD_LOGIC_VECTOR (415 downto 0);
        layer7_out_full_n : IN STD_LOGIC;
        layer7_out_write : OUT STD_LOGIC;
        layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component wedrowiec_hls_axi_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer7_out_dout : IN STD_LOGIC_VECTOR (415 downto 0);
        layer7_out_empty_n : IN STD_LOGIC;
        layer7_out_read : OUT STD_LOGIC;
        layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        layer8_out_din : OUT STD_LOGIC_VECTOR (159 downto 0);
        layer8_out_full_n : IN STD_LOGIC;
        layer8_out_write : OUT STD_LOGIC;
        layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component wedrowiec_hls_axi_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer8_out_dout : IN STD_LOGIC_VECTOR (159 downto 0);
        layer8_out_empty_n : IN STD_LOGIC;
        layer8_out_read : OUT STD_LOGIC;
        layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        out_local_din : OUT STD_LOGIC_VECTOR (99 downto 0);
        out_local_full_n : IN STD_LOGIC;
        out_local_write : OUT STD_LOGIC );
    end component;


    component wedrowiec_hls_axi_fifo_w800_d1_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (799 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (799 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component wedrowiec_hls_axi_fifo_w320_d1_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (319 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (319 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component wedrowiec_hls_axi_fifo_w832_d1_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (831 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (831 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component wedrowiec_hls_axi_fifo_w416_d1_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (415 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (415 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component wedrowiec_hls_axi_fifo_w160_d1_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (159 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (159 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component wedrowiec_hls_axi_start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component wedrowiec_hls_axi_start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component wedrowiec_hls_axi_start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component wedrowiec_hls_axi_start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component wedrowiec_hls_axi_start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component wedrowiec_hls_axi_start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0 : component wedrowiec_hls_axi_dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_full_n,
        ap_done => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_done,
        ap_continue => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_continue,
        ap_idle => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_idle,
        ap_ready => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_ready,
        start_out => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_start_out,
        start_write => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_start_write,
        in_local_dout => in_local_dout,
        in_local_empty_n => in_local_empty_n,
        in_local_read => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_in_local_read,
        layer3_out_din => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_layer3_out_din,
        layer3_out_full_n => layer3_out_full_n,
        layer3_out_write => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_layer3_out_write,
        layer3_out_num_data_valid => layer3_out_num_data_valid,
        layer3_out_fifo_cap => layer3_out_fifo_cap);

    relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0 : component wedrowiec_hls_axi_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_start,
        start_full_n => start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_full_n,
        ap_done => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_done,
        ap_continue => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_ready,
        start_out => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_start_out,
        start_write => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_start_write,
        layer3_out_dout => layer3_out_dout,
        layer3_out_empty_n => layer3_out_empty_n,
        layer3_out_read => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_layer3_out_read,
        layer3_out_num_data_valid => layer3_out_num_data_valid,
        layer3_out_fifo_cap => layer3_out_fifo_cap,
        layer4_out_din => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_layer4_out_din,
        layer4_out_full_n => layer4_out_full_n,
        layer4_out_write => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_layer4_out_write,
        layer4_out_num_data_valid => layer4_out_num_data_valid,
        layer4_out_fifo_cap => layer4_out_fifo_cap);

    dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0 : component wedrowiec_hls_axi_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_full_n,
        ap_done => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_done,
        ap_continue => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_continue,
        ap_idle => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_idle,
        ap_ready => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_ready,
        start_out => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_start_out,
        start_write => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_start_write,
        layer4_out_dout => layer4_out_dout,
        layer4_out_empty_n => layer4_out_empty_n,
        layer4_out_read => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_layer4_out_read,
        layer4_out_num_data_valid => layer4_out_num_data_valid,
        layer4_out_fifo_cap => layer4_out_fifo_cap,
        layer5_out_din => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_layer5_out_din,
        layer5_out_full_n => layer5_out_full_n,
        layer5_out_write => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_layer5_out_write,
        layer5_out_num_data_valid => layer5_out_num_data_valid,
        layer5_out_fifo_cap => layer5_out_fifo_cap);

    relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0 : component wedrowiec_hls_axi_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_start,
        start_full_n => start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_full_n,
        ap_done => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_done,
        ap_continue => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_ready,
        start_out => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_start_out,
        start_write => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_start_write,
        layer5_out_dout => layer5_out_dout,
        layer5_out_empty_n => layer5_out_empty_n,
        layer5_out_read => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_layer5_out_read,
        layer5_out_num_data_valid => layer5_out_num_data_valid,
        layer5_out_fifo_cap => layer5_out_fifo_cap,
        layer6_out_din => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_layer6_out_din,
        layer6_out_full_n => layer6_out_full_n,
        layer6_out_write => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_layer6_out_write,
        layer6_out_num_data_valid => layer6_out_num_data_valid,
        layer6_out_fifo_cap => layer6_out_fifo_cap);

    dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0 : component wedrowiec_hls_axi_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_full_n,
        ap_done => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_done,
        ap_continue => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_continue,
        ap_idle => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_idle,
        ap_ready => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_ready,
        start_out => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_start_out,
        start_write => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_start_write,
        layer6_out_dout => layer6_out_dout,
        layer6_out_empty_n => layer6_out_empty_n,
        layer6_out_read => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_layer6_out_read,
        layer6_out_num_data_valid => layer6_out_num_data_valid,
        layer6_out_fifo_cap => layer6_out_fifo_cap,
        layer7_out_din => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_layer7_out_din,
        layer7_out_full_n => layer7_out_full_n,
        layer7_out_write => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_layer7_out_write,
        layer7_out_num_data_valid => layer7_out_num_data_valid,
        layer7_out_fifo_cap => layer7_out_fifo_cap);

    relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0 : component wedrowiec_hls_axi_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_start,
        start_full_n => start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_full_n,
        ap_done => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_done,
        ap_continue => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_ready,
        start_out => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_start_out,
        start_write => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_start_write,
        layer7_out_dout => layer7_out_dout,
        layer7_out_empty_n => layer7_out_empty_n,
        layer7_out_read => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_layer7_out_read,
        layer7_out_num_data_valid => layer7_out_num_data_valid,
        layer7_out_fifo_cap => layer7_out_fifo_cap,
        layer8_out_din => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_layer8_out_din,
        layer8_out_full_n => layer8_out_full_n,
        layer8_out_write => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_layer8_out_write,
        layer8_out_num_data_valid => layer8_out_num_data_valid,
        layer8_out_fifo_cap => layer8_out_fifo_cap);

    dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0 : component wedrowiec_hls_axi_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_start,
        ap_done => dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_done,
        ap_continue => dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_continue,
        ap_idle => dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_idle,
        ap_ready => dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_ready,
        layer8_out_dout => layer8_out_dout,
        layer8_out_empty_n => layer8_out_empty_n,
        layer8_out_read => dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_layer8_out_read,
        layer8_out_num_data_valid => layer8_out_num_data_valid,
        layer8_out_fifo_cap => layer8_out_fifo_cap,
        out_local_din => dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_out_local_din,
        out_local_full_n => out_local_full_n,
        out_local_write => dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_out_local_write);

    layer3_out_U : component wedrowiec_hls_axi_fifo_w800_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_layer3_out_din,
        if_full_n => layer3_out_full_n,
        if_write => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_layer3_out_write,
        if_dout => layer3_out_dout,
        if_empty_n => layer3_out_empty_n,
        if_read => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_layer3_out_read,
        if_num_data_valid => layer3_out_num_data_valid,
        if_fifo_cap => layer3_out_fifo_cap);

    layer4_out_U : component wedrowiec_hls_axi_fifo_w320_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_layer4_out_din,
        if_full_n => layer4_out_full_n,
        if_write => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_layer4_out_write,
        if_dout => layer4_out_dout,
        if_empty_n => layer4_out_empty_n,
        if_read => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_layer4_out_read,
        if_num_data_valid => layer4_out_num_data_valid,
        if_fifo_cap => layer4_out_fifo_cap);

    layer5_out_U : component wedrowiec_hls_axi_fifo_w832_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_layer5_out_din,
        if_full_n => layer5_out_full_n,
        if_write => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_layer5_out_write,
        if_dout => layer5_out_dout,
        if_empty_n => layer5_out_empty_n,
        if_read => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_layer5_out_read,
        if_num_data_valid => layer5_out_num_data_valid,
        if_fifo_cap => layer5_out_fifo_cap);

    layer6_out_U : component wedrowiec_hls_axi_fifo_w320_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_layer6_out_din,
        if_full_n => layer6_out_full_n,
        if_write => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_layer6_out_write,
        if_dout => layer6_out_dout,
        if_empty_n => layer6_out_empty_n,
        if_read => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_layer6_out_read,
        if_num_data_valid => layer6_out_num_data_valid,
        if_fifo_cap => layer6_out_fifo_cap);

    layer7_out_U : component wedrowiec_hls_axi_fifo_w416_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_layer7_out_din,
        if_full_n => layer7_out_full_n,
        if_write => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_layer7_out_write,
        if_dout => layer7_out_dout,
        if_empty_n => layer7_out_empty_n,
        if_read => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_layer7_out_read,
        if_num_data_valid => layer7_out_num_data_valid,
        if_fifo_cap => layer7_out_fifo_cap);

    layer8_out_U : component wedrowiec_hls_axi_fifo_w160_d1_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_layer8_out_din,
        if_full_n => layer8_out_full_n,
        if_write => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_layer8_out_write,
        if_dout => layer8_out_dout,
        if_empty_n => layer8_out_empty_n,
        if_read => dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_layer8_out_read,
        if_num_data_valid => layer8_out_num_data_valid,
        if_fifo_cap => layer8_out_fifo_cap);

    start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_U : component wedrowiec_hls_axi_start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_full_n,
        if_write => dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_empty_n,
        if_read => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_ready);

    start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_U : component wedrowiec_hls_axi_start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_din,
        if_full_n => start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_full_n,
        if_write => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_start_write,
        if_dout => start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_dout,
        if_empty_n => start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_empty_n,
        if_read => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_ready);

    start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_U : component wedrowiec_hls_axi_start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_full_n,
        if_write => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_empty_n,
        if_read => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_ready);

    start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_U : component wedrowiec_hls_axi_start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_din,
        if_full_n => start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_full_n,
        if_write => relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_start_write,
        if_dout => start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_dout,
        if_empty_n => start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_empty_n,
        if_read => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_ready);

    start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_U : component wedrowiec_hls_axi_start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_full_n,
        if_write => dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_empty_n,
        if_read => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_ready);

    start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_U : component wedrowiec_hls_axi_start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_din,
        if_full_n => start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_full_n,
        if_write => relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_start_write,
        if_dout => start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_dout,
        if_empty_n => start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_empty_n,
        if_read => dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_ready);




    ap_done <= dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_done;
    ap_idle <= (relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_idle and relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_idle and relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_idle and dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_idle and dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_idle and dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_idle and dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_idle);
    ap_ready <= dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_ready;
    dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_continue <= ap_continue;
    dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_ap_start <= start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_empty_n;
    dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_continue <= ap_const_logic_1;
    dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_ap_start <= start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_empty_n;
    dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_continue <= ap_const_logic_1;
    dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_ap_start <= start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_empty_n;
    dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_continue <= ap_const_logic_1;
    dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_ap_start <= ap_start;
    in_local_read <= dense_array_ap_ufixed_8u_array_ap_fixed_25_12_5_3_0_32u_config3_U0_in_local_read;
    out_local_din <= dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_out_local_din;
    out_local_write <= dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_out_local_write;
    relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_ap_start <= start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_empty_n;
    relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_ap_start <= start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_empty_n;
    relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_ap_start <= start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_empty_n;
    start_for_dense_array_ap_fixed_16u_array_ap_fixed_25_13_5_3_0_4u_config9_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_16u_config7_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_dense_array_ap_fixed_32u_array_ap_fixed_26_14_5_3_0_32u_config5_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_fixed_16u_array_ap_fixed_10_4_0_0_0_16u_relu_config8_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config6_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
