// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module wedrowiec_hls_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer3_out_dout,
        layer3_out_empty_n,
        layer3_out_read,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap,
        layer4_out_din,
        layer4_out_full_n,
        layer4_out_write,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [671:0] layer3_out_dout;
input   layer3_out_empty_n;
output   layer3_out_read;
input  [1:0] layer3_out_num_data_valid;
input  [1:0] layer3_out_fifo_cap;
output  [191:0] layer4_out_din;
input   layer4_out_full_n;
output   layer4_out_write;
input  [1:0] layer4_out_num_data_valid;
input  [1:0] layer4_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer3_out_read;
reg layer4_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer3_out_blk_n;
reg    layer4_out_blk_n;
reg    ap_block_state1;
wire   [20:0] trunc_ln44_fu_307_p1;
wire   [14:0] tmp_2_fu_647_p4;
wire   [0:0] tmp_158_fu_639_p3;
wire   [0:0] icmp_ln52_fu_657_p2;
wire   [0:0] tmp_fu_627_p3;
wire   [0:0] or_ln52_fu_663_p2;
wire   [0:0] xor_ln52_fu_669_p2;
wire   [0:0] and_ln52_fu_675_p2;
wire   [0:0] or_ln52_1_fu_689_p2;
wire   [5:0] select_ln52_fu_681_p3;
wire   [5:0] trunc_ln52_fu_635_p1;
wire   [0:0] icmp_ln51_fu_621_p2;
wire   [5:0] select_ln52_1_fu_695_p3;
wire   [20:0] trunc_ln44_1_fu_311_p4;
wire   [14:0] tmp_5_fu_743_p4;
wire   [0:0] tmp_160_fu_735_p3;
wire   [0:0] icmp_ln52_1_fu_753_p2;
wire   [0:0] tmp_159_fu_717_p3;
wire   [0:0] or_ln52_2_fu_759_p2;
wire   [0:0] xor_ln52_1_fu_765_p2;
wire   [0:0] and_ln52_1_fu_771_p2;
wire   [0:0] or_ln52_3_fu_785_p2;
wire   [5:0] select_ln52_2_fu_777_p3;
wire   [5:0] trunc_ln52_1_fu_725_p4;
wire   [0:0] icmp_ln51_1_fu_711_p2;
wire   [5:0] select_ln52_3_fu_791_p3;
wire   [20:0] trunc_ln44_2_fu_321_p4;
wire   [14:0] tmp_8_fu_839_p4;
wire   [0:0] tmp_162_fu_831_p3;
wire   [0:0] icmp_ln52_2_fu_849_p2;
wire   [0:0] tmp_161_fu_813_p3;
wire   [0:0] or_ln52_4_fu_855_p2;
wire   [0:0] xor_ln52_2_fu_861_p2;
wire   [0:0] and_ln52_2_fu_867_p2;
wire   [0:0] or_ln52_5_fu_881_p2;
wire   [5:0] select_ln52_4_fu_873_p3;
wire   [5:0] trunc_ln52_2_fu_821_p4;
wire   [0:0] icmp_ln51_2_fu_807_p2;
wire   [5:0] select_ln52_5_fu_887_p3;
wire   [20:0] trunc_ln44_3_fu_331_p4;
wire   [14:0] tmp_11_fu_935_p4;
wire   [0:0] tmp_164_fu_927_p3;
wire   [0:0] icmp_ln52_3_fu_945_p2;
wire   [0:0] tmp_163_fu_909_p3;
wire   [0:0] or_ln52_6_fu_951_p2;
wire   [0:0] xor_ln52_3_fu_957_p2;
wire   [0:0] and_ln52_3_fu_963_p2;
wire   [0:0] or_ln52_7_fu_977_p2;
wire   [5:0] select_ln52_6_fu_969_p3;
wire   [5:0] trunc_ln52_3_fu_917_p4;
wire   [0:0] icmp_ln51_3_fu_903_p2;
wire   [5:0] select_ln52_7_fu_983_p3;
wire   [20:0] trunc_ln44_4_fu_341_p4;
wire   [14:0] tmp_14_fu_1031_p4;
wire   [0:0] tmp_166_fu_1023_p3;
wire   [0:0] icmp_ln52_4_fu_1041_p2;
wire   [0:0] tmp_165_fu_1005_p3;
wire   [0:0] or_ln52_8_fu_1047_p2;
wire   [0:0] xor_ln52_4_fu_1053_p2;
wire   [0:0] and_ln52_4_fu_1059_p2;
wire   [0:0] or_ln52_9_fu_1073_p2;
wire   [5:0] select_ln52_8_fu_1065_p3;
wire   [5:0] trunc_ln52_4_fu_1013_p4;
wire   [0:0] icmp_ln51_4_fu_999_p2;
wire   [5:0] select_ln52_9_fu_1079_p3;
wire   [20:0] trunc_ln44_5_fu_351_p4;
wire   [14:0] tmp_17_fu_1127_p4;
wire   [0:0] tmp_168_fu_1119_p3;
wire   [0:0] icmp_ln52_5_fu_1137_p2;
wire   [0:0] tmp_167_fu_1101_p3;
wire   [0:0] or_ln52_10_fu_1143_p2;
wire   [0:0] xor_ln52_5_fu_1149_p2;
wire   [0:0] and_ln52_5_fu_1155_p2;
wire   [0:0] or_ln52_11_fu_1169_p2;
wire   [5:0] select_ln52_10_fu_1161_p3;
wire   [5:0] trunc_ln52_5_fu_1109_p4;
wire   [0:0] icmp_ln51_5_fu_1095_p2;
wire   [5:0] select_ln52_11_fu_1175_p3;
wire   [20:0] trunc_ln44_6_fu_361_p4;
wire   [14:0] tmp_20_fu_1223_p4;
wire   [0:0] tmp_170_fu_1215_p3;
wire   [0:0] icmp_ln52_6_fu_1233_p2;
wire   [0:0] tmp_169_fu_1197_p3;
wire   [0:0] or_ln52_12_fu_1239_p2;
wire   [0:0] xor_ln52_6_fu_1245_p2;
wire   [0:0] and_ln52_6_fu_1251_p2;
wire   [0:0] or_ln52_13_fu_1265_p2;
wire   [5:0] select_ln52_12_fu_1257_p3;
wire   [5:0] trunc_ln52_6_fu_1205_p4;
wire   [0:0] icmp_ln51_6_fu_1191_p2;
wire   [5:0] select_ln52_13_fu_1271_p3;
wire   [20:0] trunc_ln44_7_fu_371_p4;
wire   [14:0] tmp_23_fu_1319_p4;
wire   [0:0] tmp_172_fu_1311_p3;
wire   [0:0] icmp_ln52_7_fu_1329_p2;
wire   [0:0] tmp_171_fu_1293_p3;
wire   [0:0] or_ln52_14_fu_1335_p2;
wire   [0:0] xor_ln52_7_fu_1341_p2;
wire   [0:0] and_ln52_7_fu_1347_p2;
wire   [0:0] or_ln52_15_fu_1361_p2;
wire   [5:0] select_ln52_14_fu_1353_p3;
wire   [5:0] trunc_ln52_7_fu_1301_p4;
wire   [0:0] icmp_ln51_7_fu_1287_p2;
wire   [5:0] select_ln52_15_fu_1367_p3;
wire   [20:0] trunc_ln44_8_fu_381_p4;
wire   [14:0] tmp_26_fu_1415_p4;
wire   [0:0] tmp_174_fu_1407_p3;
wire   [0:0] icmp_ln52_8_fu_1425_p2;
wire   [0:0] tmp_173_fu_1389_p3;
wire   [0:0] or_ln52_16_fu_1431_p2;
wire   [0:0] xor_ln52_8_fu_1437_p2;
wire   [0:0] and_ln52_8_fu_1443_p2;
wire   [0:0] or_ln52_17_fu_1457_p2;
wire   [5:0] select_ln52_16_fu_1449_p3;
wire   [5:0] trunc_ln52_8_fu_1397_p4;
wire   [0:0] icmp_ln51_8_fu_1383_p2;
wire   [5:0] select_ln52_17_fu_1463_p3;
wire   [20:0] trunc_ln44_9_fu_391_p4;
wire   [14:0] tmp_29_fu_1511_p4;
wire   [0:0] tmp_176_fu_1503_p3;
wire   [0:0] icmp_ln52_9_fu_1521_p2;
wire   [0:0] tmp_175_fu_1485_p3;
wire   [0:0] or_ln52_18_fu_1527_p2;
wire   [0:0] xor_ln52_9_fu_1533_p2;
wire   [0:0] and_ln52_9_fu_1539_p2;
wire   [0:0] or_ln52_19_fu_1553_p2;
wire   [5:0] select_ln52_18_fu_1545_p3;
wire   [5:0] trunc_ln52_9_fu_1493_p4;
wire   [0:0] icmp_ln51_9_fu_1479_p2;
wire   [5:0] select_ln52_19_fu_1559_p3;
wire   [20:0] trunc_ln44_10_fu_401_p4;
wire   [14:0] tmp_32_fu_1607_p4;
wire   [0:0] tmp_178_fu_1599_p3;
wire   [0:0] icmp_ln52_10_fu_1617_p2;
wire   [0:0] tmp_177_fu_1581_p3;
wire   [0:0] or_ln52_20_fu_1623_p2;
wire   [0:0] xor_ln52_10_fu_1629_p2;
wire   [0:0] and_ln52_10_fu_1635_p2;
wire   [0:0] or_ln52_21_fu_1649_p2;
wire   [5:0] select_ln52_20_fu_1641_p3;
wire   [5:0] trunc_ln52_s_fu_1589_p4;
wire   [0:0] icmp_ln51_10_fu_1575_p2;
wire   [5:0] select_ln52_21_fu_1655_p3;
wire   [20:0] trunc_ln44_11_fu_411_p4;
wire   [14:0] tmp_35_fu_1703_p4;
wire   [0:0] tmp_180_fu_1695_p3;
wire   [0:0] icmp_ln52_11_fu_1713_p2;
wire   [0:0] tmp_179_fu_1677_p3;
wire   [0:0] or_ln52_22_fu_1719_p2;
wire   [0:0] xor_ln52_11_fu_1725_p2;
wire   [0:0] and_ln52_11_fu_1731_p2;
wire   [0:0] or_ln52_23_fu_1745_p2;
wire   [5:0] select_ln52_22_fu_1737_p3;
wire   [5:0] trunc_ln52_10_fu_1685_p4;
wire   [0:0] icmp_ln51_11_fu_1671_p2;
wire   [5:0] select_ln52_23_fu_1751_p3;
wire   [20:0] trunc_ln44_12_fu_421_p4;
wire   [14:0] tmp_38_fu_1799_p4;
wire   [0:0] tmp_182_fu_1791_p3;
wire   [0:0] icmp_ln52_12_fu_1809_p2;
wire   [0:0] tmp_181_fu_1773_p3;
wire   [0:0] or_ln52_24_fu_1815_p2;
wire   [0:0] xor_ln52_12_fu_1821_p2;
wire   [0:0] and_ln52_12_fu_1827_p2;
wire   [0:0] or_ln52_25_fu_1841_p2;
wire   [5:0] select_ln52_24_fu_1833_p3;
wire   [5:0] trunc_ln52_11_fu_1781_p4;
wire   [0:0] icmp_ln51_12_fu_1767_p2;
wire   [5:0] select_ln52_25_fu_1847_p3;
wire   [20:0] trunc_ln44_13_fu_431_p4;
wire   [14:0] tmp_41_fu_1895_p4;
wire   [0:0] tmp_184_fu_1887_p3;
wire   [0:0] icmp_ln52_13_fu_1905_p2;
wire   [0:0] tmp_183_fu_1869_p3;
wire   [0:0] or_ln52_26_fu_1911_p2;
wire   [0:0] xor_ln52_13_fu_1917_p2;
wire   [0:0] and_ln52_13_fu_1923_p2;
wire   [0:0] or_ln52_27_fu_1937_p2;
wire   [5:0] select_ln52_26_fu_1929_p3;
wire   [5:0] trunc_ln52_12_fu_1877_p4;
wire   [0:0] icmp_ln51_13_fu_1863_p2;
wire   [5:0] select_ln52_27_fu_1943_p3;
wire   [20:0] trunc_ln44_14_fu_441_p4;
wire   [14:0] tmp_44_fu_1991_p4;
wire   [0:0] tmp_186_fu_1983_p3;
wire   [0:0] icmp_ln52_14_fu_2001_p2;
wire   [0:0] tmp_185_fu_1965_p3;
wire   [0:0] or_ln52_28_fu_2007_p2;
wire   [0:0] xor_ln52_14_fu_2013_p2;
wire   [0:0] and_ln52_14_fu_2019_p2;
wire   [0:0] or_ln52_29_fu_2033_p2;
wire   [5:0] select_ln52_28_fu_2025_p3;
wire   [5:0] trunc_ln52_13_fu_1973_p4;
wire   [0:0] icmp_ln51_14_fu_1959_p2;
wire   [5:0] select_ln52_29_fu_2039_p3;
wire   [20:0] trunc_ln44_15_fu_451_p4;
wire   [14:0] tmp_47_fu_2087_p4;
wire   [0:0] tmp_188_fu_2079_p3;
wire   [0:0] icmp_ln52_15_fu_2097_p2;
wire   [0:0] tmp_187_fu_2061_p3;
wire   [0:0] or_ln52_30_fu_2103_p2;
wire   [0:0] xor_ln52_15_fu_2109_p2;
wire   [0:0] and_ln52_15_fu_2115_p2;
wire   [0:0] or_ln52_31_fu_2129_p2;
wire   [5:0] select_ln52_30_fu_2121_p3;
wire   [5:0] trunc_ln52_14_fu_2069_p4;
wire   [0:0] icmp_ln51_15_fu_2055_p2;
wire   [5:0] select_ln52_31_fu_2135_p3;
wire   [20:0] trunc_ln44_16_fu_461_p4;
wire   [14:0] tmp_50_fu_2183_p4;
wire   [0:0] tmp_190_fu_2175_p3;
wire   [0:0] icmp_ln52_16_fu_2193_p2;
wire   [0:0] tmp_189_fu_2157_p3;
wire   [0:0] or_ln52_32_fu_2199_p2;
wire   [0:0] xor_ln52_16_fu_2205_p2;
wire   [0:0] and_ln52_16_fu_2211_p2;
wire   [0:0] or_ln52_33_fu_2225_p2;
wire   [5:0] select_ln52_32_fu_2217_p3;
wire   [5:0] trunc_ln52_15_fu_2165_p4;
wire   [0:0] icmp_ln51_16_fu_2151_p2;
wire   [5:0] select_ln52_33_fu_2231_p3;
wire   [20:0] trunc_ln44_17_fu_471_p4;
wire   [14:0] tmp_53_fu_2279_p4;
wire   [0:0] tmp_192_fu_2271_p3;
wire   [0:0] icmp_ln52_17_fu_2289_p2;
wire   [0:0] tmp_191_fu_2253_p3;
wire   [0:0] or_ln52_34_fu_2295_p2;
wire   [0:0] xor_ln52_17_fu_2301_p2;
wire   [0:0] and_ln52_17_fu_2307_p2;
wire   [0:0] or_ln52_35_fu_2321_p2;
wire   [5:0] select_ln52_34_fu_2313_p3;
wire   [5:0] trunc_ln52_16_fu_2261_p4;
wire   [0:0] icmp_ln51_17_fu_2247_p2;
wire   [5:0] select_ln52_35_fu_2327_p3;
wire   [20:0] trunc_ln44_18_fu_481_p4;
wire   [14:0] tmp_56_fu_2375_p4;
wire   [0:0] tmp_194_fu_2367_p3;
wire   [0:0] icmp_ln52_18_fu_2385_p2;
wire   [0:0] tmp_193_fu_2349_p3;
wire   [0:0] or_ln52_36_fu_2391_p2;
wire   [0:0] xor_ln52_18_fu_2397_p2;
wire   [0:0] and_ln52_18_fu_2403_p2;
wire   [0:0] or_ln52_37_fu_2417_p2;
wire   [5:0] select_ln52_36_fu_2409_p3;
wire   [5:0] trunc_ln52_17_fu_2357_p4;
wire   [0:0] icmp_ln51_18_fu_2343_p2;
wire   [5:0] select_ln52_37_fu_2423_p3;
wire   [20:0] trunc_ln44_19_fu_491_p4;
wire   [14:0] tmp_59_fu_2471_p4;
wire   [0:0] tmp_196_fu_2463_p3;
wire   [0:0] icmp_ln52_19_fu_2481_p2;
wire   [0:0] tmp_195_fu_2445_p3;
wire   [0:0] or_ln52_38_fu_2487_p2;
wire   [0:0] xor_ln52_19_fu_2493_p2;
wire   [0:0] and_ln52_19_fu_2499_p2;
wire   [0:0] or_ln52_39_fu_2513_p2;
wire   [5:0] select_ln52_38_fu_2505_p3;
wire   [5:0] trunc_ln52_18_fu_2453_p4;
wire   [0:0] icmp_ln51_19_fu_2439_p2;
wire   [5:0] select_ln52_39_fu_2519_p3;
wire   [20:0] trunc_ln44_20_fu_501_p4;
wire   [14:0] tmp_62_fu_2567_p4;
wire   [0:0] tmp_198_fu_2559_p3;
wire   [0:0] icmp_ln52_20_fu_2577_p2;
wire   [0:0] tmp_197_fu_2541_p3;
wire   [0:0] or_ln52_40_fu_2583_p2;
wire   [0:0] xor_ln52_20_fu_2589_p2;
wire   [0:0] and_ln52_20_fu_2595_p2;
wire   [0:0] or_ln52_41_fu_2609_p2;
wire   [5:0] select_ln52_40_fu_2601_p3;
wire   [5:0] trunc_ln52_19_fu_2549_p4;
wire   [0:0] icmp_ln51_20_fu_2535_p2;
wire   [5:0] select_ln52_41_fu_2615_p3;
wire   [20:0] trunc_ln44_21_fu_511_p4;
wire   [14:0] tmp_65_fu_2663_p4;
wire   [0:0] tmp_200_fu_2655_p3;
wire   [0:0] icmp_ln52_21_fu_2673_p2;
wire   [0:0] tmp_199_fu_2637_p3;
wire   [0:0] or_ln52_42_fu_2679_p2;
wire   [0:0] xor_ln52_21_fu_2685_p2;
wire   [0:0] and_ln52_21_fu_2691_p2;
wire   [0:0] or_ln52_43_fu_2705_p2;
wire   [5:0] select_ln52_42_fu_2697_p3;
wire   [5:0] trunc_ln52_20_fu_2645_p4;
wire   [0:0] icmp_ln51_21_fu_2631_p2;
wire   [5:0] select_ln52_43_fu_2711_p3;
wire   [20:0] trunc_ln44_22_fu_521_p4;
wire   [14:0] tmp_68_fu_2759_p4;
wire   [0:0] tmp_202_fu_2751_p3;
wire   [0:0] icmp_ln52_22_fu_2769_p2;
wire   [0:0] tmp_201_fu_2733_p3;
wire   [0:0] or_ln52_44_fu_2775_p2;
wire   [0:0] xor_ln52_22_fu_2781_p2;
wire   [0:0] and_ln52_22_fu_2787_p2;
wire   [0:0] or_ln52_45_fu_2801_p2;
wire   [5:0] select_ln52_44_fu_2793_p3;
wire   [5:0] trunc_ln52_21_fu_2741_p4;
wire   [0:0] icmp_ln51_22_fu_2727_p2;
wire   [5:0] select_ln52_45_fu_2807_p3;
wire   [20:0] trunc_ln44_23_fu_531_p4;
wire   [14:0] tmp_71_fu_2855_p4;
wire   [0:0] tmp_204_fu_2847_p3;
wire   [0:0] icmp_ln52_23_fu_2865_p2;
wire   [0:0] tmp_203_fu_2829_p3;
wire   [0:0] or_ln52_46_fu_2871_p2;
wire   [0:0] xor_ln52_23_fu_2877_p2;
wire   [0:0] and_ln52_23_fu_2883_p2;
wire   [0:0] or_ln52_47_fu_2897_p2;
wire   [5:0] select_ln52_46_fu_2889_p3;
wire   [5:0] trunc_ln52_22_fu_2837_p4;
wire   [0:0] icmp_ln51_23_fu_2823_p2;
wire   [5:0] select_ln52_47_fu_2903_p3;
wire   [20:0] trunc_ln44_24_fu_541_p4;
wire   [14:0] tmp_74_fu_2951_p4;
wire   [0:0] tmp_206_fu_2943_p3;
wire   [0:0] icmp_ln52_24_fu_2961_p2;
wire   [0:0] tmp_205_fu_2925_p3;
wire   [0:0] or_ln52_48_fu_2967_p2;
wire   [0:0] xor_ln52_24_fu_2973_p2;
wire   [0:0] and_ln52_24_fu_2979_p2;
wire   [0:0] or_ln52_49_fu_2993_p2;
wire   [5:0] select_ln52_48_fu_2985_p3;
wire   [5:0] trunc_ln52_23_fu_2933_p4;
wire   [0:0] icmp_ln51_24_fu_2919_p2;
wire   [5:0] select_ln52_49_fu_2999_p3;
wire   [20:0] trunc_ln44_25_fu_551_p4;
wire   [14:0] tmp_77_fu_3047_p4;
wire   [0:0] tmp_208_fu_3039_p3;
wire   [0:0] icmp_ln52_25_fu_3057_p2;
wire   [0:0] tmp_207_fu_3021_p3;
wire   [0:0] or_ln52_50_fu_3063_p2;
wire   [0:0] xor_ln52_25_fu_3069_p2;
wire   [0:0] and_ln52_25_fu_3075_p2;
wire   [0:0] or_ln52_51_fu_3089_p2;
wire   [5:0] select_ln52_50_fu_3081_p3;
wire   [5:0] trunc_ln52_24_fu_3029_p4;
wire   [0:0] icmp_ln51_25_fu_3015_p2;
wire   [5:0] select_ln52_51_fu_3095_p3;
wire   [20:0] trunc_ln44_26_fu_561_p4;
wire   [14:0] tmp_80_fu_3143_p4;
wire   [0:0] tmp_210_fu_3135_p3;
wire   [0:0] icmp_ln52_26_fu_3153_p2;
wire   [0:0] tmp_209_fu_3117_p3;
wire   [0:0] or_ln52_52_fu_3159_p2;
wire   [0:0] xor_ln52_26_fu_3165_p2;
wire   [0:0] and_ln52_26_fu_3171_p2;
wire   [0:0] or_ln52_53_fu_3185_p2;
wire   [5:0] select_ln52_52_fu_3177_p3;
wire   [5:0] trunc_ln52_25_fu_3125_p4;
wire   [0:0] icmp_ln51_26_fu_3111_p2;
wire   [5:0] select_ln52_53_fu_3191_p3;
wire   [20:0] trunc_ln44_27_fu_571_p4;
wire   [14:0] tmp_83_fu_3239_p4;
wire   [0:0] tmp_212_fu_3231_p3;
wire   [0:0] icmp_ln52_27_fu_3249_p2;
wire   [0:0] tmp_211_fu_3213_p3;
wire   [0:0] or_ln52_54_fu_3255_p2;
wire   [0:0] xor_ln52_27_fu_3261_p2;
wire   [0:0] and_ln52_27_fu_3267_p2;
wire   [0:0] or_ln52_55_fu_3281_p2;
wire   [5:0] select_ln52_54_fu_3273_p3;
wire   [5:0] trunc_ln52_26_fu_3221_p4;
wire   [0:0] icmp_ln51_27_fu_3207_p2;
wire   [5:0] select_ln52_55_fu_3287_p3;
wire   [20:0] trunc_ln44_28_fu_581_p4;
wire   [14:0] tmp_86_fu_3335_p4;
wire   [0:0] tmp_214_fu_3327_p3;
wire   [0:0] icmp_ln52_28_fu_3345_p2;
wire   [0:0] tmp_213_fu_3309_p3;
wire   [0:0] or_ln52_56_fu_3351_p2;
wire   [0:0] xor_ln52_28_fu_3357_p2;
wire   [0:0] and_ln52_28_fu_3363_p2;
wire   [0:0] or_ln52_57_fu_3377_p2;
wire   [5:0] select_ln52_56_fu_3369_p3;
wire   [5:0] trunc_ln52_27_fu_3317_p4;
wire   [0:0] icmp_ln51_28_fu_3303_p2;
wire   [5:0] select_ln52_57_fu_3383_p3;
wire   [20:0] trunc_ln44_29_fu_591_p4;
wire   [14:0] tmp_89_fu_3431_p4;
wire   [0:0] tmp_216_fu_3423_p3;
wire   [0:0] icmp_ln52_29_fu_3441_p2;
wire   [0:0] tmp_215_fu_3405_p3;
wire   [0:0] or_ln52_58_fu_3447_p2;
wire   [0:0] xor_ln52_29_fu_3453_p2;
wire   [0:0] and_ln52_29_fu_3459_p2;
wire   [0:0] or_ln52_59_fu_3473_p2;
wire   [5:0] select_ln52_58_fu_3465_p3;
wire   [5:0] trunc_ln52_28_fu_3413_p4;
wire   [0:0] icmp_ln51_29_fu_3399_p2;
wire   [5:0] select_ln52_59_fu_3479_p3;
wire   [20:0] trunc_ln44_30_fu_601_p4;
wire   [14:0] tmp_92_fu_3527_p4;
wire   [0:0] tmp_218_fu_3519_p3;
wire   [0:0] icmp_ln52_30_fu_3537_p2;
wire   [0:0] tmp_217_fu_3501_p3;
wire   [0:0] or_ln52_60_fu_3543_p2;
wire   [0:0] xor_ln52_30_fu_3549_p2;
wire   [0:0] and_ln52_30_fu_3555_p2;
wire   [0:0] or_ln52_61_fu_3569_p2;
wire   [5:0] select_ln52_60_fu_3561_p3;
wire   [5:0] trunc_ln52_29_fu_3509_p4;
wire   [0:0] icmp_ln51_30_fu_3495_p2;
wire   [5:0] select_ln52_61_fu_3575_p3;
wire   [20:0] trunc_ln44_s_fu_611_p4;
wire   [14:0] tmp_95_fu_3623_p4;
wire   [0:0] tmp_220_fu_3615_p3;
wire   [0:0] icmp_ln52_31_fu_3633_p2;
wire   [0:0] tmp_219_fu_3597_p3;
wire   [0:0] or_ln52_62_fu_3639_p2;
wire   [0:0] xor_ln52_31_fu_3645_p2;
wire   [0:0] and_ln52_31_fu_3651_p2;
wire   [0:0] or_ln52_63_fu_3665_p2;
wire   [5:0] select_ln52_62_fu_3657_p3;
wire   [5:0] trunc_ln52_30_fu_3605_p4;
wire   [0:0] icmp_ln51_31_fu_3591_p2;
wire   [5:0] select_ln52_63_fu_3671_p3;
wire   [5:0] storemerge556_fu_3679_p3;
wire   [5:0] out_data_0_30_0_0_0_load_fu_3583_p3;
wire   [5:0] out_data_0_29_0_0_0_load_fu_3487_p3;
wire   [5:0] out_data_0_28_0_0_0_load_fu_3391_p3;
wire   [5:0] out_data_0_27_0_0_0_load_fu_3295_p3;
wire   [5:0] out_data_0_26_0_0_0_load_fu_3199_p3;
wire   [5:0] out_data_0_25_0_0_0_load_fu_3103_p3;
wire   [5:0] out_data_0_24_0_0_0_load_fu_3007_p3;
wire   [5:0] out_data_0_23_0_0_0_load_fu_2911_p3;
wire   [5:0] out_data_0_22_0_0_0_load_fu_2815_p3;
wire   [5:0] out_data_0_21_0_0_0_load_fu_2719_p3;
wire   [5:0] out_data_0_20_0_0_0_load_fu_2623_p3;
wire   [5:0] out_data_0_19_0_0_0_load_fu_2527_p3;
wire   [5:0] out_data_0_18_0_0_0_load_fu_2431_p3;
wire   [5:0] out_data_0_17_0_0_0_load_fu_2335_p3;
wire   [5:0] out_data_0_16_0_0_0_load_fu_2239_p3;
wire   [5:0] out_data_0_15_0_0_0_load_fu_2143_p3;
wire   [5:0] out_data_0_14_0_0_0_load_fu_2047_p3;
wire   [5:0] out_data_0_13_0_0_0_load_fu_1951_p3;
wire   [5:0] out_data_0_12_0_0_0_load_fu_1855_p3;
wire   [5:0] out_data_0_11_0_0_0_load_fu_1759_p3;
wire   [5:0] out_data_0_10_0_0_0_load_fu_1663_p3;
wire   [5:0] out_data_0_9_0_0_0_load_fu_1567_p3;
wire   [5:0] out_data_0_8_0_0_0_load_fu_1471_p3;
wire   [5:0] out_data_0_7_0_0_0_load_fu_1375_p3;
wire   [5:0] out_data_0_6_0_0_0_load_fu_1279_p3;
wire   [5:0] out_data_0_5_0_0_0_load_fu_1183_p3;
wire   [5:0] out_data_0_4_0_0_0_load_fu_1087_p3;
wire   [5:0] out_data_0_3_0_0_0_load_fu_991_p3;
wire   [5:0] out_data_0_2_0_0_0_load_fu_895_p3;
wire   [5:0] out_data_0_1_0_0_0_load_fu_799_p3;
wire   [5:0] out_data_0_0_0_0_0_load_fu_703_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_blk_n = layer3_out_empty_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_read = 1'b1;
    end else begin
        layer3_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_write = 1'b1;
    end else begin
        layer4_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln52_10_fu_1635_p2 = (xor_ln52_10_fu_1629_p2 & or_ln52_20_fu_1623_p2);

assign and_ln52_11_fu_1731_p2 = (xor_ln52_11_fu_1725_p2 & or_ln52_22_fu_1719_p2);

assign and_ln52_12_fu_1827_p2 = (xor_ln52_12_fu_1821_p2 & or_ln52_24_fu_1815_p2);

assign and_ln52_13_fu_1923_p2 = (xor_ln52_13_fu_1917_p2 & or_ln52_26_fu_1911_p2);

assign and_ln52_14_fu_2019_p2 = (xor_ln52_14_fu_2013_p2 & or_ln52_28_fu_2007_p2);

assign and_ln52_15_fu_2115_p2 = (xor_ln52_15_fu_2109_p2 & or_ln52_30_fu_2103_p2);

assign and_ln52_16_fu_2211_p2 = (xor_ln52_16_fu_2205_p2 & or_ln52_32_fu_2199_p2);

assign and_ln52_17_fu_2307_p2 = (xor_ln52_17_fu_2301_p2 & or_ln52_34_fu_2295_p2);

assign and_ln52_18_fu_2403_p2 = (xor_ln52_18_fu_2397_p2 & or_ln52_36_fu_2391_p2);

assign and_ln52_19_fu_2499_p2 = (xor_ln52_19_fu_2493_p2 & or_ln52_38_fu_2487_p2);

assign and_ln52_1_fu_771_p2 = (xor_ln52_1_fu_765_p2 & or_ln52_2_fu_759_p2);

assign and_ln52_20_fu_2595_p2 = (xor_ln52_20_fu_2589_p2 & or_ln52_40_fu_2583_p2);

assign and_ln52_21_fu_2691_p2 = (xor_ln52_21_fu_2685_p2 & or_ln52_42_fu_2679_p2);

assign and_ln52_22_fu_2787_p2 = (xor_ln52_22_fu_2781_p2 & or_ln52_44_fu_2775_p2);

assign and_ln52_23_fu_2883_p2 = (xor_ln52_23_fu_2877_p2 & or_ln52_46_fu_2871_p2);

assign and_ln52_24_fu_2979_p2 = (xor_ln52_24_fu_2973_p2 & or_ln52_48_fu_2967_p2);

assign and_ln52_25_fu_3075_p2 = (xor_ln52_25_fu_3069_p2 & or_ln52_50_fu_3063_p2);

assign and_ln52_26_fu_3171_p2 = (xor_ln52_26_fu_3165_p2 & or_ln52_52_fu_3159_p2);

assign and_ln52_27_fu_3267_p2 = (xor_ln52_27_fu_3261_p2 & or_ln52_54_fu_3255_p2);

assign and_ln52_28_fu_3363_p2 = (xor_ln52_28_fu_3357_p2 & or_ln52_56_fu_3351_p2);

assign and_ln52_29_fu_3459_p2 = (xor_ln52_29_fu_3453_p2 & or_ln52_58_fu_3447_p2);

assign and_ln52_2_fu_867_p2 = (xor_ln52_2_fu_861_p2 & or_ln52_4_fu_855_p2);

assign and_ln52_30_fu_3555_p2 = (xor_ln52_30_fu_3549_p2 & or_ln52_60_fu_3543_p2);

assign and_ln52_31_fu_3651_p2 = (xor_ln52_31_fu_3645_p2 & or_ln52_62_fu_3639_p2);

assign and_ln52_3_fu_963_p2 = (xor_ln52_3_fu_957_p2 & or_ln52_6_fu_951_p2);

assign and_ln52_4_fu_1059_p2 = (xor_ln52_4_fu_1053_p2 & or_ln52_8_fu_1047_p2);

assign and_ln52_5_fu_1155_p2 = (xor_ln52_5_fu_1149_p2 & or_ln52_10_fu_1143_p2);

assign and_ln52_6_fu_1251_p2 = (xor_ln52_6_fu_1245_p2 & or_ln52_12_fu_1239_p2);

assign and_ln52_7_fu_1347_p2 = (xor_ln52_7_fu_1341_p2 & or_ln52_14_fu_1335_p2);

assign and_ln52_8_fu_1443_p2 = (xor_ln52_8_fu_1437_p2 & or_ln52_16_fu_1431_p2);

assign and_ln52_9_fu_1539_p2 = (xor_ln52_9_fu_1533_p2 & or_ln52_18_fu_1527_p2);

assign and_ln52_fu_675_p2 = (xor_ln52_fu_669_p2 & or_ln52_fu_663_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer4_out_full_n == 1'b0) | (layer3_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_10_fu_1575_p2 = (($signed(trunc_ln44_10_fu_401_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_1671_p2 = (($signed(trunc_ln44_11_fu_411_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_1767_p2 = (($signed(trunc_ln44_12_fu_421_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_1863_p2 = (($signed(trunc_ln44_13_fu_431_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_1959_p2 = (($signed(trunc_ln44_14_fu_441_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_2055_p2 = (($signed(trunc_ln44_15_fu_451_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_16_fu_2151_p2 = (($signed(trunc_ln44_16_fu_461_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_17_fu_2247_p2 = (($signed(trunc_ln44_17_fu_471_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_18_fu_2343_p2 = (($signed(trunc_ln44_18_fu_481_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_19_fu_2439_p2 = (($signed(trunc_ln44_19_fu_491_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_711_p2 = (($signed(trunc_ln44_1_fu_311_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_20_fu_2535_p2 = (($signed(trunc_ln44_20_fu_501_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_21_fu_2631_p2 = (($signed(trunc_ln44_21_fu_511_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_22_fu_2727_p2 = (($signed(trunc_ln44_22_fu_521_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_23_fu_2823_p2 = (($signed(trunc_ln44_23_fu_531_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_24_fu_2919_p2 = (($signed(trunc_ln44_24_fu_541_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_25_fu_3015_p2 = (($signed(trunc_ln44_25_fu_551_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_26_fu_3111_p2 = (($signed(trunc_ln44_26_fu_561_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_27_fu_3207_p2 = (($signed(trunc_ln44_27_fu_571_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_28_fu_3303_p2 = (($signed(trunc_ln44_28_fu_581_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_29_fu_3399_p2 = (($signed(trunc_ln44_29_fu_591_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_807_p2 = (($signed(trunc_ln44_2_fu_321_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_30_fu_3495_p2 = (($signed(trunc_ln44_30_fu_601_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_31_fu_3591_p2 = (($signed(trunc_ln44_s_fu_611_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_903_p2 = (($signed(trunc_ln44_3_fu_331_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_999_p2 = (($signed(trunc_ln44_4_fu_341_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_1095_p2 = (($signed(trunc_ln44_5_fu_351_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_1191_p2 = (($signed(trunc_ln44_6_fu_361_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_1287_p2 = (($signed(trunc_ln44_7_fu_371_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_1383_p2 = (($signed(trunc_ln44_8_fu_381_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_1479_p2 = (($signed(trunc_ln44_9_fu_391_p4) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_621_p2 = (($signed(trunc_ln44_fu_307_p1) > $signed(21'd0)) ? 1'b1 : 1'b0);

assign icmp_ln52_10_fu_1617_p2 = ((tmp_32_fu_1607_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_11_fu_1713_p2 = ((tmp_35_fu_1703_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_12_fu_1809_p2 = ((tmp_38_fu_1799_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_13_fu_1905_p2 = ((tmp_41_fu_1895_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_14_fu_2001_p2 = ((tmp_44_fu_1991_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_15_fu_2097_p2 = ((tmp_47_fu_2087_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_16_fu_2193_p2 = ((tmp_50_fu_2183_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_17_fu_2289_p2 = ((tmp_53_fu_2279_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_18_fu_2385_p2 = ((tmp_56_fu_2375_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_19_fu_2481_p2 = ((tmp_59_fu_2471_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_1_fu_753_p2 = ((tmp_5_fu_743_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_20_fu_2577_p2 = ((tmp_62_fu_2567_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_21_fu_2673_p2 = ((tmp_65_fu_2663_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_22_fu_2769_p2 = ((tmp_68_fu_2759_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_23_fu_2865_p2 = ((tmp_71_fu_2855_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_24_fu_2961_p2 = ((tmp_74_fu_2951_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_25_fu_3057_p2 = ((tmp_77_fu_3047_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_26_fu_3153_p2 = ((tmp_80_fu_3143_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_27_fu_3249_p2 = ((tmp_83_fu_3239_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_28_fu_3345_p2 = ((tmp_86_fu_3335_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_29_fu_3441_p2 = ((tmp_89_fu_3431_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_2_fu_849_p2 = ((tmp_8_fu_839_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_30_fu_3537_p2 = ((tmp_92_fu_3527_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_31_fu_3633_p2 = ((tmp_95_fu_3623_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_3_fu_945_p2 = ((tmp_11_fu_935_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_4_fu_1041_p2 = ((tmp_14_fu_1031_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_5_fu_1137_p2 = ((tmp_17_fu_1127_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_6_fu_1233_p2 = ((tmp_20_fu_1223_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_7_fu_1329_p2 = ((tmp_23_fu_1319_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_8_fu_1425_p2 = ((tmp_26_fu_1415_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_9_fu_1521_p2 = ((tmp_29_fu_1511_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_657_p2 = ((tmp_2_fu_647_p4 != 15'd0) ? 1'b1 : 1'b0);

assign layer4_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{storemerge556_fu_3679_p3}, {out_data_0_30_0_0_0_load_fu_3583_p3}}, {out_data_0_29_0_0_0_load_fu_3487_p3}}, {out_data_0_28_0_0_0_load_fu_3391_p3}}, {out_data_0_27_0_0_0_load_fu_3295_p3}}, {out_data_0_26_0_0_0_load_fu_3199_p3}}, {out_data_0_25_0_0_0_load_fu_3103_p3}}, {out_data_0_24_0_0_0_load_fu_3007_p3}}, {out_data_0_23_0_0_0_load_fu_2911_p3}}, {out_data_0_22_0_0_0_load_fu_2815_p3}}, {out_data_0_21_0_0_0_load_fu_2719_p3}}, {out_data_0_20_0_0_0_load_fu_2623_p3}}, {out_data_0_19_0_0_0_load_fu_2527_p3}}, {out_data_0_18_0_0_0_load_fu_2431_p3}}, {out_data_0_17_0_0_0_load_fu_2335_p3}}, {out_data_0_16_0_0_0_load_fu_2239_p3}}, {out_data_0_15_0_0_0_load_fu_2143_p3}}, {out_data_0_14_0_0_0_load_fu_2047_p3}}, {out_data_0_13_0_0_0_load_fu_1951_p3}}, {out_data_0_12_0_0_0_load_fu_1855_p3}}, {out_data_0_11_0_0_0_load_fu_1759_p3}}, {out_data_0_10_0_0_0_load_fu_1663_p3}}, {out_data_0_9_0_0_0_load_fu_1567_p3}}, {out_data_0_8_0_0_0_load_fu_1471_p3}}, {out_data_0_7_0_0_0_load_fu_1375_p3}}, {out_data_0_6_0_0_0_load_fu_1279_p3}}, 
    {out_data_0_5_0_0_0_load_fu_1183_p3}}, {out_data_0_4_0_0_0_load_fu_1087_p3}}, {out_data_0_3_0_0_0_load_fu_991_p3}}, {out_data_0_2_0_0_0_load_fu_895_p3}}, {out_data_0_1_0_0_0_load_fu_799_p3}}, {out_data_0_0_0_0_0_load_fu_703_p3}};

assign or_ln52_10_fu_1143_p2 = (tmp_168_fu_1119_p3 | icmp_ln52_5_fu_1137_p2);

assign or_ln52_11_fu_1169_p2 = (tmp_167_fu_1101_p3 | and_ln52_5_fu_1155_p2);

assign or_ln52_12_fu_1239_p2 = (tmp_170_fu_1215_p3 | icmp_ln52_6_fu_1233_p2);

assign or_ln52_13_fu_1265_p2 = (tmp_169_fu_1197_p3 | and_ln52_6_fu_1251_p2);

assign or_ln52_14_fu_1335_p2 = (tmp_172_fu_1311_p3 | icmp_ln52_7_fu_1329_p2);

assign or_ln52_15_fu_1361_p2 = (tmp_171_fu_1293_p3 | and_ln52_7_fu_1347_p2);

assign or_ln52_16_fu_1431_p2 = (tmp_174_fu_1407_p3 | icmp_ln52_8_fu_1425_p2);

assign or_ln52_17_fu_1457_p2 = (tmp_173_fu_1389_p3 | and_ln52_8_fu_1443_p2);

assign or_ln52_18_fu_1527_p2 = (tmp_176_fu_1503_p3 | icmp_ln52_9_fu_1521_p2);

assign or_ln52_19_fu_1553_p2 = (tmp_175_fu_1485_p3 | and_ln52_9_fu_1539_p2);

assign or_ln52_1_fu_689_p2 = (tmp_fu_627_p3 | and_ln52_fu_675_p2);

assign or_ln52_20_fu_1623_p2 = (tmp_178_fu_1599_p3 | icmp_ln52_10_fu_1617_p2);

assign or_ln52_21_fu_1649_p2 = (tmp_177_fu_1581_p3 | and_ln52_10_fu_1635_p2);

assign or_ln52_22_fu_1719_p2 = (tmp_180_fu_1695_p3 | icmp_ln52_11_fu_1713_p2);

assign or_ln52_23_fu_1745_p2 = (tmp_179_fu_1677_p3 | and_ln52_11_fu_1731_p2);

assign or_ln52_24_fu_1815_p2 = (tmp_182_fu_1791_p3 | icmp_ln52_12_fu_1809_p2);

assign or_ln52_25_fu_1841_p2 = (tmp_181_fu_1773_p3 | and_ln52_12_fu_1827_p2);

assign or_ln52_26_fu_1911_p2 = (tmp_184_fu_1887_p3 | icmp_ln52_13_fu_1905_p2);

assign or_ln52_27_fu_1937_p2 = (tmp_183_fu_1869_p3 | and_ln52_13_fu_1923_p2);

assign or_ln52_28_fu_2007_p2 = (tmp_186_fu_1983_p3 | icmp_ln52_14_fu_2001_p2);

assign or_ln52_29_fu_2033_p2 = (tmp_185_fu_1965_p3 | and_ln52_14_fu_2019_p2);

assign or_ln52_2_fu_759_p2 = (tmp_160_fu_735_p3 | icmp_ln52_1_fu_753_p2);

assign or_ln52_30_fu_2103_p2 = (tmp_188_fu_2079_p3 | icmp_ln52_15_fu_2097_p2);

assign or_ln52_31_fu_2129_p2 = (tmp_187_fu_2061_p3 | and_ln52_15_fu_2115_p2);

assign or_ln52_32_fu_2199_p2 = (tmp_190_fu_2175_p3 | icmp_ln52_16_fu_2193_p2);

assign or_ln52_33_fu_2225_p2 = (tmp_189_fu_2157_p3 | and_ln52_16_fu_2211_p2);

assign or_ln52_34_fu_2295_p2 = (tmp_192_fu_2271_p3 | icmp_ln52_17_fu_2289_p2);

assign or_ln52_35_fu_2321_p2 = (tmp_191_fu_2253_p3 | and_ln52_17_fu_2307_p2);

assign or_ln52_36_fu_2391_p2 = (tmp_194_fu_2367_p3 | icmp_ln52_18_fu_2385_p2);

assign or_ln52_37_fu_2417_p2 = (tmp_193_fu_2349_p3 | and_ln52_18_fu_2403_p2);

assign or_ln52_38_fu_2487_p2 = (tmp_196_fu_2463_p3 | icmp_ln52_19_fu_2481_p2);

assign or_ln52_39_fu_2513_p2 = (tmp_195_fu_2445_p3 | and_ln52_19_fu_2499_p2);

assign or_ln52_3_fu_785_p2 = (tmp_159_fu_717_p3 | and_ln52_1_fu_771_p2);

assign or_ln52_40_fu_2583_p2 = (tmp_198_fu_2559_p3 | icmp_ln52_20_fu_2577_p2);

assign or_ln52_41_fu_2609_p2 = (tmp_197_fu_2541_p3 | and_ln52_20_fu_2595_p2);

assign or_ln52_42_fu_2679_p2 = (tmp_200_fu_2655_p3 | icmp_ln52_21_fu_2673_p2);

assign or_ln52_43_fu_2705_p2 = (tmp_199_fu_2637_p3 | and_ln52_21_fu_2691_p2);

assign or_ln52_44_fu_2775_p2 = (tmp_202_fu_2751_p3 | icmp_ln52_22_fu_2769_p2);

assign or_ln52_45_fu_2801_p2 = (tmp_201_fu_2733_p3 | and_ln52_22_fu_2787_p2);

assign or_ln52_46_fu_2871_p2 = (tmp_204_fu_2847_p3 | icmp_ln52_23_fu_2865_p2);

assign or_ln52_47_fu_2897_p2 = (tmp_203_fu_2829_p3 | and_ln52_23_fu_2883_p2);

assign or_ln52_48_fu_2967_p2 = (tmp_206_fu_2943_p3 | icmp_ln52_24_fu_2961_p2);

assign or_ln52_49_fu_2993_p2 = (tmp_205_fu_2925_p3 | and_ln52_24_fu_2979_p2);

assign or_ln52_4_fu_855_p2 = (tmp_162_fu_831_p3 | icmp_ln52_2_fu_849_p2);

assign or_ln52_50_fu_3063_p2 = (tmp_208_fu_3039_p3 | icmp_ln52_25_fu_3057_p2);

assign or_ln52_51_fu_3089_p2 = (tmp_207_fu_3021_p3 | and_ln52_25_fu_3075_p2);

assign or_ln52_52_fu_3159_p2 = (tmp_210_fu_3135_p3 | icmp_ln52_26_fu_3153_p2);

assign or_ln52_53_fu_3185_p2 = (tmp_209_fu_3117_p3 | and_ln52_26_fu_3171_p2);

assign or_ln52_54_fu_3255_p2 = (tmp_212_fu_3231_p3 | icmp_ln52_27_fu_3249_p2);

assign or_ln52_55_fu_3281_p2 = (tmp_211_fu_3213_p3 | and_ln52_27_fu_3267_p2);

assign or_ln52_56_fu_3351_p2 = (tmp_214_fu_3327_p3 | icmp_ln52_28_fu_3345_p2);

assign or_ln52_57_fu_3377_p2 = (tmp_213_fu_3309_p3 | and_ln52_28_fu_3363_p2);

assign or_ln52_58_fu_3447_p2 = (tmp_216_fu_3423_p3 | icmp_ln52_29_fu_3441_p2);

assign or_ln52_59_fu_3473_p2 = (tmp_215_fu_3405_p3 | and_ln52_29_fu_3459_p2);

assign or_ln52_5_fu_881_p2 = (tmp_161_fu_813_p3 | and_ln52_2_fu_867_p2);

assign or_ln52_60_fu_3543_p2 = (tmp_218_fu_3519_p3 | icmp_ln52_30_fu_3537_p2);

assign or_ln52_61_fu_3569_p2 = (tmp_217_fu_3501_p3 | and_ln52_30_fu_3555_p2);

assign or_ln52_62_fu_3639_p2 = (tmp_220_fu_3615_p3 | icmp_ln52_31_fu_3633_p2);

assign or_ln52_63_fu_3665_p2 = (tmp_219_fu_3597_p3 | and_ln52_31_fu_3651_p2);

assign or_ln52_6_fu_951_p2 = (tmp_164_fu_927_p3 | icmp_ln52_3_fu_945_p2);

assign or_ln52_7_fu_977_p2 = (tmp_163_fu_909_p3 | and_ln52_3_fu_963_p2);

assign or_ln52_8_fu_1047_p2 = (tmp_166_fu_1023_p3 | icmp_ln52_4_fu_1041_p2);

assign or_ln52_9_fu_1073_p2 = (tmp_165_fu_1005_p3 | and_ln52_4_fu_1059_p2);

assign or_ln52_fu_663_p2 = (tmp_158_fu_639_p3 | icmp_ln52_fu_657_p2);

assign out_data_0_0_0_0_0_load_fu_703_p3 = ((icmp_ln51_fu_621_p2[0:0] == 1'b1) ? select_ln52_1_fu_695_p3 : 6'd0);

assign out_data_0_10_0_0_0_load_fu_1663_p3 = ((icmp_ln51_10_fu_1575_p2[0:0] == 1'b1) ? select_ln52_21_fu_1655_p3 : 6'd0);

assign out_data_0_11_0_0_0_load_fu_1759_p3 = ((icmp_ln51_11_fu_1671_p2[0:0] == 1'b1) ? select_ln52_23_fu_1751_p3 : 6'd0);

assign out_data_0_12_0_0_0_load_fu_1855_p3 = ((icmp_ln51_12_fu_1767_p2[0:0] == 1'b1) ? select_ln52_25_fu_1847_p3 : 6'd0);

assign out_data_0_13_0_0_0_load_fu_1951_p3 = ((icmp_ln51_13_fu_1863_p2[0:0] == 1'b1) ? select_ln52_27_fu_1943_p3 : 6'd0);

assign out_data_0_14_0_0_0_load_fu_2047_p3 = ((icmp_ln51_14_fu_1959_p2[0:0] == 1'b1) ? select_ln52_29_fu_2039_p3 : 6'd0);

assign out_data_0_15_0_0_0_load_fu_2143_p3 = ((icmp_ln51_15_fu_2055_p2[0:0] == 1'b1) ? select_ln52_31_fu_2135_p3 : 6'd0);

assign out_data_0_16_0_0_0_load_fu_2239_p3 = ((icmp_ln51_16_fu_2151_p2[0:0] == 1'b1) ? select_ln52_33_fu_2231_p3 : 6'd0);

assign out_data_0_17_0_0_0_load_fu_2335_p3 = ((icmp_ln51_17_fu_2247_p2[0:0] == 1'b1) ? select_ln52_35_fu_2327_p3 : 6'd0);

assign out_data_0_18_0_0_0_load_fu_2431_p3 = ((icmp_ln51_18_fu_2343_p2[0:0] == 1'b1) ? select_ln52_37_fu_2423_p3 : 6'd0);

assign out_data_0_19_0_0_0_load_fu_2527_p3 = ((icmp_ln51_19_fu_2439_p2[0:0] == 1'b1) ? select_ln52_39_fu_2519_p3 : 6'd0);

assign out_data_0_1_0_0_0_load_fu_799_p3 = ((icmp_ln51_1_fu_711_p2[0:0] == 1'b1) ? select_ln52_3_fu_791_p3 : 6'd0);

assign out_data_0_20_0_0_0_load_fu_2623_p3 = ((icmp_ln51_20_fu_2535_p2[0:0] == 1'b1) ? select_ln52_41_fu_2615_p3 : 6'd0);

assign out_data_0_21_0_0_0_load_fu_2719_p3 = ((icmp_ln51_21_fu_2631_p2[0:0] == 1'b1) ? select_ln52_43_fu_2711_p3 : 6'd0);

assign out_data_0_22_0_0_0_load_fu_2815_p3 = ((icmp_ln51_22_fu_2727_p2[0:0] == 1'b1) ? select_ln52_45_fu_2807_p3 : 6'd0);

assign out_data_0_23_0_0_0_load_fu_2911_p3 = ((icmp_ln51_23_fu_2823_p2[0:0] == 1'b1) ? select_ln52_47_fu_2903_p3 : 6'd0);

assign out_data_0_24_0_0_0_load_fu_3007_p3 = ((icmp_ln51_24_fu_2919_p2[0:0] == 1'b1) ? select_ln52_49_fu_2999_p3 : 6'd0);

assign out_data_0_25_0_0_0_load_fu_3103_p3 = ((icmp_ln51_25_fu_3015_p2[0:0] == 1'b1) ? select_ln52_51_fu_3095_p3 : 6'd0);

assign out_data_0_26_0_0_0_load_fu_3199_p3 = ((icmp_ln51_26_fu_3111_p2[0:0] == 1'b1) ? select_ln52_53_fu_3191_p3 : 6'd0);

assign out_data_0_27_0_0_0_load_fu_3295_p3 = ((icmp_ln51_27_fu_3207_p2[0:0] == 1'b1) ? select_ln52_55_fu_3287_p3 : 6'd0);

assign out_data_0_28_0_0_0_load_fu_3391_p3 = ((icmp_ln51_28_fu_3303_p2[0:0] == 1'b1) ? select_ln52_57_fu_3383_p3 : 6'd0);

assign out_data_0_29_0_0_0_load_fu_3487_p3 = ((icmp_ln51_29_fu_3399_p2[0:0] == 1'b1) ? select_ln52_59_fu_3479_p3 : 6'd0);

assign out_data_0_2_0_0_0_load_fu_895_p3 = ((icmp_ln51_2_fu_807_p2[0:0] == 1'b1) ? select_ln52_5_fu_887_p3 : 6'd0);

assign out_data_0_30_0_0_0_load_fu_3583_p3 = ((icmp_ln51_30_fu_3495_p2[0:0] == 1'b1) ? select_ln52_61_fu_3575_p3 : 6'd0);

assign out_data_0_3_0_0_0_load_fu_991_p3 = ((icmp_ln51_3_fu_903_p2[0:0] == 1'b1) ? select_ln52_7_fu_983_p3 : 6'd0);

assign out_data_0_4_0_0_0_load_fu_1087_p3 = ((icmp_ln51_4_fu_999_p2[0:0] == 1'b1) ? select_ln52_9_fu_1079_p3 : 6'd0);

assign out_data_0_5_0_0_0_load_fu_1183_p3 = ((icmp_ln51_5_fu_1095_p2[0:0] == 1'b1) ? select_ln52_11_fu_1175_p3 : 6'd0);

assign out_data_0_6_0_0_0_load_fu_1279_p3 = ((icmp_ln51_6_fu_1191_p2[0:0] == 1'b1) ? select_ln52_13_fu_1271_p3 : 6'd0);

assign out_data_0_7_0_0_0_load_fu_1375_p3 = ((icmp_ln51_7_fu_1287_p2[0:0] == 1'b1) ? select_ln52_15_fu_1367_p3 : 6'd0);

assign out_data_0_8_0_0_0_load_fu_1471_p3 = ((icmp_ln51_8_fu_1383_p2[0:0] == 1'b1) ? select_ln52_17_fu_1463_p3 : 6'd0);

assign out_data_0_9_0_0_0_load_fu_1567_p3 = ((icmp_ln51_9_fu_1479_p2[0:0] == 1'b1) ? select_ln52_19_fu_1559_p3 : 6'd0);

assign select_ln52_10_fu_1161_p3 = ((and_ln52_5_fu_1155_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_11_fu_1175_p3 = ((or_ln52_11_fu_1169_p2[0:0] == 1'b1) ? select_ln52_10_fu_1161_p3 : trunc_ln52_5_fu_1109_p4);

assign select_ln52_12_fu_1257_p3 = ((and_ln52_6_fu_1251_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_13_fu_1271_p3 = ((or_ln52_13_fu_1265_p2[0:0] == 1'b1) ? select_ln52_12_fu_1257_p3 : trunc_ln52_6_fu_1205_p4);

assign select_ln52_14_fu_1353_p3 = ((and_ln52_7_fu_1347_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_15_fu_1367_p3 = ((or_ln52_15_fu_1361_p2[0:0] == 1'b1) ? select_ln52_14_fu_1353_p3 : trunc_ln52_7_fu_1301_p4);

assign select_ln52_16_fu_1449_p3 = ((and_ln52_8_fu_1443_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_17_fu_1463_p3 = ((or_ln52_17_fu_1457_p2[0:0] == 1'b1) ? select_ln52_16_fu_1449_p3 : trunc_ln52_8_fu_1397_p4);

assign select_ln52_18_fu_1545_p3 = ((and_ln52_9_fu_1539_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_19_fu_1559_p3 = ((or_ln52_19_fu_1553_p2[0:0] == 1'b1) ? select_ln52_18_fu_1545_p3 : trunc_ln52_9_fu_1493_p4);

assign select_ln52_1_fu_695_p3 = ((or_ln52_1_fu_689_p2[0:0] == 1'b1) ? select_ln52_fu_681_p3 : trunc_ln52_fu_635_p1);

assign select_ln52_20_fu_1641_p3 = ((and_ln52_10_fu_1635_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_21_fu_1655_p3 = ((or_ln52_21_fu_1649_p2[0:0] == 1'b1) ? select_ln52_20_fu_1641_p3 : trunc_ln52_s_fu_1589_p4);

assign select_ln52_22_fu_1737_p3 = ((and_ln52_11_fu_1731_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_23_fu_1751_p3 = ((or_ln52_23_fu_1745_p2[0:0] == 1'b1) ? select_ln52_22_fu_1737_p3 : trunc_ln52_10_fu_1685_p4);

assign select_ln52_24_fu_1833_p3 = ((and_ln52_12_fu_1827_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_25_fu_1847_p3 = ((or_ln52_25_fu_1841_p2[0:0] == 1'b1) ? select_ln52_24_fu_1833_p3 : trunc_ln52_11_fu_1781_p4);

assign select_ln52_26_fu_1929_p3 = ((and_ln52_13_fu_1923_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_27_fu_1943_p3 = ((or_ln52_27_fu_1937_p2[0:0] == 1'b1) ? select_ln52_26_fu_1929_p3 : trunc_ln52_12_fu_1877_p4);

assign select_ln52_28_fu_2025_p3 = ((and_ln52_14_fu_2019_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_29_fu_2039_p3 = ((or_ln52_29_fu_2033_p2[0:0] == 1'b1) ? select_ln52_28_fu_2025_p3 : trunc_ln52_13_fu_1973_p4);

assign select_ln52_2_fu_777_p3 = ((and_ln52_1_fu_771_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_30_fu_2121_p3 = ((and_ln52_15_fu_2115_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_31_fu_2135_p3 = ((or_ln52_31_fu_2129_p2[0:0] == 1'b1) ? select_ln52_30_fu_2121_p3 : trunc_ln52_14_fu_2069_p4);

assign select_ln52_32_fu_2217_p3 = ((and_ln52_16_fu_2211_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_33_fu_2231_p3 = ((or_ln52_33_fu_2225_p2[0:0] == 1'b1) ? select_ln52_32_fu_2217_p3 : trunc_ln52_15_fu_2165_p4);

assign select_ln52_34_fu_2313_p3 = ((and_ln52_17_fu_2307_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_35_fu_2327_p3 = ((or_ln52_35_fu_2321_p2[0:0] == 1'b1) ? select_ln52_34_fu_2313_p3 : trunc_ln52_16_fu_2261_p4);

assign select_ln52_36_fu_2409_p3 = ((and_ln52_18_fu_2403_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_37_fu_2423_p3 = ((or_ln52_37_fu_2417_p2[0:0] == 1'b1) ? select_ln52_36_fu_2409_p3 : trunc_ln52_17_fu_2357_p4);

assign select_ln52_38_fu_2505_p3 = ((and_ln52_19_fu_2499_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_39_fu_2519_p3 = ((or_ln52_39_fu_2513_p2[0:0] == 1'b1) ? select_ln52_38_fu_2505_p3 : trunc_ln52_18_fu_2453_p4);

assign select_ln52_3_fu_791_p3 = ((or_ln52_3_fu_785_p2[0:0] == 1'b1) ? select_ln52_2_fu_777_p3 : trunc_ln52_1_fu_725_p4);

assign select_ln52_40_fu_2601_p3 = ((and_ln52_20_fu_2595_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_41_fu_2615_p3 = ((or_ln52_41_fu_2609_p2[0:0] == 1'b1) ? select_ln52_40_fu_2601_p3 : trunc_ln52_19_fu_2549_p4);

assign select_ln52_42_fu_2697_p3 = ((and_ln52_21_fu_2691_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_43_fu_2711_p3 = ((or_ln52_43_fu_2705_p2[0:0] == 1'b1) ? select_ln52_42_fu_2697_p3 : trunc_ln52_20_fu_2645_p4);

assign select_ln52_44_fu_2793_p3 = ((and_ln52_22_fu_2787_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_45_fu_2807_p3 = ((or_ln52_45_fu_2801_p2[0:0] == 1'b1) ? select_ln52_44_fu_2793_p3 : trunc_ln52_21_fu_2741_p4);

assign select_ln52_46_fu_2889_p3 = ((and_ln52_23_fu_2883_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_47_fu_2903_p3 = ((or_ln52_47_fu_2897_p2[0:0] == 1'b1) ? select_ln52_46_fu_2889_p3 : trunc_ln52_22_fu_2837_p4);

assign select_ln52_48_fu_2985_p3 = ((and_ln52_24_fu_2979_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_49_fu_2999_p3 = ((or_ln52_49_fu_2993_p2[0:0] == 1'b1) ? select_ln52_48_fu_2985_p3 : trunc_ln52_23_fu_2933_p4);

assign select_ln52_4_fu_873_p3 = ((and_ln52_2_fu_867_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_50_fu_3081_p3 = ((and_ln52_25_fu_3075_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_51_fu_3095_p3 = ((or_ln52_51_fu_3089_p2[0:0] == 1'b1) ? select_ln52_50_fu_3081_p3 : trunc_ln52_24_fu_3029_p4);

assign select_ln52_52_fu_3177_p3 = ((and_ln52_26_fu_3171_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_53_fu_3191_p3 = ((or_ln52_53_fu_3185_p2[0:0] == 1'b1) ? select_ln52_52_fu_3177_p3 : trunc_ln52_25_fu_3125_p4);

assign select_ln52_54_fu_3273_p3 = ((and_ln52_27_fu_3267_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_55_fu_3287_p3 = ((or_ln52_55_fu_3281_p2[0:0] == 1'b1) ? select_ln52_54_fu_3273_p3 : trunc_ln52_26_fu_3221_p4);

assign select_ln52_56_fu_3369_p3 = ((and_ln52_28_fu_3363_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_57_fu_3383_p3 = ((or_ln52_57_fu_3377_p2[0:0] == 1'b1) ? select_ln52_56_fu_3369_p3 : trunc_ln52_27_fu_3317_p4);

assign select_ln52_58_fu_3465_p3 = ((and_ln52_29_fu_3459_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_59_fu_3479_p3 = ((or_ln52_59_fu_3473_p2[0:0] == 1'b1) ? select_ln52_58_fu_3465_p3 : trunc_ln52_28_fu_3413_p4);

assign select_ln52_5_fu_887_p3 = ((or_ln52_5_fu_881_p2[0:0] == 1'b1) ? select_ln52_4_fu_873_p3 : trunc_ln52_2_fu_821_p4);

assign select_ln52_60_fu_3561_p3 = ((and_ln52_30_fu_3555_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_61_fu_3575_p3 = ((or_ln52_61_fu_3569_p2[0:0] == 1'b1) ? select_ln52_60_fu_3561_p3 : trunc_ln52_29_fu_3509_p4);

assign select_ln52_62_fu_3657_p3 = ((and_ln52_31_fu_3651_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_63_fu_3671_p3 = ((or_ln52_63_fu_3665_p2[0:0] == 1'b1) ? select_ln52_62_fu_3657_p3 : trunc_ln52_30_fu_3605_p4);

assign select_ln52_6_fu_969_p3 = ((and_ln52_3_fu_963_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_7_fu_983_p3 = ((or_ln52_7_fu_977_p2[0:0] == 1'b1) ? select_ln52_6_fu_969_p3 : trunc_ln52_3_fu_917_p4);

assign select_ln52_8_fu_1065_p3 = ((and_ln52_4_fu_1059_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign select_ln52_9_fu_1079_p3 = ((or_ln52_9_fu_1073_p2[0:0] == 1'b1) ? select_ln52_8_fu_1065_p3 : trunc_ln52_4_fu_1013_p4);

assign select_ln52_fu_681_p3 = ((and_ln52_fu_675_p2[0:0] == 1'b1) ? 6'd31 : 6'd32);

assign start_out = real_start;

assign storemerge556_fu_3679_p3 = ((icmp_ln51_31_fu_3591_p2[0:0] == 1'b1) ? select_ln52_63_fu_3671_p3 : 6'd0);

assign tmp_11_fu_935_p4 = {{layer3_out_dout[83:69]}};

assign tmp_14_fu_1031_p4 = {{layer3_out_dout[104:90]}};

assign tmp_158_fu_639_p3 = layer3_out_dout[32'd5];

assign tmp_159_fu_717_p3 = layer3_out_dout[32'd41];

assign tmp_160_fu_735_p3 = layer3_out_dout[32'd26];

assign tmp_161_fu_813_p3 = layer3_out_dout[32'd62];

assign tmp_162_fu_831_p3 = layer3_out_dout[32'd47];

assign tmp_163_fu_909_p3 = layer3_out_dout[32'd83];

assign tmp_164_fu_927_p3 = layer3_out_dout[32'd68];

assign tmp_165_fu_1005_p3 = layer3_out_dout[32'd104];

assign tmp_166_fu_1023_p3 = layer3_out_dout[32'd89];

assign tmp_167_fu_1101_p3 = layer3_out_dout[32'd125];

assign tmp_168_fu_1119_p3 = layer3_out_dout[32'd110];

assign tmp_169_fu_1197_p3 = layer3_out_dout[32'd146];

assign tmp_170_fu_1215_p3 = layer3_out_dout[32'd131];

assign tmp_171_fu_1293_p3 = layer3_out_dout[32'd167];

assign tmp_172_fu_1311_p3 = layer3_out_dout[32'd152];

assign tmp_173_fu_1389_p3 = layer3_out_dout[32'd188];

assign tmp_174_fu_1407_p3 = layer3_out_dout[32'd173];

assign tmp_175_fu_1485_p3 = layer3_out_dout[32'd209];

assign tmp_176_fu_1503_p3 = layer3_out_dout[32'd194];

assign tmp_177_fu_1581_p3 = layer3_out_dout[32'd230];

assign tmp_178_fu_1599_p3 = layer3_out_dout[32'd215];

assign tmp_179_fu_1677_p3 = layer3_out_dout[32'd251];

assign tmp_17_fu_1127_p4 = {{layer3_out_dout[125:111]}};

assign tmp_180_fu_1695_p3 = layer3_out_dout[32'd236];

assign tmp_181_fu_1773_p3 = layer3_out_dout[32'd272];

assign tmp_182_fu_1791_p3 = layer3_out_dout[32'd257];

assign tmp_183_fu_1869_p3 = layer3_out_dout[32'd293];

assign tmp_184_fu_1887_p3 = layer3_out_dout[32'd278];

assign tmp_185_fu_1965_p3 = layer3_out_dout[32'd314];

assign tmp_186_fu_1983_p3 = layer3_out_dout[32'd299];

assign tmp_187_fu_2061_p3 = layer3_out_dout[32'd335];

assign tmp_188_fu_2079_p3 = layer3_out_dout[32'd320];

assign tmp_189_fu_2157_p3 = layer3_out_dout[32'd356];

assign tmp_190_fu_2175_p3 = layer3_out_dout[32'd341];

assign tmp_191_fu_2253_p3 = layer3_out_dout[32'd377];

assign tmp_192_fu_2271_p3 = layer3_out_dout[32'd362];

assign tmp_193_fu_2349_p3 = layer3_out_dout[32'd398];

assign tmp_194_fu_2367_p3 = layer3_out_dout[32'd383];

assign tmp_195_fu_2445_p3 = layer3_out_dout[32'd419];

assign tmp_196_fu_2463_p3 = layer3_out_dout[32'd404];

assign tmp_197_fu_2541_p3 = layer3_out_dout[32'd440];

assign tmp_198_fu_2559_p3 = layer3_out_dout[32'd425];

assign tmp_199_fu_2637_p3 = layer3_out_dout[32'd461];

assign tmp_200_fu_2655_p3 = layer3_out_dout[32'd446];

assign tmp_201_fu_2733_p3 = layer3_out_dout[32'd482];

assign tmp_202_fu_2751_p3 = layer3_out_dout[32'd467];

assign tmp_203_fu_2829_p3 = layer3_out_dout[32'd503];

assign tmp_204_fu_2847_p3 = layer3_out_dout[32'd488];

assign tmp_205_fu_2925_p3 = layer3_out_dout[32'd524];

assign tmp_206_fu_2943_p3 = layer3_out_dout[32'd509];

assign tmp_207_fu_3021_p3 = layer3_out_dout[32'd545];

assign tmp_208_fu_3039_p3 = layer3_out_dout[32'd530];

assign tmp_209_fu_3117_p3 = layer3_out_dout[32'd566];

assign tmp_20_fu_1223_p4 = {{layer3_out_dout[146:132]}};

assign tmp_210_fu_3135_p3 = layer3_out_dout[32'd551];

assign tmp_211_fu_3213_p3 = layer3_out_dout[32'd587];

assign tmp_212_fu_3231_p3 = layer3_out_dout[32'd572];

assign tmp_213_fu_3309_p3 = layer3_out_dout[32'd608];

assign tmp_214_fu_3327_p3 = layer3_out_dout[32'd593];

assign tmp_215_fu_3405_p3 = layer3_out_dout[32'd629];

assign tmp_216_fu_3423_p3 = layer3_out_dout[32'd614];

assign tmp_217_fu_3501_p3 = layer3_out_dout[32'd650];

assign tmp_218_fu_3519_p3 = layer3_out_dout[32'd635];

assign tmp_219_fu_3597_p3 = layer3_out_dout[32'd671];

assign tmp_220_fu_3615_p3 = layer3_out_dout[32'd656];

assign tmp_23_fu_1319_p4 = {{layer3_out_dout[167:153]}};

assign tmp_26_fu_1415_p4 = {{layer3_out_dout[188:174]}};

assign tmp_29_fu_1511_p4 = {{layer3_out_dout[209:195]}};

assign tmp_2_fu_647_p4 = {{layer3_out_dout[20:6]}};

assign tmp_32_fu_1607_p4 = {{layer3_out_dout[230:216]}};

assign tmp_35_fu_1703_p4 = {{layer3_out_dout[251:237]}};

assign tmp_38_fu_1799_p4 = {{layer3_out_dout[272:258]}};

assign tmp_41_fu_1895_p4 = {{layer3_out_dout[293:279]}};

assign tmp_44_fu_1991_p4 = {{layer3_out_dout[314:300]}};

assign tmp_47_fu_2087_p4 = {{layer3_out_dout[335:321]}};

assign tmp_50_fu_2183_p4 = {{layer3_out_dout[356:342]}};

assign tmp_53_fu_2279_p4 = {{layer3_out_dout[377:363]}};

assign tmp_56_fu_2375_p4 = {{layer3_out_dout[398:384]}};

assign tmp_59_fu_2471_p4 = {{layer3_out_dout[419:405]}};

assign tmp_5_fu_743_p4 = {{layer3_out_dout[41:27]}};

assign tmp_62_fu_2567_p4 = {{layer3_out_dout[440:426]}};

assign tmp_65_fu_2663_p4 = {{layer3_out_dout[461:447]}};

assign tmp_68_fu_2759_p4 = {{layer3_out_dout[482:468]}};

assign tmp_71_fu_2855_p4 = {{layer3_out_dout[503:489]}};

assign tmp_74_fu_2951_p4 = {{layer3_out_dout[524:510]}};

assign tmp_77_fu_3047_p4 = {{layer3_out_dout[545:531]}};

assign tmp_80_fu_3143_p4 = {{layer3_out_dout[566:552]}};

assign tmp_83_fu_3239_p4 = {{layer3_out_dout[587:573]}};

assign tmp_86_fu_3335_p4 = {{layer3_out_dout[608:594]}};

assign tmp_89_fu_3431_p4 = {{layer3_out_dout[629:615]}};

assign tmp_8_fu_839_p4 = {{layer3_out_dout[62:48]}};

assign tmp_92_fu_3527_p4 = {{layer3_out_dout[650:636]}};

assign tmp_95_fu_3623_p4 = {{layer3_out_dout[671:657]}};

assign tmp_fu_627_p3 = layer3_out_dout[32'd20];

assign trunc_ln44_10_fu_401_p4 = {{layer3_out_dout[230:210]}};

assign trunc_ln44_11_fu_411_p4 = {{layer3_out_dout[251:231]}};

assign trunc_ln44_12_fu_421_p4 = {{layer3_out_dout[272:252]}};

assign trunc_ln44_13_fu_431_p4 = {{layer3_out_dout[293:273]}};

assign trunc_ln44_14_fu_441_p4 = {{layer3_out_dout[314:294]}};

assign trunc_ln44_15_fu_451_p4 = {{layer3_out_dout[335:315]}};

assign trunc_ln44_16_fu_461_p4 = {{layer3_out_dout[356:336]}};

assign trunc_ln44_17_fu_471_p4 = {{layer3_out_dout[377:357]}};

assign trunc_ln44_18_fu_481_p4 = {{layer3_out_dout[398:378]}};

assign trunc_ln44_19_fu_491_p4 = {{layer3_out_dout[419:399]}};

assign trunc_ln44_1_fu_311_p4 = {{layer3_out_dout[41:21]}};

assign trunc_ln44_20_fu_501_p4 = {{layer3_out_dout[440:420]}};

assign trunc_ln44_21_fu_511_p4 = {{layer3_out_dout[461:441]}};

assign trunc_ln44_22_fu_521_p4 = {{layer3_out_dout[482:462]}};

assign trunc_ln44_23_fu_531_p4 = {{layer3_out_dout[503:483]}};

assign trunc_ln44_24_fu_541_p4 = {{layer3_out_dout[524:504]}};

assign trunc_ln44_25_fu_551_p4 = {{layer3_out_dout[545:525]}};

assign trunc_ln44_26_fu_561_p4 = {{layer3_out_dout[566:546]}};

assign trunc_ln44_27_fu_571_p4 = {{layer3_out_dout[587:567]}};

assign trunc_ln44_28_fu_581_p4 = {{layer3_out_dout[608:588]}};

assign trunc_ln44_29_fu_591_p4 = {{layer3_out_dout[629:609]}};

assign trunc_ln44_2_fu_321_p4 = {{layer3_out_dout[62:42]}};

assign trunc_ln44_30_fu_601_p4 = {{layer3_out_dout[650:630]}};

assign trunc_ln44_3_fu_331_p4 = {{layer3_out_dout[83:63]}};

assign trunc_ln44_4_fu_341_p4 = {{layer3_out_dout[104:84]}};

assign trunc_ln44_5_fu_351_p4 = {{layer3_out_dout[125:105]}};

assign trunc_ln44_6_fu_361_p4 = {{layer3_out_dout[146:126]}};

assign trunc_ln44_7_fu_371_p4 = {{layer3_out_dout[167:147]}};

assign trunc_ln44_8_fu_381_p4 = {{layer3_out_dout[188:168]}};

assign trunc_ln44_9_fu_391_p4 = {{layer3_out_dout[209:189]}};

assign trunc_ln44_fu_307_p1 = layer3_out_dout[20:0];

assign trunc_ln44_s_fu_611_p4 = {{layer3_out_dout[671:651]}};

assign trunc_ln52_10_fu_1685_p4 = {{layer3_out_dout[236:231]}};

assign trunc_ln52_11_fu_1781_p4 = {{layer3_out_dout[257:252]}};

assign trunc_ln52_12_fu_1877_p4 = {{layer3_out_dout[278:273]}};

assign trunc_ln52_13_fu_1973_p4 = {{layer3_out_dout[299:294]}};

assign trunc_ln52_14_fu_2069_p4 = {{layer3_out_dout[320:315]}};

assign trunc_ln52_15_fu_2165_p4 = {{layer3_out_dout[341:336]}};

assign trunc_ln52_16_fu_2261_p4 = {{layer3_out_dout[362:357]}};

assign trunc_ln52_17_fu_2357_p4 = {{layer3_out_dout[383:378]}};

assign trunc_ln52_18_fu_2453_p4 = {{layer3_out_dout[404:399]}};

assign trunc_ln52_19_fu_2549_p4 = {{layer3_out_dout[425:420]}};

assign trunc_ln52_1_fu_725_p4 = {{layer3_out_dout[26:21]}};

assign trunc_ln52_20_fu_2645_p4 = {{layer3_out_dout[446:441]}};

assign trunc_ln52_21_fu_2741_p4 = {{layer3_out_dout[467:462]}};

assign trunc_ln52_22_fu_2837_p4 = {{layer3_out_dout[488:483]}};

assign trunc_ln52_23_fu_2933_p4 = {{layer3_out_dout[509:504]}};

assign trunc_ln52_24_fu_3029_p4 = {{layer3_out_dout[530:525]}};

assign trunc_ln52_25_fu_3125_p4 = {{layer3_out_dout[551:546]}};

assign trunc_ln52_26_fu_3221_p4 = {{layer3_out_dout[572:567]}};

assign trunc_ln52_27_fu_3317_p4 = {{layer3_out_dout[593:588]}};

assign trunc_ln52_28_fu_3413_p4 = {{layer3_out_dout[614:609]}};

assign trunc_ln52_29_fu_3509_p4 = {{layer3_out_dout[635:630]}};

assign trunc_ln52_2_fu_821_p4 = {{layer3_out_dout[47:42]}};

assign trunc_ln52_30_fu_3605_p4 = {{layer3_out_dout[656:651]}};

assign trunc_ln52_3_fu_917_p4 = {{layer3_out_dout[68:63]}};

assign trunc_ln52_4_fu_1013_p4 = {{layer3_out_dout[89:84]}};

assign trunc_ln52_5_fu_1109_p4 = {{layer3_out_dout[110:105]}};

assign trunc_ln52_6_fu_1205_p4 = {{layer3_out_dout[131:126]}};

assign trunc_ln52_7_fu_1301_p4 = {{layer3_out_dout[152:147]}};

assign trunc_ln52_8_fu_1397_p4 = {{layer3_out_dout[173:168]}};

assign trunc_ln52_9_fu_1493_p4 = {{layer3_out_dout[194:189]}};

assign trunc_ln52_fu_635_p1 = layer3_out_dout[5:0];

assign trunc_ln52_s_fu_1589_p4 = {{layer3_out_dout[215:210]}};

assign xor_ln52_10_fu_1629_p2 = (tmp_177_fu_1581_p3 ^ 1'd1);

assign xor_ln52_11_fu_1725_p2 = (tmp_179_fu_1677_p3 ^ 1'd1);

assign xor_ln52_12_fu_1821_p2 = (tmp_181_fu_1773_p3 ^ 1'd1);

assign xor_ln52_13_fu_1917_p2 = (tmp_183_fu_1869_p3 ^ 1'd1);

assign xor_ln52_14_fu_2013_p2 = (tmp_185_fu_1965_p3 ^ 1'd1);

assign xor_ln52_15_fu_2109_p2 = (tmp_187_fu_2061_p3 ^ 1'd1);

assign xor_ln52_16_fu_2205_p2 = (tmp_189_fu_2157_p3 ^ 1'd1);

assign xor_ln52_17_fu_2301_p2 = (tmp_191_fu_2253_p3 ^ 1'd1);

assign xor_ln52_18_fu_2397_p2 = (tmp_193_fu_2349_p3 ^ 1'd1);

assign xor_ln52_19_fu_2493_p2 = (tmp_195_fu_2445_p3 ^ 1'd1);

assign xor_ln52_1_fu_765_p2 = (tmp_159_fu_717_p3 ^ 1'd1);

assign xor_ln52_20_fu_2589_p2 = (tmp_197_fu_2541_p3 ^ 1'd1);

assign xor_ln52_21_fu_2685_p2 = (tmp_199_fu_2637_p3 ^ 1'd1);

assign xor_ln52_22_fu_2781_p2 = (tmp_201_fu_2733_p3 ^ 1'd1);

assign xor_ln52_23_fu_2877_p2 = (tmp_203_fu_2829_p3 ^ 1'd1);

assign xor_ln52_24_fu_2973_p2 = (tmp_205_fu_2925_p3 ^ 1'd1);

assign xor_ln52_25_fu_3069_p2 = (tmp_207_fu_3021_p3 ^ 1'd1);

assign xor_ln52_26_fu_3165_p2 = (tmp_209_fu_3117_p3 ^ 1'd1);

assign xor_ln52_27_fu_3261_p2 = (tmp_211_fu_3213_p3 ^ 1'd1);

assign xor_ln52_28_fu_3357_p2 = (tmp_213_fu_3309_p3 ^ 1'd1);

assign xor_ln52_29_fu_3453_p2 = (tmp_215_fu_3405_p3 ^ 1'd1);

assign xor_ln52_2_fu_861_p2 = (tmp_161_fu_813_p3 ^ 1'd1);

assign xor_ln52_30_fu_3549_p2 = (tmp_217_fu_3501_p3 ^ 1'd1);

assign xor_ln52_31_fu_3645_p2 = (tmp_219_fu_3597_p3 ^ 1'd1);

assign xor_ln52_3_fu_957_p2 = (tmp_163_fu_909_p3 ^ 1'd1);

assign xor_ln52_4_fu_1053_p2 = (tmp_165_fu_1005_p3 ^ 1'd1);

assign xor_ln52_5_fu_1149_p2 = (tmp_167_fu_1101_p3 ^ 1'd1);

assign xor_ln52_6_fu_1245_p2 = (tmp_169_fu_1197_p3 ^ 1'd1);

assign xor_ln52_7_fu_1341_p2 = (tmp_171_fu_1293_p3 ^ 1'd1);

assign xor_ln52_8_fu_1437_p2 = (tmp_173_fu_1389_p3 ^ 1'd1);

assign xor_ln52_9_fu_1533_p2 = (tmp_175_fu_1485_p3 ^ 1'd1);

assign xor_ln52_fu_669_p2 = (tmp_fu_627_p3 ^ 1'd1);

endmodule //wedrowiec_hls_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_s
