// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module wedrowiec_hls_axi_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer3_out_dout,
        layer3_out_empty_n,
        layer3_out_read,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap,
        layer4_out_din,
        layer4_out_full_n,
        layer4_out_write,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [799:0] layer3_out_dout;
input   layer3_out_empty_n;
output   layer3_out_read;
input  [1:0] layer3_out_num_data_valid;
input  [1:0] layer3_out_fifo_cap;
output  [319:0] layer4_out_din;
input   layer4_out_full_n;
output   layer4_out_write;
input  [1:0] layer4_out_num_data_valid;
input  [1:0] layer4_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer3_out_read;
reg layer4_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer3_out_blk_n;
reg    layer4_out_blk_n;
reg    ap_block_state1;
wire   [24:0] trunc_ln44_fu_439_p1;
wire   [0:0] tmp_239_fu_777_p3;
wire   [9:0] trunc_ln4_fu_767_p4;
wire   [9:0] zext_ln52_fu_793_p1;
wire   [9:0] add_ln52_fu_797_p2;
wire   [7:0] tmp_s_fu_811_p4;
wire   [0:0] tmp_240_fu_785_p3;
wire   [0:0] tmp_241_fu_803_p3;
wire   [0:0] xor_ln52_fu_827_p2;
wire   [0:0] icmp_ln52_fu_821_p2;
wire   [0:0] or_ln52_97_fu_833_p2;
wire   [0:0] and_ln52_fu_839_p2;
wire   [0:0] xor_ln52_96_fu_845_p2;
wire   [0:0] tmp_fu_759_p3;
wire   [0:0] or_ln52_fu_851_p2;
wire   [0:0] xor_ln52_97_fu_857_p2;
wire   [0:0] and_ln52_64_fu_863_p2;
wire   [0:0] or_ln52_99_fu_877_p2;
wire   [9:0] select_ln52_fu_869_p3;
wire   [0:0] icmp_ln51_fu_753_p2;
wire   [9:0] select_ln52_64_fu_883_p3;
wire   [24:0] trunc_ln44_s_fu_443_p4;
wire   [0:0] tmp_244_fu_923_p3;
wire   [9:0] trunc_ln52_s_fu_913_p4;
wire   [9:0] zext_ln52_32_fu_939_p1;
wire   [9:0] add_ln52_32_fu_943_p2;
wire   [7:0] tmp_59_fu_957_p4;
wire   [0:0] tmp_245_fu_931_p3;
wire   [0:0] tmp_246_fu_949_p3;
wire   [0:0] xor_ln52_98_fu_973_p2;
wire   [0:0] icmp_ln52_32_fu_967_p2;
wire   [0:0] or_ln52_101_fu_979_p2;
wire   [0:0] and_ln52_65_fu_985_p2;
wire   [0:0] xor_ln52_99_fu_991_p2;
wire   [0:0] tmp_242_fu_905_p3;
wire   [0:0] or_ln52_96_fu_997_p2;
wire   [0:0] xor_ln52_100_fu_1003_p2;
wire   [0:0] and_ln52_66_fu_1009_p2;
wire   [0:0] or_ln52_103_fu_1023_p2;
wire   [9:0] select_ln52_65_fu_1015_p3;
wire   [0:0] icmp_ln51_32_fu_899_p2;
wire   [9:0] select_ln52_66_fu_1029_p3;
wire   [24:0] trunc_ln44_31_fu_453_p4;
wire   [0:0] tmp_249_fu_1069_p3;
wire   [9:0] trunc_ln52_31_fu_1059_p4;
wire   [9:0] zext_ln52_33_fu_1085_p1;
wire   [9:0] add_ln52_33_fu_1089_p2;
wire   [7:0] tmp_60_fu_1103_p4;
wire   [0:0] tmp_250_fu_1077_p3;
wire   [0:0] tmp_251_fu_1095_p3;
wire   [0:0] xor_ln52_101_fu_1119_p2;
wire   [0:0] icmp_ln52_33_fu_1113_p2;
wire   [0:0] or_ln52_105_fu_1125_p2;
wire   [0:0] and_ln52_67_fu_1131_p2;
wire   [0:0] xor_ln52_102_fu_1137_p2;
wire   [0:0] tmp_247_fu_1051_p3;
wire   [0:0] or_ln52_98_fu_1143_p2;
wire   [0:0] xor_ln52_103_fu_1149_p2;
wire   [0:0] and_ln52_68_fu_1155_p2;
wire   [0:0] or_ln52_107_fu_1169_p2;
wire   [9:0] select_ln52_67_fu_1161_p3;
wire   [0:0] icmp_ln51_33_fu_1045_p2;
wire   [9:0] select_ln52_68_fu_1175_p3;
wire   [24:0] trunc_ln44_32_fu_463_p4;
wire   [0:0] tmp_254_fu_1215_p3;
wire   [9:0] trunc_ln52_32_fu_1205_p4;
wire   [9:0] zext_ln52_34_fu_1231_p1;
wire   [9:0] add_ln52_34_fu_1235_p2;
wire   [7:0] tmp_61_fu_1249_p4;
wire   [0:0] tmp_255_fu_1223_p3;
wire   [0:0] tmp_256_fu_1241_p3;
wire   [0:0] xor_ln52_104_fu_1265_p2;
wire   [0:0] icmp_ln52_34_fu_1259_p2;
wire   [0:0] or_ln52_109_fu_1271_p2;
wire   [0:0] and_ln52_69_fu_1277_p2;
wire   [0:0] xor_ln52_105_fu_1283_p2;
wire   [0:0] tmp_252_fu_1197_p3;
wire   [0:0] or_ln52_100_fu_1289_p2;
wire   [0:0] xor_ln52_106_fu_1295_p2;
wire   [0:0] and_ln52_70_fu_1301_p2;
wire   [0:0] or_ln52_111_fu_1315_p2;
wire   [9:0] select_ln52_69_fu_1307_p3;
wire   [0:0] icmp_ln51_34_fu_1191_p2;
wire   [9:0] select_ln52_70_fu_1321_p3;
wire   [24:0] trunc_ln44_33_fu_473_p4;
wire   [0:0] tmp_259_fu_1361_p3;
wire   [9:0] trunc_ln52_33_fu_1351_p4;
wire   [9:0] zext_ln52_35_fu_1377_p1;
wire   [9:0] add_ln52_35_fu_1381_p2;
wire   [7:0] tmp_62_fu_1395_p4;
wire   [0:0] tmp_260_fu_1369_p3;
wire   [0:0] tmp_261_fu_1387_p3;
wire   [0:0] xor_ln52_107_fu_1411_p2;
wire   [0:0] icmp_ln52_35_fu_1405_p2;
wire   [0:0] or_ln52_113_fu_1417_p2;
wire   [0:0] and_ln52_71_fu_1423_p2;
wire   [0:0] xor_ln52_108_fu_1429_p2;
wire   [0:0] tmp_257_fu_1343_p3;
wire   [0:0] or_ln52_102_fu_1435_p2;
wire   [0:0] xor_ln52_109_fu_1441_p2;
wire   [0:0] and_ln52_72_fu_1447_p2;
wire   [0:0] or_ln52_115_fu_1461_p2;
wire   [9:0] select_ln52_71_fu_1453_p3;
wire   [0:0] icmp_ln51_35_fu_1337_p2;
wire   [9:0] select_ln52_72_fu_1467_p3;
wire   [24:0] trunc_ln44_34_fu_483_p4;
wire   [0:0] tmp_264_fu_1507_p3;
wire   [9:0] trunc_ln52_34_fu_1497_p4;
wire   [9:0] zext_ln52_36_fu_1523_p1;
wire   [9:0] add_ln52_36_fu_1527_p2;
wire   [7:0] tmp_63_fu_1541_p4;
wire   [0:0] tmp_265_fu_1515_p3;
wire   [0:0] tmp_266_fu_1533_p3;
wire   [0:0] xor_ln52_110_fu_1557_p2;
wire   [0:0] icmp_ln52_36_fu_1551_p2;
wire   [0:0] or_ln52_117_fu_1563_p2;
wire   [0:0] and_ln52_73_fu_1569_p2;
wire   [0:0] xor_ln52_111_fu_1575_p2;
wire   [0:0] tmp_262_fu_1489_p3;
wire   [0:0] or_ln52_104_fu_1581_p2;
wire   [0:0] xor_ln52_112_fu_1587_p2;
wire   [0:0] and_ln52_74_fu_1593_p2;
wire   [0:0] or_ln52_119_fu_1607_p2;
wire   [9:0] select_ln52_73_fu_1599_p3;
wire   [0:0] icmp_ln51_36_fu_1483_p2;
wire   [9:0] select_ln52_74_fu_1613_p3;
wire   [24:0] trunc_ln44_35_fu_493_p4;
wire   [0:0] tmp_269_fu_1653_p3;
wire   [9:0] trunc_ln52_35_fu_1643_p4;
wire   [9:0] zext_ln52_37_fu_1669_p1;
wire   [9:0] add_ln52_37_fu_1673_p2;
wire   [7:0] tmp_64_fu_1687_p4;
wire   [0:0] tmp_270_fu_1661_p3;
wire   [0:0] tmp_271_fu_1679_p3;
wire   [0:0] xor_ln52_113_fu_1703_p2;
wire   [0:0] icmp_ln52_37_fu_1697_p2;
wire   [0:0] or_ln52_121_fu_1709_p2;
wire   [0:0] and_ln52_75_fu_1715_p2;
wire   [0:0] xor_ln52_114_fu_1721_p2;
wire   [0:0] tmp_267_fu_1635_p3;
wire   [0:0] or_ln52_106_fu_1727_p2;
wire   [0:0] xor_ln52_115_fu_1733_p2;
wire   [0:0] and_ln52_76_fu_1739_p2;
wire   [0:0] or_ln52_123_fu_1753_p2;
wire   [9:0] select_ln52_75_fu_1745_p3;
wire   [0:0] icmp_ln51_37_fu_1629_p2;
wire   [9:0] select_ln52_76_fu_1759_p3;
wire   [24:0] trunc_ln44_36_fu_503_p4;
wire   [0:0] tmp_274_fu_1799_p3;
wire   [9:0] trunc_ln52_36_fu_1789_p4;
wire   [9:0] zext_ln52_38_fu_1815_p1;
wire   [9:0] add_ln52_38_fu_1819_p2;
wire   [7:0] tmp_65_fu_1833_p4;
wire   [0:0] tmp_275_fu_1807_p3;
wire   [0:0] tmp_276_fu_1825_p3;
wire   [0:0] xor_ln52_116_fu_1849_p2;
wire   [0:0] icmp_ln52_38_fu_1843_p2;
wire   [0:0] or_ln52_125_fu_1855_p2;
wire   [0:0] and_ln52_77_fu_1861_p2;
wire   [0:0] xor_ln52_117_fu_1867_p2;
wire   [0:0] tmp_272_fu_1781_p3;
wire   [0:0] or_ln52_108_fu_1873_p2;
wire   [0:0] xor_ln52_118_fu_1879_p2;
wire   [0:0] and_ln52_78_fu_1885_p2;
wire   [0:0] or_ln52_127_fu_1899_p2;
wire   [9:0] select_ln52_77_fu_1891_p3;
wire   [0:0] icmp_ln51_38_fu_1775_p2;
wire   [9:0] select_ln52_78_fu_1905_p3;
wire   [24:0] trunc_ln44_37_fu_513_p4;
wire   [0:0] tmp_279_fu_1945_p3;
wire   [9:0] trunc_ln52_37_fu_1935_p4;
wire   [9:0] zext_ln52_39_fu_1961_p1;
wire   [9:0] add_ln52_39_fu_1965_p2;
wire   [7:0] tmp_66_fu_1979_p4;
wire   [0:0] tmp_280_fu_1953_p3;
wire   [0:0] tmp_281_fu_1971_p3;
wire   [0:0] xor_ln52_119_fu_1995_p2;
wire   [0:0] icmp_ln52_39_fu_1989_p2;
wire   [0:0] or_ln52_129_fu_2001_p2;
wire   [0:0] and_ln52_79_fu_2007_p2;
wire   [0:0] xor_ln52_120_fu_2013_p2;
wire   [0:0] tmp_277_fu_1927_p3;
wire   [0:0] or_ln52_110_fu_2019_p2;
wire   [0:0] xor_ln52_121_fu_2025_p2;
wire   [0:0] and_ln52_80_fu_2031_p2;
wire   [0:0] or_ln52_131_fu_2045_p2;
wire   [9:0] select_ln52_79_fu_2037_p3;
wire   [0:0] icmp_ln51_39_fu_1921_p2;
wire   [9:0] select_ln52_80_fu_2051_p3;
wire   [24:0] trunc_ln44_38_fu_523_p4;
wire   [0:0] tmp_284_fu_2091_p3;
wire   [9:0] trunc_ln52_38_fu_2081_p4;
wire   [9:0] zext_ln52_40_fu_2107_p1;
wire   [9:0] add_ln52_40_fu_2111_p2;
wire   [7:0] tmp_67_fu_2125_p4;
wire   [0:0] tmp_285_fu_2099_p3;
wire   [0:0] tmp_286_fu_2117_p3;
wire   [0:0] xor_ln52_122_fu_2141_p2;
wire   [0:0] icmp_ln52_40_fu_2135_p2;
wire   [0:0] or_ln52_133_fu_2147_p2;
wire   [0:0] and_ln52_81_fu_2153_p2;
wire   [0:0] xor_ln52_123_fu_2159_p2;
wire   [0:0] tmp_282_fu_2073_p3;
wire   [0:0] or_ln52_112_fu_2165_p2;
wire   [0:0] xor_ln52_124_fu_2171_p2;
wire   [0:0] and_ln52_82_fu_2177_p2;
wire   [0:0] or_ln52_135_fu_2191_p2;
wire   [9:0] select_ln52_81_fu_2183_p3;
wire   [0:0] icmp_ln51_40_fu_2067_p2;
wire   [9:0] select_ln52_82_fu_2197_p3;
wire   [24:0] trunc_ln44_39_fu_533_p4;
wire   [0:0] tmp_289_fu_2237_p3;
wire   [9:0] trunc_ln52_39_fu_2227_p4;
wire   [9:0] zext_ln52_41_fu_2253_p1;
wire   [9:0] add_ln52_41_fu_2257_p2;
wire   [7:0] tmp_68_fu_2271_p4;
wire   [0:0] tmp_290_fu_2245_p3;
wire   [0:0] tmp_291_fu_2263_p3;
wire   [0:0] xor_ln52_125_fu_2287_p2;
wire   [0:0] icmp_ln52_41_fu_2281_p2;
wire   [0:0] or_ln52_137_fu_2293_p2;
wire   [0:0] and_ln52_83_fu_2299_p2;
wire   [0:0] xor_ln52_126_fu_2305_p2;
wire   [0:0] tmp_287_fu_2219_p3;
wire   [0:0] or_ln52_114_fu_2311_p2;
wire   [0:0] xor_ln52_127_fu_2317_p2;
wire   [0:0] and_ln52_84_fu_2323_p2;
wire   [0:0] or_ln52_139_fu_2337_p2;
wire   [9:0] select_ln52_83_fu_2329_p3;
wire   [0:0] icmp_ln51_41_fu_2213_p2;
wire   [9:0] select_ln52_84_fu_2343_p3;
wire   [24:0] trunc_ln44_40_fu_543_p4;
wire   [0:0] tmp_294_fu_2383_p3;
wire   [9:0] trunc_ln52_40_fu_2373_p4;
wire   [9:0] zext_ln52_42_fu_2399_p1;
wire   [9:0] add_ln52_42_fu_2403_p2;
wire   [7:0] tmp_69_fu_2417_p4;
wire   [0:0] tmp_295_fu_2391_p3;
wire   [0:0] tmp_296_fu_2409_p3;
wire   [0:0] xor_ln52_128_fu_2433_p2;
wire   [0:0] icmp_ln52_42_fu_2427_p2;
wire   [0:0] or_ln52_141_fu_2439_p2;
wire   [0:0] and_ln52_85_fu_2445_p2;
wire   [0:0] xor_ln52_129_fu_2451_p2;
wire   [0:0] tmp_292_fu_2365_p3;
wire   [0:0] or_ln52_116_fu_2457_p2;
wire   [0:0] xor_ln52_130_fu_2463_p2;
wire   [0:0] and_ln52_86_fu_2469_p2;
wire   [0:0] or_ln52_143_fu_2483_p2;
wire   [9:0] select_ln52_85_fu_2475_p3;
wire   [0:0] icmp_ln51_42_fu_2359_p2;
wire   [9:0] select_ln52_86_fu_2489_p3;
wire   [24:0] trunc_ln44_41_fu_553_p4;
wire   [0:0] tmp_299_fu_2529_p3;
wire   [9:0] trunc_ln52_41_fu_2519_p4;
wire   [9:0] zext_ln52_43_fu_2545_p1;
wire   [9:0] add_ln52_43_fu_2549_p2;
wire   [7:0] tmp_70_fu_2563_p4;
wire   [0:0] tmp_300_fu_2537_p3;
wire   [0:0] tmp_301_fu_2555_p3;
wire   [0:0] xor_ln52_131_fu_2579_p2;
wire   [0:0] icmp_ln52_43_fu_2573_p2;
wire   [0:0] or_ln52_145_fu_2585_p2;
wire   [0:0] and_ln52_87_fu_2591_p2;
wire   [0:0] xor_ln52_132_fu_2597_p2;
wire   [0:0] tmp_297_fu_2511_p3;
wire   [0:0] or_ln52_118_fu_2603_p2;
wire   [0:0] xor_ln52_133_fu_2609_p2;
wire   [0:0] and_ln52_88_fu_2615_p2;
wire   [0:0] or_ln52_147_fu_2629_p2;
wire   [9:0] select_ln52_87_fu_2621_p3;
wire   [0:0] icmp_ln51_43_fu_2505_p2;
wire   [9:0] select_ln52_88_fu_2635_p3;
wire   [24:0] trunc_ln44_42_fu_563_p4;
wire   [0:0] tmp_304_fu_2675_p3;
wire   [9:0] trunc_ln52_42_fu_2665_p4;
wire   [9:0] zext_ln52_44_fu_2691_p1;
wire   [9:0] add_ln52_44_fu_2695_p2;
wire   [7:0] tmp_71_fu_2709_p4;
wire   [0:0] tmp_305_fu_2683_p3;
wire   [0:0] tmp_306_fu_2701_p3;
wire   [0:0] xor_ln52_134_fu_2725_p2;
wire   [0:0] icmp_ln52_44_fu_2719_p2;
wire   [0:0] or_ln52_149_fu_2731_p2;
wire   [0:0] and_ln52_89_fu_2737_p2;
wire   [0:0] xor_ln52_135_fu_2743_p2;
wire   [0:0] tmp_302_fu_2657_p3;
wire   [0:0] or_ln52_120_fu_2749_p2;
wire   [0:0] xor_ln52_136_fu_2755_p2;
wire   [0:0] and_ln52_90_fu_2761_p2;
wire   [0:0] or_ln52_151_fu_2775_p2;
wire   [9:0] select_ln52_89_fu_2767_p3;
wire   [0:0] icmp_ln51_44_fu_2651_p2;
wire   [9:0] select_ln52_90_fu_2781_p3;
wire   [24:0] trunc_ln44_43_fu_573_p4;
wire   [0:0] tmp_309_fu_2821_p3;
wire   [9:0] trunc_ln52_43_fu_2811_p4;
wire   [9:0] zext_ln52_45_fu_2837_p1;
wire   [9:0] add_ln52_45_fu_2841_p2;
wire   [7:0] tmp_72_fu_2855_p4;
wire   [0:0] tmp_310_fu_2829_p3;
wire   [0:0] tmp_311_fu_2847_p3;
wire   [0:0] xor_ln52_137_fu_2871_p2;
wire   [0:0] icmp_ln52_45_fu_2865_p2;
wire   [0:0] or_ln52_153_fu_2877_p2;
wire   [0:0] and_ln52_91_fu_2883_p2;
wire   [0:0] xor_ln52_138_fu_2889_p2;
wire   [0:0] tmp_307_fu_2803_p3;
wire   [0:0] or_ln52_122_fu_2895_p2;
wire   [0:0] xor_ln52_139_fu_2901_p2;
wire   [0:0] and_ln52_92_fu_2907_p2;
wire   [0:0] or_ln52_155_fu_2921_p2;
wire   [9:0] select_ln52_91_fu_2913_p3;
wire   [0:0] icmp_ln51_45_fu_2797_p2;
wire   [9:0] select_ln52_92_fu_2927_p3;
wire   [24:0] trunc_ln44_44_fu_583_p4;
wire   [0:0] tmp_314_fu_2967_p3;
wire   [9:0] trunc_ln52_44_fu_2957_p4;
wire   [9:0] zext_ln52_46_fu_2983_p1;
wire   [9:0] add_ln52_46_fu_2987_p2;
wire   [7:0] tmp_73_fu_3001_p4;
wire   [0:0] tmp_315_fu_2975_p3;
wire   [0:0] tmp_316_fu_2993_p3;
wire   [0:0] xor_ln52_140_fu_3017_p2;
wire   [0:0] icmp_ln52_46_fu_3011_p2;
wire   [0:0] or_ln52_157_fu_3023_p2;
wire   [0:0] and_ln52_93_fu_3029_p2;
wire   [0:0] xor_ln52_141_fu_3035_p2;
wire   [0:0] tmp_312_fu_2949_p3;
wire   [0:0] or_ln52_124_fu_3041_p2;
wire   [0:0] xor_ln52_142_fu_3047_p2;
wire   [0:0] and_ln52_94_fu_3053_p2;
wire   [0:0] or_ln52_158_fu_3067_p2;
wire   [9:0] select_ln52_93_fu_3059_p3;
wire   [0:0] icmp_ln51_46_fu_2943_p2;
wire   [9:0] select_ln52_94_fu_3073_p3;
wire   [24:0] trunc_ln44_45_fu_593_p4;
wire   [0:0] tmp_319_fu_3113_p3;
wire   [9:0] trunc_ln52_45_fu_3103_p4;
wire   [9:0] zext_ln52_47_fu_3129_p1;
wire   [9:0] add_ln52_47_fu_3133_p2;
wire   [7:0] tmp_74_fu_3147_p4;
wire   [0:0] tmp_320_fu_3121_p3;
wire   [0:0] tmp_321_fu_3139_p3;
wire   [0:0] xor_ln52_143_fu_3163_p2;
wire   [0:0] icmp_ln52_47_fu_3157_p2;
wire   [0:0] or_ln52_159_fu_3169_p2;
wire   [0:0] and_ln52_95_fu_3175_p2;
wire   [0:0] xor_ln52_144_fu_3181_p2;
wire   [0:0] tmp_317_fu_3095_p3;
wire   [0:0] or_ln52_126_fu_3187_p2;
wire   [0:0] xor_ln52_145_fu_3193_p2;
wire   [0:0] and_ln52_96_fu_3199_p2;
wire   [0:0] or_ln52_160_fu_3213_p2;
wire   [9:0] select_ln52_95_fu_3205_p3;
wire   [0:0] icmp_ln51_47_fu_3089_p2;
wire   [9:0] select_ln52_96_fu_3219_p3;
wire   [24:0] trunc_ln44_46_fu_603_p4;
wire   [0:0] tmp_324_fu_3259_p3;
wire   [9:0] trunc_ln52_46_fu_3249_p4;
wire   [9:0] zext_ln52_48_fu_3275_p1;
wire   [9:0] add_ln52_48_fu_3279_p2;
wire   [7:0] tmp_75_fu_3293_p4;
wire   [0:0] tmp_325_fu_3267_p3;
wire   [0:0] tmp_326_fu_3285_p3;
wire   [0:0] xor_ln52_146_fu_3309_p2;
wire   [0:0] icmp_ln52_48_fu_3303_p2;
wire   [0:0] or_ln52_161_fu_3315_p2;
wire   [0:0] and_ln52_97_fu_3321_p2;
wire   [0:0] xor_ln52_147_fu_3327_p2;
wire   [0:0] tmp_322_fu_3241_p3;
wire   [0:0] or_ln52_128_fu_3333_p2;
wire   [0:0] xor_ln52_148_fu_3339_p2;
wire   [0:0] and_ln52_98_fu_3345_p2;
wire   [0:0] or_ln52_162_fu_3359_p2;
wire   [9:0] select_ln52_97_fu_3351_p3;
wire   [0:0] icmp_ln51_48_fu_3235_p2;
wire   [9:0] select_ln52_98_fu_3365_p3;
wire   [24:0] trunc_ln44_47_fu_613_p4;
wire   [0:0] tmp_329_fu_3405_p3;
wire   [9:0] trunc_ln52_47_fu_3395_p4;
wire   [9:0] zext_ln52_49_fu_3421_p1;
wire   [9:0] add_ln52_49_fu_3425_p2;
wire   [7:0] tmp_76_fu_3439_p4;
wire   [0:0] tmp_330_fu_3413_p3;
wire   [0:0] tmp_331_fu_3431_p3;
wire   [0:0] xor_ln52_149_fu_3455_p2;
wire   [0:0] icmp_ln52_49_fu_3449_p2;
wire   [0:0] or_ln52_163_fu_3461_p2;
wire   [0:0] and_ln52_99_fu_3467_p2;
wire   [0:0] xor_ln52_150_fu_3473_p2;
wire   [0:0] tmp_327_fu_3387_p3;
wire   [0:0] or_ln52_130_fu_3479_p2;
wire   [0:0] xor_ln52_151_fu_3485_p2;
wire   [0:0] and_ln52_100_fu_3491_p2;
wire   [0:0] or_ln52_164_fu_3505_p2;
wire   [9:0] select_ln52_99_fu_3497_p3;
wire   [0:0] icmp_ln51_49_fu_3381_p2;
wire   [9:0] select_ln52_100_fu_3511_p3;
wire   [24:0] trunc_ln44_48_fu_623_p4;
wire   [0:0] tmp_334_fu_3551_p3;
wire   [9:0] trunc_ln52_48_fu_3541_p4;
wire   [9:0] zext_ln52_50_fu_3567_p1;
wire   [9:0] add_ln52_50_fu_3571_p2;
wire   [7:0] tmp_77_fu_3585_p4;
wire   [0:0] tmp_335_fu_3559_p3;
wire   [0:0] tmp_336_fu_3577_p3;
wire   [0:0] xor_ln52_152_fu_3601_p2;
wire   [0:0] icmp_ln52_50_fu_3595_p2;
wire   [0:0] or_ln52_165_fu_3607_p2;
wire   [0:0] and_ln52_101_fu_3613_p2;
wire   [0:0] xor_ln52_153_fu_3619_p2;
wire   [0:0] tmp_332_fu_3533_p3;
wire   [0:0] or_ln52_132_fu_3625_p2;
wire   [0:0] xor_ln52_154_fu_3631_p2;
wire   [0:0] and_ln52_102_fu_3637_p2;
wire   [0:0] or_ln52_166_fu_3651_p2;
wire   [9:0] select_ln52_101_fu_3643_p3;
wire   [0:0] icmp_ln51_50_fu_3527_p2;
wire   [9:0] select_ln52_102_fu_3657_p3;
wire   [24:0] trunc_ln44_49_fu_633_p4;
wire   [0:0] tmp_339_fu_3697_p3;
wire   [9:0] trunc_ln52_49_fu_3687_p4;
wire   [9:0] zext_ln52_51_fu_3713_p1;
wire   [9:0] add_ln52_51_fu_3717_p2;
wire   [7:0] tmp_78_fu_3731_p4;
wire   [0:0] tmp_340_fu_3705_p3;
wire   [0:0] tmp_341_fu_3723_p3;
wire   [0:0] xor_ln52_155_fu_3747_p2;
wire   [0:0] icmp_ln52_51_fu_3741_p2;
wire   [0:0] or_ln52_167_fu_3753_p2;
wire   [0:0] and_ln52_103_fu_3759_p2;
wire   [0:0] xor_ln52_156_fu_3765_p2;
wire   [0:0] tmp_337_fu_3679_p3;
wire   [0:0] or_ln52_134_fu_3771_p2;
wire   [0:0] xor_ln52_157_fu_3777_p2;
wire   [0:0] and_ln52_104_fu_3783_p2;
wire   [0:0] or_ln52_168_fu_3797_p2;
wire   [9:0] select_ln52_103_fu_3789_p3;
wire   [0:0] icmp_ln51_51_fu_3673_p2;
wire   [9:0] select_ln52_104_fu_3803_p3;
wire   [24:0] trunc_ln44_50_fu_643_p4;
wire   [0:0] tmp_344_fu_3843_p3;
wire   [9:0] trunc_ln52_50_fu_3833_p4;
wire   [9:0] zext_ln52_52_fu_3859_p1;
wire   [9:0] add_ln52_52_fu_3863_p2;
wire   [7:0] tmp_79_fu_3877_p4;
wire   [0:0] tmp_345_fu_3851_p3;
wire   [0:0] tmp_346_fu_3869_p3;
wire   [0:0] xor_ln52_158_fu_3893_p2;
wire   [0:0] icmp_ln52_52_fu_3887_p2;
wire   [0:0] or_ln52_169_fu_3899_p2;
wire   [0:0] and_ln52_105_fu_3905_p2;
wire   [0:0] xor_ln52_159_fu_3911_p2;
wire   [0:0] tmp_342_fu_3825_p3;
wire   [0:0] or_ln52_136_fu_3917_p2;
wire   [0:0] xor_ln52_160_fu_3923_p2;
wire   [0:0] and_ln52_106_fu_3929_p2;
wire   [0:0] or_ln52_170_fu_3943_p2;
wire   [9:0] select_ln52_105_fu_3935_p3;
wire   [0:0] icmp_ln51_52_fu_3819_p2;
wire   [9:0] select_ln52_106_fu_3949_p3;
wire   [24:0] trunc_ln44_51_fu_653_p4;
wire   [0:0] tmp_349_fu_3989_p3;
wire   [9:0] trunc_ln52_51_fu_3979_p4;
wire   [9:0] zext_ln52_53_fu_4005_p1;
wire   [9:0] add_ln52_53_fu_4009_p2;
wire   [7:0] tmp_80_fu_4023_p4;
wire   [0:0] tmp_350_fu_3997_p3;
wire   [0:0] tmp_351_fu_4015_p3;
wire   [0:0] xor_ln52_161_fu_4039_p2;
wire   [0:0] icmp_ln52_53_fu_4033_p2;
wire   [0:0] or_ln52_171_fu_4045_p2;
wire   [0:0] and_ln52_107_fu_4051_p2;
wire   [0:0] xor_ln52_162_fu_4057_p2;
wire   [0:0] tmp_347_fu_3971_p3;
wire   [0:0] or_ln52_138_fu_4063_p2;
wire   [0:0] xor_ln52_163_fu_4069_p2;
wire   [0:0] and_ln52_108_fu_4075_p2;
wire   [0:0] or_ln52_172_fu_4089_p2;
wire   [9:0] select_ln52_107_fu_4081_p3;
wire   [0:0] icmp_ln51_53_fu_3965_p2;
wire   [9:0] select_ln52_108_fu_4095_p3;
wire   [24:0] trunc_ln44_52_fu_663_p4;
wire   [0:0] tmp_354_fu_4135_p3;
wire   [9:0] trunc_ln52_52_fu_4125_p4;
wire   [9:0] zext_ln52_54_fu_4151_p1;
wire   [9:0] add_ln52_54_fu_4155_p2;
wire   [7:0] tmp_81_fu_4169_p4;
wire   [0:0] tmp_355_fu_4143_p3;
wire   [0:0] tmp_356_fu_4161_p3;
wire   [0:0] xor_ln52_164_fu_4185_p2;
wire   [0:0] icmp_ln52_54_fu_4179_p2;
wire   [0:0] or_ln52_173_fu_4191_p2;
wire   [0:0] and_ln52_109_fu_4197_p2;
wire   [0:0] xor_ln52_165_fu_4203_p2;
wire   [0:0] tmp_352_fu_4117_p3;
wire   [0:0] or_ln52_140_fu_4209_p2;
wire   [0:0] xor_ln52_166_fu_4215_p2;
wire   [0:0] and_ln52_110_fu_4221_p2;
wire   [0:0] or_ln52_174_fu_4235_p2;
wire   [9:0] select_ln52_109_fu_4227_p3;
wire   [0:0] icmp_ln51_54_fu_4111_p2;
wire   [9:0] select_ln52_110_fu_4241_p3;
wire   [24:0] trunc_ln44_53_fu_673_p4;
wire   [0:0] tmp_359_fu_4281_p3;
wire   [9:0] trunc_ln52_53_fu_4271_p4;
wire   [9:0] zext_ln52_55_fu_4297_p1;
wire   [9:0] add_ln52_55_fu_4301_p2;
wire   [7:0] tmp_82_fu_4315_p4;
wire   [0:0] tmp_360_fu_4289_p3;
wire   [0:0] tmp_361_fu_4307_p3;
wire   [0:0] xor_ln52_167_fu_4331_p2;
wire   [0:0] icmp_ln52_55_fu_4325_p2;
wire   [0:0] or_ln52_175_fu_4337_p2;
wire   [0:0] and_ln52_111_fu_4343_p2;
wire   [0:0] xor_ln52_168_fu_4349_p2;
wire   [0:0] tmp_357_fu_4263_p3;
wire   [0:0] or_ln52_142_fu_4355_p2;
wire   [0:0] xor_ln52_169_fu_4361_p2;
wire   [0:0] and_ln52_112_fu_4367_p2;
wire   [0:0] or_ln52_176_fu_4381_p2;
wire   [9:0] select_ln52_111_fu_4373_p3;
wire   [0:0] icmp_ln51_55_fu_4257_p2;
wire   [9:0] select_ln52_112_fu_4387_p3;
wire   [24:0] trunc_ln44_54_fu_683_p4;
wire   [0:0] tmp_364_fu_4427_p3;
wire   [9:0] trunc_ln52_54_fu_4417_p4;
wire   [9:0] zext_ln52_56_fu_4443_p1;
wire   [9:0] add_ln52_56_fu_4447_p2;
wire   [7:0] tmp_83_fu_4461_p4;
wire   [0:0] tmp_365_fu_4435_p3;
wire   [0:0] tmp_366_fu_4453_p3;
wire   [0:0] xor_ln52_170_fu_4477_p2;
wire   [0:0] icmp_ln52_56_fu_4471_p2;
wire   [0:0] or_ln52_177_fu_4483_p2;
wire   [0:0] and_ln52_113_fu_4489_p2;
wire   [0:0] xor_ln52_171_fu_4495_p2;
wire   [0:0] tmp_362_fu_4409_p3;
wire   [0:0] or_ln52_144_fu_4501_p2;
wire   [0:0] xor_ln52_172_fu_4507_p2;
wire   [0:0] and_ln52_114_fu_4513_p2;
wire   [0:0] or_ln52_178_fu_4527_p2;
wire   [9:0] select_ln52_113_fu_4519_p3;
wire   [0:0] icmp_ln51_56_fu_4403_p2;
wire   [9:0] select_ln52_114_fu_4533_p3;
wire   [24:0] trunc_ln44_55_fu_693_p4;
wire   [0:0] tmp_369_fu_4573_p3;
wire   [9:0] trunc_ln52_55_fu_4563_p4;
wire   [9:0] zext_ln52_57_fu_4589_p1;
wire   [9:0] add_ln52_57_fu_4593_p2;
wire   [7:0] tmp_84_fu_4607_p4;
wire   [0:0] tmp_370_fu_4581_p3;
wire   [0:0] tmp_371_fu_4599_p3;
wire   [0:0] xor_ln52_173_fu_4623_p2;
wire   [0:0] icmp_ln52_57_fu_4617_p2;
wire   [0:0] or_ln52_179_fu_4629_p2;
wire   [0:0] and_ln52_115_fu_4635_p2;
wire   [0:0] xor_ln52_174_fu_4641_p2;
wire   [0:0] tmp_367_fu_4555_p3;
wire   [0:0] or_ln52_146_fu_4647_p2;
wire   [0:0] xor_ln52_175_fu_4653_p2;
wire   [0:0] and_ln52_116_fu_4659_p2;
wire   [0:0] or_ln52_180_fu_4673_p2;
wire   [9:0] select_ln52_115_fu_4665_p3;
wire   [0:0] icmp_ln51_57_fu_4549_p2;
wire   [9:0] select_ln52_116_fu_4679_p3;
wire   [24:0] trunc_ln44_56_fu_703_p4;
wire   [0:0] tmp_374_fu_4719_p3;
wire   [9:0] trunc_ln52_56_fu_4709_p4;
wire   [9:0] zext_ln52_58_fu_4735_p1;
wire   [9:0] add_ln52_58_fu_4739_p2;
wire   [7:0] tmp_85_fu_4753_p4;
wire   [0:0] tmp_375_fu_4727_p3;
wire   [0:0] tmp_376_fu_4745_p3;
wire   [0:0] xor_ln52_176_fu_4769_p2;
wire   [0:0] icmp_ln52_58_fu_4763_p2;
wire   [0:0] or_ln52_181_fu_4775_p2;
wire   [0:0] and_ln52_117_fu_4781_p2;
wire   [0:0] xor_ln52_177_fu_4787_p2;
wire   [0:0] tmp_372_fu_4701_p3;
wire   [0:0] or_ln52_148_fu_4793_p2;
wire   [0:0] xor_ln52_178_fu_4799_p2;
wire   [0:0] and_ln52_118_fu_4805_p2;
wire   [0:0] or_ln52_182_fu_4819_p2;
wire   [9:0] select_ln52_117_fu_4811_p3;
wire   [0:0] icmp_ln51_58_fu_4695_p2;
wire   [9:0] select_ln52_118_fu_4825_p3;
wire   [24:0] trunc_ln44_57_fu_713_p4;
wire   [0:0] tmp_379_fu_4865_p3;
wire   [9:0] trunc_ln52_57_fu_4855_p4;
wire   [9:0] zext_ln52_59_fu_4881_p1;
wire   [9:0] add_ln52_59_fu_4885_p2;
wire   [7:0] tmp_86_fu_4899_p4;
wire   [0:0] tmp_380_fu_4873_p3;
wire   [0:0] tmp_381_fu_4891_p3;
wire   [0:0] xor_ln52_179_fu_4915_p2;
wire   [0:0] icmp_ln52_59_fu_4909_p2;
wire   [0:0] or_ln52_183_fu_4921_p2;
wire   [0:0] and_ln52_119_fu_4927_p2;
wire   [0:0] xor_ln52_180_fu_4933_p2;
wire   [0:0] tmp_377_fu_4847_p3;
wire   [0:0] or_ln52_150_fu_4939_p2;
wire   [0:0] xor_ln52_181_fu_4945_p2;
wire   [0:0] and_ln52_120_fu_4951_p2;
wire   [0:0] or_ln52_184_fu_4965_p2;
wire   [9:0] select_ln52_119_fu_4957_p3;
wire   [0:0] icmp_ln51_59_fu_4841_p2;
wire   [9:0] select_ln52_120_fu_4971_p3;
wire   [24:0] trunc_ln44_58_fu_723_p4;
wire   [0:0] tmp_383_fu_5011_p3;
wire   [9:0] trunc_ln52_58_fu_5001_p4;
wire   [9:0] zext_ln52_60_fu_5027_p1;
wire   [9:0] add_ln52_60_fu_5031_p2;
wire   [7:0] tmp_87_fu_5045_p4;
wire   [0:0] tmp_384_fu_5019_p3;
wire   [0:0] tmp_385_fu_5037_p3;
wire   [0:0] xor_ln52_182_fu_5061_p2;
wire   [0:0] icmp_ln52_60_fu_5055_p2;
wire   [0:0] or_ln52_185_fu_5067_p2;
wire   [0:0] and_ln52_121_fu_5073_p2;
wire   [0:0] xor_ln52_183_fu_5079_p2;
wire   [0:0] tmp_382_fu_4993_p3;
wire   [0:0] or_ln52_152_fu_5085_p2;
wire   [0:0] xor_ln52_184_fu_5091_p2;
wire   [0:0] and_ln52_122_fu_5097_p2;
wire   [0:0] or_ln52_186_fu_5111_p2;
wire   [9:0] select_ln52_121_fu_5103_p3;
wire   [0:0] icmp_ln51_60_fu_4987_p2;
wire   [9:0] select_ln52_122_fu_5117_p3;
wire   [24:0] trunc_ln44_59_fu_733_p4;
wire   [0:0] tmp_387_fu_5157_p3;
wire   [9:0] trunc_ln52_59_fu_5147_p4;
wire   [9:0] zext_ln52_61_fu_5173_p1;
wire   [9:0] add_ln52_61_fu_5177_p2;
wire   [7:0] tmp_88_fu_5191_p4;
wire   [0:0] tmp_388_fu_5165_p3;
wire   [0:0] tmp_389_fu_5183_p3;
wire   [0:0] xor_ln52_185_fu_5207_p2;
wire   [0:0] icmp_ln52_61_fu_5201_p2;
wire   [0:0] or_ln52_187_fu_5213_p2;
wire   [0:0] and_ln52_123_fu_5219_p2;
wire   [0:0] xor_ln52_186_fu_5225_p2;
wire   [0:0] tmp_386_fu_5139_p3;
wire   [0:0] or_ln52_154_fu_5231_p2;
wire   [0:0] xor_ln52_187_fu_5237_p2;
wire   [0:0] and_ln52_124_fu_5243_p2;
wire   [0:0] or_ln52_188_fu_5257_p2;
wire   [9:0] select_ln52_123_fu_5249_p3;
wire   [0:0] icmp_ln51_61_fu_5133_p2;
wire   [9:0] select_ln52_124_fu_5263_p3;
wire   [24:0] trunc_ln44_60_fu_743_p4;
wire   [0:0] tmp_391_fu_5303_p3;
wire   [9:0] trunc_ln52_60_fu_5293_p4;
wire   [9:0] zext_ln52_62_fu_5319_p1;
wire   [9:0] add_ln52_62_fu_5323_p2;
wire   [7:0] tmp_89_fu_5337_p4;
wire   [0:0] tmp_392_fu_5311_p3;
wire   [0:0] tmp_393_fu_5329_p3;
wire   [0:0] xor_ln52_188_fu_5353_p2;
wire   [0:0] icmp_ln52_62_fu_5347_p2;
wire   [0:0] or_ln52_189_fu_5359_p2;
wire   [0:0] and_ln52_125_fu_5365_p2;
wire   [0:0] xor_ln52_189_fu_5371_p2;
wire   [0:0] tmp_390_fu_5285_p3;
wire   [0:0] or_ln52_156_fu_5377_p2;
wire   [0:0] xor_ln52_190_fu_5383_p2;
wire   [0:0] and_ln52_126_fu_5389_p2;
wire   [0:0] or_ln52_190_fu_5403_p2;
wire   [9:0] select_ln52_125_fu_5395_p3;
wire   [0:0] icmp_ln51_62_fu_5279_p2;
wire   [9:0] select_ln52_126_fu_5409_p3;
wire   [9:0] out_data_0_31_0_0_0_load_fu_5417_p3;
wire   [9:0] out_data_0_30_0_0_0_load_fu_5271_p3;
wire   [9:0] out_data_0_29_0_0_0_load_fu_5125_p3;
wire   [9:0] out_data_0_28_0_0_0_load_fu_4979_p3;
wire   [9:0] out_data_0_27_0_0_0_load_fu_4833_p3;
wire   [9:0] out_data_0_26_0_0_0_load_fu_4687_p3;
wire   [9:0] out_data_0_25_0_0_0_load_fu_4541_p3;
wire   [9:0] out_data_0_24_0_0_0_load_fu_4395_p3;
wire   [9:0] out_data_0_23_0_0_0_load_fu_4249_p3;
wire   [9:0] out_data_0_22_0_0_0_load_fu_4103_p3;
wire   [9:0] out_data_0_21_0_0_0_load_fu_3957_p3;
wire   [9:0] out_data_0_20_0_0_0_load_fu_3811_p3;
wire   [9:0] out_data_0_19_0_0_0_load_fu_3665_p3;
wire   [9:0] out_data_0_18_0_0_0_load_fu_3519_p3;
wire   [9:0] out_data_0_17_0_0_0_load_fu_3373_p3;
wire   [9:0] out_data_0_16_0_0_0_load_fu_3227_p3;
wire   [9:0] out_data_0_15_0_0_0_load_fu_3081_p3;
wire   [9:0] out_data_0_14_0_0_0_load_fu_2935_p3;
wire   [9:0] out_data_0_13_0_0_0_load_fu_2789_p3;
wire   [9:0] out_data_0_12_0_0_0_load_fu_2643_p3;
wire   [9:0] out_data_0_11_0_0_0_load_fu_2497_p3;
wire   [9:0] out_data_0_10_0_0_0_load_fu_2351_p3;
wire   [9:0] out_data_0_9_0_0_0_load_fu_2205_p3;
wire   [9:0] out_data_0_8_0_0_0_load_fu_2059_p3;
wire   [9:0] out_data_0_7_0_0_0_load_fu_1913_p3;
wire   [9:0] out_data_0_6_0_0_0_load_fu_1767_p3;
wire   [9:0] out_data_0_5_0_0_0_load_fu_1621_p3;
wire   [9:0] out_data_0_4_0_0_0_load_fu_1475_p3;
wire   [9:0] out_data_0_3_0_0_0_load_fu_1329_p3;
wire   [9:0] out_data_0_2_0_0_0_load_fu_1183_p3;
wire   [9:0] out_data_0_1_0_0_0_load_fu_1037_p3;
wire   [9:0] out_data_0_0_0_0_0_load_fu_891_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_blk_n = layer3_out_empty_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer3_out_read = 1'b1;
    end else begin
        layer3_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_write = 1'b1;
    end else begin
        layer4_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_32_fu_943_p2 = (trunc_ln52_s_fu_913_p4 + zext_ln52_32_fu_939_p1);

assign add_ln52_33_fu_1089_p2 = (trunc_ln52_31_fu_1059_p4 + zext_ln52_33_fu_1085_p1);

assign add_ln52_34_fu_1235_p2 = (trunc_ln52_32_fu_1205_p4 + zext_ln52_34_fu_1231_p1);

assign add_ln52_35_fu_1381_p2 = (trunc_ln52_33_fu_1351_p4 + zext_ln52_35_fu_1377_p1);

assign add_ln52_36_fu_1527_p2 = (trunc_ln52_34_fu_1497_p4 + zext_ln52_36_fu_1523_p1);

assign add_ln52_37_fu_1673_p2 = (trunc_ln52_35_fu_1643_p4 + zext_ln52_37_fu_1669_p1);

assign add_ln52_38_fu_1819_p2 = (trunc_ln52_36_fu_1789_p4 + zext_ln52_38_fu_1815_p1);

assign add_ln52_39_fu_1965_p2 = (trunc_ln52_37_fu_1935_p4 + zext_ln52_39_fu_1961_p1);

assign add_ln52_40_fu_2111_p2 = (trunc_ln52_38_fu_2081_p4 + zext_ln52_40_fu_2107_p1);

assign add_ln52_41_fu_2257_p2 = (trunc_ln52_39_fu_2227_p4 + zext_ln52_41_fu_2253_p1);

assign add_ln52_42_fu_2403_p2 = (trunc_ln52_40_fu_2373_p4 + zext_ln52_42_fu_2399_p1);

assign add_ln52_43_fu_2549_p2 = (trunc_ln52_41_fu_2519_p4 + zext_ln52_43_fu_2545_p1);

assign add_ln52_44_fu_2695_p2 = (trunc_ln52_42_fu_2665_p4 + zext_ln52_44_fu_2691_p1);

assign add_ln52_45_fu_2841_p2 = (trunc_ln52_43_fu_2811_p4 + zext_ln52_45_fu_2837_p1);

assign add_ln52_46_fu_2987_p2 = (trunc_ln52_44_fu_2957_p4 + zext_ln52_46_fu_2983_p1);

assign add_ln52_47_fu_3133_p2 = (trunc_ln52_45_fu_3103_p4 + zext_ln52_47_fu_3129_p1);

assign add_ln52_48_fu_3279_p2 = (trunc_ln52_46_fu_3249_p4 + zext_ln52_48_fu_3275_p1);

assign add_ln52_49_fu_3425_p2 = (trunc_ln52_47_fu_3395_p4 + zext_ln52_49_fu_3421_p1);

assign add_ln52_50_fu_3571_p2 = (trunc_ln52_48_fu_3541_p4 + zext_ln52_50_fu_3567_p1);

assign add_ln52_51_fu_3717_p2 = (trunc_ln52_49_fu_3687_p4 + zext_ln52_51_fu_3713_p1);

assign add_ln52_52_fu_3863_p2 = (trunc_ln52_50_fu_3833_p4 + zext_ln52_52_fu_3859_p1);

assign add_ln52_53_fu_4009_p2 = (trunc_ln52_51_fu_3979_p4 + zext_ln52_53_fu_4005_p1);

assign add_ln52_54_fu_4155_p2 = (trunc_ln52_52_fu_4125_p4 + zext_ln52_54_fu_4151_p1);

assign add_ln52_55_fu_4301_p2 = (trunc_ln52_53_fu_4271_p4 + zext_ln52_55_fu_4297_p1);

assign add_ln52_56_fu_4447_p2 = (trunc_ln52_54_fu_4417_p4 + zext_ln52_56_fu_4443_p1);

assign add_ln52_57_fu_4593_p2 = (trunc_ln52_55_fu_4563_p4 + zext_ln52_57_fu_4589_p1);

assign add_ln52_58_fu_4739_p2 = (trunc_ln52_56_fu_4709_p4 + zext_ln52_58_fu_4735_p1);

assign add_ln52_59_fu_4885_p2 = (trunc_ln52_57_fu_4855_p4 + zext_ln52_59_fu_4881_p1);

assign add_ln52_60_fu_5031_p2 = (trunc_ln52_58_fu_5001_p4 + zext_ln52_60_fu_5027_p1);

assign add_ln52_61_fu_5177_p2 = (trunc_ln52_59_fu_5147_p4 + zext_ln52_61_fu_5173_p1);

assign add_ln52_62_fu_5323_p2 = (trunc_ln52_60_fu_5293_p4 + zext_ln52_62_fu_5319_p1);

assign add_ln52_fu_797_p2 = (trunc_ln4_fu_767_p4 + zext_ln52_fu_793_p1);

assign and_ln52_100_fu_3491_p2 = (xor_ln52_151_fu_3485_p2 & or_ln52_130_fu_3479_p2);

assign and_ln52_101_fu_3613_p2 = (or_ln52_165_fu_3607_p2 & icmp_ln52_50_fu_3595_p2);

assign and_ln52_102_fu_3637_p2 = (xor_ln52_154_fu_3631_p2 & or_ln52_132_fu_3625_p2);

assign and_ln52_103_fu_3759_p2 = (or_ln52_167_fu_3753_p2 & icmp_ln52_51_fu_3741_p2);

assign and_ln52_104_fu_3783_p2 = (xor_ln52_157_fu_3777_p2 & or_ln52_134_fu_3771_p2);

assign and_ln52_105_fu_3905_p2 = (or_ln52_169_fu_3899_p2 & icmp_ln52_52_fu_3887_p2);

assign and_ln52_106_fu_3929_p2 = (xor_ln52_160_fu_3923_p2 & or_ln52_136_fu_3917_p2);

assign and_ln52_107_fu_4051_p2 = (or_ln52_171_fu_4045_p2 & icmp_ln52_53_fu_4033_p2);

assign and_ln52_108_fu_4075_p2 = (xor_ln52_163_fu_4069_p2 & or_ln52_138_fu_4063_p2);

assign and_ln52_109_fu_4197_p2 = (or_ln52_173_fu_4191_p2 & icmp_ln52_54_fu_4179_p2);

assign and_ln52_110_fu_4221_p2 = (xor_ln52_166_fu_4215_p2 & or_ln52_140_fu_4209_p2);

assign and_ln52_111_fu_4343_p2 = (or_ln52_175_fu_4337_p2 & icmp_ln52_55_fu_4325_p2);

assign and_ln52_112_fu_4367_p2 = (xor_ln52_169_fu_4361_p2 & or_ln52_142_fu_4355_p2);

assign and_ln52_113_fu_4489_p2 = (or_ln52_177_fu_4483_p2 & icmp_ln52_56_fu_4471_p2);

assign and_ln52_114_fu_4513_p2 = (xor_ln52_172_fu_4507_p2 & or_ln52_144_fu_4501_p2);

assign and_ln52_115_fu_4635_p2 = (or_ln52_179_fu_4629_p2 & icmp_ln52_57_fu_4617_p2);

assign and_ln52_116_fu_4659_p2 = (xor_ln52_175_fu_4653_p2 & or_ln52_146_fu_4647_p2);

assign and_ln52_117_fu_4781_p2 = (or_ln52_181_fu_4775_p2 & icmp_ln52_58_fu_4763_p2);

assign and_ln52_118_fu_4805_p2 = (xor_ln52_178_fu_4799_p2 & or_ln52_148_fu_4793_p2);

assign and_ln52_119_fu_4927_p2 = (or_ln52_183_fu_4921_p2 & icmp_ln52_59_fu_4909_p2);

assign and_ln52_120_fu_4951_p2 = (xor_ln52_181_fu_4945_p2 & or_ln52_150_fu_4939_p2);

assign and_ln52_121_fu_5073_p2 = (or_ln52_185_fu_5067_p2 & icmp_ln52_60_fu_5055_p2);

assign and_ln52_122_fu_5097_p2 = (xor_ln52_184_fu_5091_p2 & or_ln52_152_fu_5085_p2);

assign and_ln52_123_fu_5219_p2 = (or_ln52_187_fu_5213_p2 & icmp_ln52_61_fu_5201_p2);

assign and_ln52_124_fu_5243_p2 = (xor_ln52_187_fu_5237_p2 & or_ln52_154_fu_5231_p2);

assign and_ln52_125_fu_5365_p2 = (or_ln52_189_fu_5359_p2 & icmp_ln52_62_fu_5347_p2);

assign and_ln52_126_fu_5389_p2 = (xor_ln52_190_fu_5383_p2 & or_ln52_156_fu_5377_p2);

assign and_ln52_64_fu_863_p2 = (xor_ln52_97_fu_857_p2 & or_ln52_fu_851_p2);

assign and_ln52_65_fu_985_p2 = (or_ln52_101_fu_979_p2 & icmp_ln52_32_fu_967_p2);

assign and_ln52_66_fu_1009_p2 = (xor_ln52_100_fu_1003_p2 & or_ln52_96_fu_997_p2);

assign and_ln52_67_fu_1131_p2 = (or_ln52_105_fu_1125_p2 & icmp_ln52_33_fu_1113_p2);

assign and_ln52_68_fu_1155_p2 = (xor_ln52_103_fu_1149_p2 & or_ln52_98_fu_1143_p2);

assign and_ln52_69_fu_1277_p2 = (or_ln52_109_fu_1271_p2 & icmp_ln52_34_fu_1259_p2);

assign and_ln52_70_fu_1301_p2 = (xor_ln52_106_fu_1295_p2 & or_ln52_100_fu_1289_p2);

assign and_ln52_71_fu_1423_p2 = (or_ln52_113_fu_1417_p2 & icmp_ln52_35_fu_1405_p2);

assign and_ln52_72_fu_1447_p2 = (xor_ln52_109_fu_1441_p2 & or_ln52_102_fu_1435_p2);

assign and_ln52_73_fu_1569_p2 = (or_ln52_117_fu_1563_p2 & icmp_ln52_36_fu_1551_p2);

assign and_ln52_74_fu_1593_p2 = (xor_ln52_112_fu_1587_p2 & or_ln52_104_fu_1581_p2);

assign and_ln52_75_fu_1715_p2 = (or_ln52_121_fu_1709_p2 & icmp_ln52_37_fu_1697_p2);

assign and_ln52_76_fu_1739_p2 = (xor_ln52_115_fu_1733_p2 & or_ln52_106_fu_1727_p2);

assign and_ln52_77_fu_1861_p2 = (or_ln52_125_fu_1855_p2 & icmp_ln52_38_fu_1843_p2);

assign and_ln52_78_fu_1885_p2 = (xor_ln52_118_fu_1879_p2 & or_ln52_108_fu_1873_p2);

assign and_ln52_79_fu_2007_p2 = (or_ln52_129_fu_2001_p2 & icmp_ln52_39_fu_1989_p2);

assign and_ln52_80_fu_2031_p2 = (xor_ln52_121_fu_2025_p2 & or_ln52_110_fu_2019_p2);

assign and_ln52_81_fu_2153_p2 = (or_ln52_133_fu_2147_p2 & icmp_ln52_40_fu_2135_p2);

assign and_ln52_82_fu_2177_p2 = (xor_ln52_124_fu_2171_p2 & or_ln52_112_fu_2165_p2);

assign and_ln52_83_fu_2299_p2 = (or_ln52_137_fu_2293_p2 & icmp_ln52_41_fu_2281_p2);

assign and_ln52_84_fu_2323_p2 = (xor_ln52_127_fu_2317_p2 & or_ln52_114_fu_2311_p2);

assign and_ln52_85_fu_2445_p2 = (or_ln52_141_fu_2439_p2 & icmp_ln52_42_fu_2427_p2);

assign and_ln52_86_fu_2469_p2 = (xor_ln52_130_fu_2463_p2 & or_ln52_116_fu_2457_p2);

assign and_ln52_87_fu_2591_p2 = (or_ln52_145_fu_2585_p2 & icmp_ln52_43_fu_2573_p2);

assign and_ln52_88_fu_2615_p2 = (xor_ln52_133_fu_2609_p2 & or_ln52_118_fu_2603_p2);

assign and_ln52_89_fu_2737_p2 = (or_ln52_149_fu_2731_p2 & icmp_ln52_44_fu_2719_p2);

assign and_ln52_90_fu_2761_p2 = (xor_ln52_136_fu_2755_p2 & or_ln52_120_fu_2749_p2);

assign and_ln52_91_fu_2883_p2 = (or_ln52_153_fu_2877_p2 & icmp_ln52_45_fu_2865_p2);

assign and_ln52_92_fu_2907_p2 = (xor_ln52_139_fu_2901_p2 & or_ln52_122_fu_2895_p2);

assign and_ln52_93_fu_3029_p2 = (or_ln52_157_fu_3023_p2 & icmp_ln52_46_fu_3011_p2);

assign and_ln52_94_fu_3053_p2 = (xor_ln52_142_fu_3047_p2 & or_ln52_124_fu_3041_p2);

assign and_ln52_95_fu_3175_p2 = (or_ln52_159_fu_3169_p2 & icmp_ln52_47_fu_3157_p2);

assign and_ln52_96_fu_3199_p2 = (xor_ln52_145_fu_3193_p2 & or_ln52_126_fu_3187_p2);

assign and_ln52_97_fu_3321_p2 = (or_ln52_161_fu_3315_p2 & icmp_ln52_48_fu_3303_p2);

assign and_ln52_98_fu_3345_p2 = (xor_ln52_148_fu_3339_p2 & or_ln52_128_fu_3333_p2);

assign and_ln52_99_fu_3467_p2 = (or_ln52_163_fu_3461_p2 & icmp_ln52_49_fu_3449_p2);

assign and_ln52_fu_839_p2 = (or_ln52_97_fu_833_p2 & icmp_ln52_fu_821_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer4_out_full_n == 1'b0) | (layer3_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_32_fu_899_p2 = (($signed(trunc_ln44_s_fu_443_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_33_fu_1045_p2 = (($signed(trunc_ln44_31_fu_453_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_34_fu_1191_p2 = (($signed(trunc_ln44_32_fu_463_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_35_fu_1337_p2 = (($signed(trunc_ln44_33_fu_473_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_36_fu_1483_p2 = (($signed(trunc_ln44_34_fu_483_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_37_fu_1629_p2 = (($signed(trunc_ln44_35_fu_493_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_38_fu_1775_p2 = (($signed(trunc_ln44_36_fu_503_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_39_fu_1921_p2 = (($signed(trunc_ln44_37_fu_513_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_40_fu_2067_p2 = (($signed(trunc_ln44_38_fu_523_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_41_fu_2213_p2 = (($signed(trunc_ln44_39_fu_533_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_42_fu_2359_p2 = (($signed(trunc_ln44_40_fu_543_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_43_fu_2505_p2 = (($signed(trunc_ln44_41_fu_553_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_44_fu_2651_p2 = (($signed(trunc_ln44_42_fu_563_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_45_fu_2797_p2 = (($signed(trunc_ln44_43_fu_573_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_46_fu_2943_p2 = (($signed(trunc_ln44_44_fu_583_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_47_fu_3089_p2 = (($signed(trunc_ln44_45_fu_593_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_48_fu_3235_p2 = (($signed(trunc_ln44_46_fu_603_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_49_fu_3381_p2 = (($signed(trunc_ln44_47_fu_613_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_50_fu_3527_p2 = (($signed(trunc_ln44_48_fu_623_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_51_fu_3673_p2 = (($signed(trunc_ln44_49_fu_633_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_52_fu_3819_p2 = (($signed(trunc_ln44_50_fu_643_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_53_fu_3965_p2 = (($signed(trunc_ln44_51_fu_653_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_54_fu_4111_p2 = (($signed(trunc_ln44_52_fu_663_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_55_fu_4257_p2 = (($signed(trunc_ln44_53_fu_673_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_56_fu_4403_p2 = (($signed(trunc_ln44_54_fu_683_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_57_fu_4549_p2 = (($signed(trunc_ln44_55_fu_693_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_58_fu_4695_p2 = (($signed(trunc_ln44_56_fu_703_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_59_fu_4841_p2 = (($signed(trunc_ln44_57_fu_713_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_60_fu_4987_p2 = (($signed(trunc_ln44_58_fu_723_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_61_fu_5133_p2 = (($signed(trunc_ln44_59_fu_733_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_62_fu_5279_p2 = (($signed(trunc_ln44_60_fu_743_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_753_p2 = (($signed(trunc_ln44_fu_439_p1) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln52_32_fu_967_p2 = ((tmp_59_fu_957_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_33_fu_1113_p2 = ((tmp_60_fu_1103_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_34_fu_1259_p2 = ((tmp_61_fu_1249_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_35_fu_1405_p2 = ((tmp_62_fu_1395_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_36_fu_1551_p2 = ((tmp_63_fu_1541_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_37_fu_1697_p2 = ((tmp_64_fu_1687_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_38_fu_1843_p2 = ((tmp_65_fu_1833_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_39_fu_1989_p2 = ((tmp_66_fu_1979_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_40_fu_2135_p2 = ((tmp_67_fu_2125_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_41_fu_2281_p2 = ((tmp_68_fu_2271_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_42_fu_2427_p2 = ((tmp_69_fu_2417_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_43_fu_2573_p2 = ((tmp_70_fu_2563_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_44_fu_2719_p2 = ((tmp_71_fu_2709_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_45_fu_2865_p2 = ((tmp_72_fu_2855_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_46_fu_3011_p2 = ((tmp_73_fu_3001_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_47_fu_3157_p2 = ((tmp_74_fu_3147_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_48_fu_3303_p2 = ((tmp_75_fu_3293_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_49_fu_3449_p2 = ((tmp_76_fu_3439_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_50_fu_3595_p2 = ((tmp_77_fu_3585_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_51_fu_3741_p2 = ((tmp_78_fu_3731_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_52_fu_3887_p2 = ((tmp_79_fu_3877_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_53_fu_4033_p2 = ((tmp_80_fu_4023_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_54_fu_4179_p2 = ((tmp_81_fu_4169_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_55_fu_4325_p2 = ((tmp_82_fu_4315_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_56_fu_4471_p2 = ((tmp_83_fu_4461_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_57_fu_4617_p2 = ((tmp_84_fu_4607_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_58_fu_4763_p2 = ((tmp_85_fu_4753_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_59_fu_4909_p2 = ((tmp_86_fu_4899_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_60_fu_5055_p2 = ((tmp_87_fu_5045_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_61_fu_5201_p2 = ((tmp_88_fu_5191_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_62_fu_5347_p2 = ((tmp_89_fu_5337_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_821_p2 = ((tmp_s_fu_811_p4 == 8'd0) ? 1'b1 : 1'b0);

assign layer4_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{out_data_0_31_0_0_0_load_fu_5417_p3}, {out_data_0_30_0_0_0_load_fu_5271_p3}}, {out_data_0_29_0_0_0_load_fu_5125_p3}}, {out_data_0_28_0_0_0_load_fu_4979_p3}}, {out_data_0_27_0_0_0_load_fu_4833_p3}}, {out_data_0_26_0_0_0_load_fu_4687_p3}}, {out_data_0_25_0_0_0_load_fu_4541_p3}}, {out_data_0_24_0_0_0_load_fu_4395_p3}}, {out_data_0_23_0_0_0_load_fu_4249_p3}}, {out_data_0_22_0_0_0_load_fu_4103_p3}}, {out_data_0_21_0_0_0_load_fu_3957_p3}}, {out_data_0_20_0_0_0_load_fu_3811_p3}}, {out_data_0_19_0_0_0_load_fu_3665_p3}}, {out_data_0_18_0_0_0_load_fu_3519_p3}}, {out_data_0_17_0_0_0_load_fu_3373_p3}}, {out_data_0_16_0_0_0_load_fu_3227_p3}}, {out_data_0_15_0_0_0_load_fu_3081_p3}}, {out_data_0_14_0_0_0_load_fu_2935_p3}}, {out_data_0_13_0_0_0_load_fu_2789_p3}}, {out_data_0_12_0_0_0_load_fu_2643_p3}}, {out_data_0_11_0_0_0_load_fu_2497_p3}}, {out_data_0_10_0_0_0_load_fu_2351_p3}}, {out_data_0_9_0_0_0_load_fu_2205_p3}}, {out_data_0_8_0_0_0_load_fu_2059_p3}}, {out_data_0_7_0_0_0_load_fu_1913_p3}}, 
    {out_data_0_6_0_0_0_load_fu_1767_p3}}, {out_data_0_5_0_0_0_load_fu_1621_p3}}, {out_data_0_4_0_0_0_load_fu_1475_p3}}, {out_data_0_3_0_0_0_load_fu_1329_p3}}, {out_data_0_2_0_0_0_load_fu_1183_p3}}, {out_data_0_1_0_0_0_load_fu_1037_p3}}, {out_data_0_0_0_0_0_load_fu_891_p3}};

assign or_ln52_100_fu_1289_p2 = (xor_ln52_105_fu_1283_p2 | tmp_256_fu_1241_p3);

assign or_ln52_101_fu_979_p2 = (xor_ln52_98_fu_973_p2 | tmp_246_fu_949_p3);

assign or_ln52_102_fu_1435_p2 = (xor_ln52_108_fu_1429_p2 | tmp_261_fu_1387_p3);

assign or_ln52_103_fu_1023_p2 = (tmp_242_fu_905_p3 | and_ln52_66_fu_1009_p2);

assign or_ln52_104_fu_1581_p2 = (xor_ln52_111_fu_1575_p2 | tmp_266_fu_1533_p3);

assign or_ln52_105_fu_1125_p2 = (xor_ln52_101_fu_1119_p2 | tmp_251_fu_1095_p3);

assign or_ln52_106_fu_1727_p2 = (xor_ln52_114_fu_1721_p2 | tmp_271_fu_1679_p3);

assign or_ln52_107_fu_1169_p2 = (tmp_247_fu_1051_p3 | and_ln52_68_fu_1155_p2);

assign or_ln52_108_fu_1873_p2 = (xor_ln52_117_fu_1867_p2 | tmp_276_fu_1825_p3);

assign or_ln52_109_fu_1271_p2 = (xor_ln52_104_fu_1265_p2 | tmp_256_fu_1241_p3);

assign or_ln52_110_fu_2019_p2 = (xor_ln52_120_fu_2013_p2 | tmp_281_fu_1971_p3);

assign or_ln52_111_fu_1315_p2 = (tmp_252_fu_1197_p3 | and_ln52_70_fu_1301_p2);

assign or_ln52_112_fu_2165_p2 = (xor_ln52_123_fu_2159_p2 | tmp_286_fu_2117_p3);

assign or_ln52_113_fu_1417_p2 = (xor_ln52_107_fu_1411_p2 | tmp_261_fu_1387_p3);

assign or_ln52_114_fu_2311_p2 = (xor_ln52_126_fu_2305_p2 | tmp_291_fu_2263_p3);

assign or_ln52_115_fu_1461_p2 = (tmp_257_fu_1343_p3 | and_ln52_72_fu_1447_p2);

assign or_ln52_116_fu_2457_p2 = (xor_ln52_129_fu_2451_p2 | tmp_296_fu_2409_p3);

assign or_ln52_117_fu_1563_p2 = (xor_ln52_110_fu_1557_p2 | tmp_266_fu_1533_p3);

assign or_ln52_118_fu_2603_p2 = (xor_ln52_132_fu_2597_p2 | tmp_301_fu_2555_p3);

assign or_ln52_119_fu_1607_p2 = (tmp_262_fu_1489_p3 | and_ln52_74_fu_1593_p2);

assign or_ln52_120_fu_2749_p2 = (xor_ln52_135_fu_2743_p2 | tmp_306_fu_2701_p3);

assign or_ln52_121_fu_1709_p2 = (xor_ln52_113_fu_1703_p2 | tmp_271_fu_1679_p3);

assign or_ln52_122_fu_2895_p2 = (xor_ln52_138_fu_2889_p2 | tmp_311_fu_2847_p3);

assign or_ln52_123_fu_1753_p2 = (tmp_267_fu_1635_p3 | and_ln52_76_fu_1739_p2);

assign or_ln52_124_fu_3041_p2 = (xor_ln52_141_fu_3035_p2 | tmp_316_fu_2993_p3);

assign or_ln52_125_fu_1855_p2 = (xor_ln52_116_fu_1849_p2 | tmp_276_fu_1825_p3);

assign or_ln52_126_fu_3187_p2 = (xor_ln52_144_fu_3181_p2 | tmp_321_fu_3139_p3);

assign or_ln52_127_fu_1899_p2 = (tmp_272_fu_1781_p3 | and_ln52_78_fu_1885_p2);

assign or_ln52_128_fu_3333_p2 = (xor_ln52_147_fu_3327_p2 | tmp_326_fu_3285_p3);

assign or_ln52_129_fu_2001_p2 = (xor_ln52_119_fu_1995_p2 | tmp_281_fu_1971_p3);

assign or_ln52_130_fu_3479_p2 = (xor_ln52_150_fu_3473_p2 | tmp_331_fu_3431_p3);

assign or_ln52_131_fu_2045_p2 = (tmp_277_fu_1927_p3 | and_ln52_80_fu_2031_p2);

assign or_ln52_132_fu_3625_p2 = (xor_ln52_153_fu_3619_p2 | tmp_336_fu_3577_p3);

assign or_ln52_133_fu_2147_p2 = (xor_ln52_122_fu_2141_p2 | tmp_286_fu_2117_p3);

assign or_ln52_134_fu_3771_p2 = (xor_ln52_156_fu_3765_p2 | tmp_341_fu_3723_p3);

assign or_ln52_135_fu_2191_p2 = (tmp_282_fu_2073_p3 | and_ln52_82_fu_2177_p2);

assign or_ln52_136_fu_3917_p2 = (xor_ln52_159_fu_3911_p2 | tmp_346_fu_3869_p3);

assign or_ln52_137_fu_2293_p2 = (xor_ln52_125_fu_2287_p2 | tmp_291_fu_2263_p3);

assign or_ln52_138_fu_4063_p2 = (xor_ln52_162_fu_4057_p2 | tmp_351_fu_4015_p3);

assign or_ln52_139_fu_2337_p2 = (tmp_287_fu_2219_p3 | and_ln52_84_fu_2323_p2);

assign or_ln52_140_fu_4209_p2 = (xor_ln52_165_fu_4203_p2 | tmp_356_fu_4161_p3);

assign or_ln52_141_fu_2439_p2 = (xor_ln52_128_fu_2433_p2 | tmp_296_fu_2409_p3);

assign or_ln52_142_fu_4355_p2 = (xor_ln52_168_fu_4349_p2 | tmp_361_fu_4307_p3);

assign or_ln52_143_fu_2483_p2 = (tmp_292_fu_2365_p3 | and_ln52_86_fu_2469_p2);

assign or_ln52_144_fu_4501_p2 = (xor_ln52_171_fu_4495_p2 | tmp_366_fu_4453_p3);

assign or_ln52_145_fu_2585_p2 = (xor_ln52_131_fu_2579_p2 | tmp_301_fu_2555_p3);

assign or_ln52_146_fu_4647_p2 = (xor_ln52_174_fu_4641_p2 | tmp_371_fu_4599_p3);

assign or_ln52_147_fu_2629_p2 = (tmp_297_fu_2511_p3 | and_ln52_88_fu_2615_p2);

assign or_ln52_148_fu_4793_p2 = (xor_ln52_177_fu_4787_p2 | tmp_376_fu_4745_p3);

assign or_ln52_149_fu_2731_p2 = (xor_ln52_134_fu_2725_p2 | tmp_306_fu_2701_p3);

assign or_ln52_150_fu_4939_p2 = (xor_ln52_180_fu_4933_p2 | tmp_381_fu_4891_p3);

assign or_ln52_151_fu_2775_p2 = (tmp_302_fu_2657_p3 | and_ln52_90_fu_2761_p2);

assign or_ln52_152_fu_5085_p2 = (xor_ln52_183_fu_5079_p2 | tmp_385_fu_5037_p3);

assign or_ln52_153_fu_2877_p2 = (xor_ln52_137_fu_2871_p2 | tmp_311_fu_2847_p3);

assign or_ln52_154_fu_5231_p2 = (xor_ln52_186_fu_5225_p2 | tmp_389_fu_5183_p3);

assign or_ln52_155_fu_2921_p2 = (tmp_307_fu_2803_p3 | and_ln52_92_fu_2907_p2);

assign or_ln52_156_fu_5377_p2 = (xor_ln52_189_fu_5371_p2 | tmp_393_fu_5329_p3);

assign or_ln52_157_fu_3023_p2 = (xor_ln52_140_fu_3017_p2 | tmp_316_fu_2993_p3);

assign or_ln52_158_fu_3067_p2 = (tmp_312_fu_2949_p3 | and_ln52_94_fu_3053_p2);

assign or_ln52_159_fu_3169_p2 = (xor_ln52_143_fu_3163_p2 | tmp_321_fu_3139_p3);

assign or_ln52_160_fu_3213_p2 = (tmp_317_fu_3095_p3 | and_ln52_96_fu_3199_p2);

assign or_ln52_161_fu_3315_p2 = (xor_ln52_146_fu_3309_p2 | tmp_326_fu_3285_p3);

assign or_ln52_162_fu_3359_p2 = (tmp_322_fu_3241_p3 | and_ln52_98_fu_3345_p2);

assign or_ln52_163_fu_3461_p2 = (xor_ln52_149_fu_3455_p2 | tmp_331_fu_3431_p3);

assign or_ln52_164_fu_3505_p2 = (tmp_327_fu_3387_p3 | and_ln52_100_fu_3491_p2);

assign or_ln52_165_fu_3607_p2 = (xor_ln52_152_fu_3601_p2 | tmp_336_fu_3577_p3);

assign or_ln52_166_fu_3651_p2 = (tmp_332_fu_3533_p3 | and_ln52_102_fu_3637_p2);

assign or_ln52_167_fu_3753_p2 = (xor_ln52_155_fu_3747_p2 | tmp_341_fu_3723_p3);

assign or_ln52_168_fu_3797_p2 = (tmp_337_fu_3679_p3 | and_ln52_104_fu_3783_p2);

assign or_ln52_169_fu_3899_p2 = (xor_ln52_158_fu_3893_p2 | tmp_346_fu_3869_p3);

assign or_ln52_170_fu_3943_p2 = (tmp_342_fu_3825_p3 | and_ln52_106_fu_3929_p2);

assign or_ln52_171_fu_4045_p2 = (xor_ln52_161_fu_4039_p2 | tmp_351_fu_4015_p3);

assign or_ln52_172_fu_4089_p2 = (tmp_347_fu_3971_p3 | and_ln52_108_fu_4075_p2);

assign or_ln52_173_fu_4191_p2 = (xor_ln52_164_fu_4185_p2 | tmp_356_fu_4161_p3);

assign or_ln52_174_fu_4235_p2 = (tmp_352_fu_4117_p3 | and_ln52_110_fu_4221_p2);

assign or_ln52_175_fu_4337_p2 = (xor_ln52_167_fu_4331_p2 | tmp_361_fu_4307_p3);

assign or_ln52_176_fu_4381_p2 = (tmp_357_fu_4263_p3 | and_ln52_112_fu_4367_p2);

assign or_ln52_177_fu_4483_p2 = (xor_ln52_170_fu_4477_p2 | tmp_366_fu_4453_p3);

assign or_ln52_178_fu_4527_p2 = (tmp_362_fu_4409_p3 | and_ln52_114_fu_4513_p2);

assign or_ln52_179_fu_4629_p2 = (xor_ln52_173_fu_4623_p2 | tmp_371_fu_4599_p3);

assign or_ln52_180_fu_4673_p2 = (tmp_367_fu_4555_p3 | and_ln52_116_fu_4659_p2);

assign or_ln52_181_fu_4775_p2 = (xor_ln52_176_fu_4769_p2 | tmp_376_fu_4745_p3);

assign or_ln52_182_fu_4819_p2 = (tmp_372_fu_4701_p3 | and_ln52_118_fu_4805_p2);

assign or_ln52_183_fu_4921_p2 = (xor_ln52_179_fu_4915_p2 | tmp_381_fu_4891_p3);

assign or_ln52_184_fu_4965_p2 = (tmp_377_fu_4847_p3 | and_ln52_120_fu_4951_p2);

assign or_ln52_185_fu_5067_p2 = (xor_ln52_182_fu_5061_p2 | tmp_385_fu_5037_p3);

assign or_ln52_186_fu_5111_p2 = (tmp_382_fu_4993_p3 | and_ln52_122_fu_5097_p2);

assign or_ln52_187_fu_5213_p2 = (xor_ln52_185_fu_5207_p2 | tmp_389_fu_5183_p3);

assign or_ln52_188_fu_5257_p2 = (tmp_386_fu_5139_p3 | and_ln52_124_fu_5243_p2);

assign or_ln52_189_fu_5359_p2 = (xor_ln52_188_fu_5353_p2 | tmp_393_fu_5329_p3);

assign or_ln52_190_fu_5403_p2 = (tmp_390_fu_5285_p3 | and_ln52_126_fu_5389_p2);

assign or_ln52_96_fu_997_p2 = (xor_ln52_99_fu_991_p2 | tmp_246_fu_949_p3);

assign or_ln52_97_fu_833_p2 = (xor_ln52_fu_827_p2 | tmp_241_fu_803_p3);

assign or_ln52_98_fu_1143_p2 = (xor_ln52_102_fu_1137_p2 | tmp_251_fu_1095_p3);

assign or_ln52_99_fu_877_p2 = (tmp_fu_759_p3 | and_ln52_64_fu_863_p2);

assign or_ln52_fu_851_p2 = (xor_ln52_96_fu_845_p2 | tmp_241_fu_803_p3);

assign out_data_0_0_0_0_0_load_fu_891_p3 = ((icmp_ln51_fu_753_p2[0:0] == 1'b1) ? select_ln52_64_fu_883_p3 : 10'd0);

assign out_data_0_10_0_0_0_load_fu_2351_p3 = ((icmp_ln51_41_fu_2213_p2[0:0] == 1'b1) ? select_ln52_84_fu_2343_p3 : 10'd0);

assign out_data_0_11_0_0_0_load_fu_2497_p3 = ((icmp_ln51_42_fu_2359_p2[0:0] == 1'b1) ? select_ln52_86_fu_2489_p3 : 10'd0);

assign out_data_0_12_0_0_0_load_fu_2643_p3 = ((icmp_ln51_43_fu_2505_p2[0:0] == 1'b1) ? select_ln52_88_fu_2635_p3 : 10'd0);

assign out_data_0_13_0_0_0_load_fu_2789_p3 = ((icmp_ln51_44_fu_2651_p2[0:0] == 1'b1) ? select_ln52_90_fu_2781_p3 : 10'd0);

assign out_data_0_14_0_0_0_load_fu_2935_p3 = ((icmp_ln51_45_fu_2797_p2[0:0] == 1'b1) ? select_ln52_92_fu_2927_p3 : 10'd0);

assign out_data_0_15_0_0_0_load_fu_3081_p3 = ((icmp_ln51_46_fu_2943_p2[0:0] == 1'b1) ? select_ln52_94_fu_3073_p3 : 10'd0);

assign out_data_0_16_0_0_0_load_fu_3227_p3 = ((icmp_ln51_47_fu_3089_p2[0:0] == 1'b1) ? select_ln52_96_fu_3219_p3 : 10'd0);

assign out_data_0_17_0_0_0_load_fu_3373_p3 = ((icmp_ln51_48_fu_3235_p2[0:0] == 1'b1) ? select_ln52_98_fu_3365_p3 : 10'd0);

assign out_data_0_18_0_0_0_load_fu_3519_p3 = ((icmp_ln51_49_fu_3381_p2[0:0] == 1'b1) ? select_ln52_100_fu_3511_p3 : 10'd0);

assign out_data_0_19_0_0_0_load_fu_3665_p3 = ((icmp_ln51_50_fu_3527_p2[0:0] == 1'b1) ? select_ln52_102_fu_3657_p3 : 10'd0);

assign out_data_0_1_0_0_0_load_fu_1037_p3 = ((icmp_ln51_32_fu_899_p2[0:0] == 1'b1) ? select_ln52_66_fu_1029_p3 : 10'd0);

assign out_data_0_20_0_0_0_load_fu_3811_p3 = ((icmp_ln51_51_fu_3673_p2[0:0] == 1'b1) ? select_ln52_104_fu_3803_p3 : 10'd0);

assign out_data_0_21_0_0_0_load_fu_3957_p3 = ((icmp_ln51_52_fu_3819_p2[0:0] == 1'b1) ? select_ln52_106_fu_3949_p3 : 10'd0);

assign out_data_0_22_0_0_0_load_fu_4103_p3 = ((icmp_ln51_53_fu_3965_p2[0:0] == 1'b1) ? select_ln52_108_fu_4095_p3 : 10'd0);

assign out_data_0_23_0_0_0_load_fu_4249_p3 = ((icmp_ln51_54_fu_4111_p2[0:0] == 1'b1) ? select_ln52_110_fu_4241_p3 : 10'd0);

assign out_data_0_24_0_0_0_load_fu_4395_p3 = ((icmp_ln51_55_fu_4257_p2[0:0] == 1'b1) ? select_ln52_112_fu_4387_p3 : 10'd0);

assign out_data_0_25_0_0_0_load_fu_4541_p3 = ((icmp_ln51_56_fu_4403_p2[0:0] == 1'b1) ? select_ln52_114_fu_4533_p3 : 10'd0);

assign out_data_0_26_0_0_0_load_fu_4687_p3 = ((icmp_ln51_57_fu_4549_p2[0:0] == 1'b1) ? select_ln52_116_fu_4679_p3 : 10'd0);

assign out_data_0_27_0_0_0_load_fu_4833_p3 = ((icmp_ln51_58_fu_4695_p2[0:0] == 1'b1) ? select_ln52_118_fu_4825_p3 : 10'd0);

assign out_data_0_28_0_0_0_load_fu_4979_p3 = ((icmp_ln51_59_fu_4841_p2[0:0] == 1'b1) ? select_ln52_120_fu_4971_p3 : 10'd0);

assign out_data_0_29_0_0_0_load_fu_5125_p3 = ((icmp_ln51_60_fu_4987_p2[0:0] == 1'b1) ? select_ln52_122_fu_5117_p3 : 10'd0);

assign out_data_0_2_0_0_0_load_fu_1183_p3 = ((icmp_ln51_33_fu_1045_p2[0:0] == 1'b1) ? select_ln52_68_fu_1175_p3 : 10'd0);

assign out_data_0_30_0_0_0_load_fu_5271_p3 = ((icmp_ln51_61_fu_5133_p2[0:0] == 1'b1) ? select_ln52_124_fu_5263_p3 : 10'd0);

assign out_data_0_31_0_0_0_load_fu_5417_p3 = ((icmp_ln51_62_fu_5279_p2[0:0] == 1'b1) ? select_ln52_126_fu_5409_p3 : 10'd0);

assign out_data_0_3_0_0_0_load_fu_1329_p3 = ((icmp_ln51_34_fu_1191_p2[0:0] == 1'b1) ? select_ln52_70_fu_1321_p3 : 10'd0);

assign out_data_0_4_0_0_0_load_fu_1475_p3 = ((icmp_ln51_35_fu_1337_p2[0:0] == 1'b1) ? select_ln52_72_fu_1467_p3 : 10'd0);

assign out_data_0_5_0_0_0_load_fu_1621_p3 = ((icmp_ln51_36_fu_1483_p2[0:0] == 1'b1) ? select_ln52_74_fu_1613_p3 : 10'd0);

assign out_data_0_6_0_0_0_load_fu_1767_p3 = ((icmp_ln51_37_fu_1629_p2[0:0] == 1'b1) ? select_ln52_76_fu_1759_p3 : 10'd0);

assign out_data_0_7_0_0_0_load_fu_1913_p3 = ((icmp_ln51_38_fu_1775_p2[0:0] == 1'b1) ? select_ln52_78_fu_1905_p3 : 10'd0);

assign out_data_0_8_0_0_0_load_fu_2059_p3 = ((icmp_ln51_39_fu_1921_p2[0:0] == 1'b1) ? select_ln52_80_fu_2051_p3 : 10'd0);

assign out_data_0_9_0_0_0_load_fu_2205_p3 = ((icmp_ln51_40_fu_2067_p2[0:0] == 1'b1) ? select_ln52_82_fu_2197_p3 : 10'd0);

assign select_ln52_100_fu_3511_p3 = ((or_ln52_164_fu_3505_p2[0:0] == 1'b1) ? select_ln52_99_fu_3497_p3 : add_ln52_49_fu_3425_p2);

assign select_ln52_101_fu_3643_p3 = ((and_ln52_102_fu_3637_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_102_fu_3657_p3 = ((or_ln52_166_fu_3651_p2[0:0] == 1'b1) ? select_ln52_101_fu_3643_p3 : add_ln52_50_fu_3571_p2);

assign select_ln52_103_fu_3789_p3 = ((and_ln52_104_fu_3783_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_104_fu_3803_p3 = ((or_ln52_168_fu_3797_p2[0:0] == 1'b1) ? select_ln52_103_fu_3789_p3 : add_ln52_51_fu_3717_p2);

assign select_ln52_105_fu_3935_p3 = ((and_ln52_106_fu_3929_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_106_fu_3949_p3 = ((or_ln52_170_fu_3943_p2[0:0] == 1'b1) ? select_ln52_105_fu_3935_p3 : add_ln52_52_fu_3863_p2);

assign select_ln52_107_fu_4081_p3 = ((and_ln52_108_fu_4075_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_108_fu_4095_p3 = ((or_ln52_172_fu_4089_p2[0:0] == 1'b1) ? select_ln52_107_fu_4081_p3 : add_ln52_53_fu_4009_p2);

assign select_ln52_109_fu_4227_p3 = ((and_ln52_110_fu_4221_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_110_fu_4241_p3 = ((or_ln52_174_fu_4235_p2[0:0] == 1'b1) ? select_ln52_109_fu_4227_p3 : add_ln52_54_fu_4155_p2);

assign select_ln52_111_fu_4373_p3 = ((and_ln52_112_fu_4367_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_112_fu_4387_p3 = ((or_ln52_176_fu_4381_p2[0:0] == 1'b1) ? select_ln52_111_fu_4373_p3 : add_ln52_55_fu_4301_p2);

assign select_ln52_113_fu_4519_p3 = ((and_ln52_114_fu_4513_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_114_fu_4533_p3 = ((or_ln52_178_fu_4527_p2[0:0] == 1'b1) ? select_ln52_113_fu_4519_p3 : add_ln52_56_fu_4447_p2);

assign select_ln52_115_fu_4665_p3 = ((and_ln52_116_fu_4659_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_116_fu_4679_p3 = ((or_ln52_180_fu_4673_p2[0:0] == 1'b1) ? select_ln52_115_fu_4665_p3 : add_ln52_57_fu_4593_p2);

assign select_ln52_117_fu_4811_p3 = ((and_ln52_118_fu_4805_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_118_fu_4825_p3 = ((or_ln52_182_fu_4819_p2[0:0] == 1'b1) ? select_ln52_117_fu_4811_p3 : add_ln52_58_fu_4739_p2);

assign select_ln52_119_fu_4957_p3 = ((and_ln52_120_fu_4951_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_120_fu_4971_p3 = ((or_ln52_184_fu_4965_p2[0:0] == 1'b1) ? select_ln52_119_fu_4957_p3 : add_ln52_59_fu_4885_p2);

assign select_ln52_121_fu_5103_p3 = ((and_ln52_122_fu_5097_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_122_fu_5117_p3 = ((or_ln52_186_fu_5111_p2[0:0] == 1'b1) ? select_ln52_121_fu_5103_p3 : add_ln52_60_fu_5031_p2);

assign select_ln52_123_fu_5249_p3 = ((and_ln52_124_fu_5243_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_124_fu_5263_p3 = ((or_ln52_188_fu_5257_p2[0:0] == 1'b1) ? select_ln52_123_fu_5249_p3 : add_ln52_61_fu_5177_p2);

assign select_ln52_125_fu_5395_p3 = ((and_ln52_126_fu_5389_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_126_fu_5409_p3 = ((or_ln52_190_fu_5403_p2[0:0] == 1'b1) ? select_ln52_125_fu_5395_p3 : add_ln52_62_fu_5323_p2);

assign select_ln52_64_fu_883_p3 = ((or_ln52_99_fu_877_p2[0:0] == 1'b1) ? select_ln52_fu_869_p3 : add_ln52_fu_797_p2);

assign select_ln52_65_fu_1015_p3 = ((and_ln52_66_fu_1009_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_66_fu_1029_p3 = ((or_ln52_103_fu_1023_p2[0:0] == 1'b1) ? select_ln52_65_fu_1015_p3 : add_ln52_32_fu_943_p2);

assign select_ln52_67_fu_1161_p3 = ((and_ln52_68_fu_1155_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_68_fu_1175_p3 = ((or_ln52_107_fu_1169_p2[0:0] == 1'b1) ? select_ln52_67_fu_1161_p3 : add_ln52_33_fu_1089_p2);

assign select_ln52_69_fu_1307_p3 = ((and_ln52_70_fu_1301_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_70_fu_1321_p3 = ((or_ln52_111_fu_1315_p2[0:0] == 1'b1) ? select_ln52_69_fu_1307_p3 : add_ln52_34_fu_1235_p2);

assign select_ln52_71_fu_1453_p3 = ((and_ln52_72_fu_1447_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_72_fu_1467_p3 = ((or_ln52_115_fu_1461_p2[0:0] == 1'b1) ? select_ln52_71_fu_1453_p3 : add_ln52_35_fu_1381_p2);

assign select_ln52_73_fu_1599_p3 = ((and_ln52_74_fu_1593_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_74_fu_1613_p3 = ((or_ln52_119_fu_1607_p2[0:0] == 1'b1) ? select_ln52_73_fu_1599_p3 : add_ln52_36_fu_1527_p2);

assign select_ln52_75_fu_1745_p3 = ((and_ln52_76_fu_1739_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_76_fu_1759_p3 = ((or_ln52_123_fu_1753_p2[0:0] == 1'b1) ? select_ln52_75_fu_1745_p3 : add_ln52_37_fu_1673_p2);

assign select_ln52_77_fu_1891_p3 = ((and_ln52_78_fu_1885_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_78_fu_1905_p3 = ((or_ln52_127_fu_1899_p2[0:0] == 1'b1) ? select_ln52_77_fu_1891_p3 : add_ln52_38_fu_1819_p2);

assign select_ln52_79_fu_2037_p3 = ((and_ln52_80_fu_2031_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_80_fu_2051_p3 = ((or_ln52_131_fu_2045_p2[0:0] == 1'b1) ? select_ln52_79_fu_2037_p3 : add_ln52_39_fu_1965_p2);

assign select_ln52_81_fu_2183_p3 = ((and_ln52_82_fu_2177_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_82_fu_2197_p3 = ((or_ln52_135_fu_2191_p2[0:0] == 1'b1) ? select_ln52_81_fu_2183_p3 : add_ln52_40_fu_2111_p2);

assign select_ln52_83_fu_2329_p3 = ((and_ln52_84_fu_2323_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_84_fu_2343_p3 = ((or_ln52_139_fu_2337_p2[0:0] == 1'b1) ? select_ln52_83_fu_2329_p3 : add_ln52_41_fu_2257_p2);

assign select_ln52_85_fu_2475_p3 = ((and_ln52_86_fu_2469_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_86_fu_2489_p3 = ((or_ln52_143_fu_2483_p2[0:0] == 1'b1) ? select_ln52_85_fu_2475_p3 : add_ln52_42_fu_2403_p2);

assign select_ln52_87_fu_2621_p3 = ((and_ln52_88_fu_2615_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_88_fu_2635_p3 = ((or_ln52_147_fu_2629_p2[0:0] == 1'b1) ? select_ln52_87_fu_2621_p3 : add_ln52_43_fu_2549_p2);

assign select_ln52_89_fu_2767_p3 = ((and_ln52_90_fu_2761_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_90_fu_2781_p3 = ((or_ln52_151_fu_2775_p2[0:0] == 1'b1) ? select_ln52_89_fu_2767_p3 : add_ln52_44_fu_2695_p2);

assign select_ln52_91_fu_2913_p3 = ((and_ln52_92_fu_2907_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_92_fu_2927_p3 = ((or_ln52_155_fu_2921_p2[0:0] == 1'b1) ? select_ln52_91_fu_2913_p3 : add_ln52_45_fu_2841_p2);

assign select_ln52_93_fu_3059_p3 = ((and_ln52_94_fu_3053_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_94_fu_3073_p3 = ((or_ln52_158_fu_3067_p2[0:0] == 1'b1) ? select_ln52_93_fu_3059_p3 : add_ln52_46_fu_2987_p2);

assign select_ln52_95_fu_3205_p3 = ((and_ln52_96_fu_3199_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_96_fu_3219_p3 = ((or_ln52_160_fu_3213_p2[0:0] == 1'b1) ? select_ln52_95_fu_3205_p3 : add_ln52_47_fu_3133_p2);

assign select_ln52_97_fu_3351_p3 = ((and_ln52_98_fu_3345_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_98_fu_3365_p3 = ((or_ln52_162_fu_3359_p2[0:0] == 1'b1) ? select_ln52_97_fu_3351_p3 : add_ln52_48_fu_3279_p2);

assign select_ln52_99_fu_3497_p3 = ((and_ln52_100_fu_3491_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln52_fu_869_p3 = ((and_ln52_64_fu_863_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign start_out = real_start;

assign tmp_239_fu_777_p3 = layer3_out_dout[32'd6];

assign tmp_240_fu_785_p3 = layer3_out_dout[32'd16];

assign tmp_241_fu_803_p3 = add_ln52_fu_797_p2[32'd9];

assign tmp_242_fu_905_p3 = layer3_out_dout[32'd49];

assign tmp_244_fu_923_p3 = layer3_out_dout[32'd31];

assign tmp_245_fu_931_p3 = layer3_out_dout[32'd41];

assign tmp_246_fu_949_p3 = add_ln52_32_fu_943_p2[32'd9];

assign tmp_247_fu_1051_p3 = layer3_out_dout[32'd74];

assign tmp_249_fu_1069_p3 = layer3_out_dout[32'd56];

assign tmp_250_fu_1077_p3 = layer3_out_dout[32'd66];

assign tmp_251_fu_1095_p3 = add_ln52_33_fu_1089_p2[32'd9];

assign tmp_252_fu_1197_p3 = layer3_out_dout[32'd99];

assign tmp_254_fu_1215_p3 = layer3_out_dout[32'd81];

assign tmp_255_fu_1223_p3 = layer3_out_dout[32'd91];

assign tmp_256_fu_1241_p3 = add_ln52_34_fu_1235_p2[32'd9];

assign tmp_257_fu_1343_p3 = layer3_out_dout[32'd124];

assign tmp_259_fu_1361_p3 = layer3_out_dout[32'd106];

assign tmp_260_fu_1369_p3 = layer3_out_dout[32'd116];

assign tmp_261_fu_1387_p3 = add_ln52_35_fu_1381_p2[32'd9];

assign tmp_262_fu_1489_p3 = layer3_out_dout[32'd149];

assign tmp_264_fu_1507_p3 = layer3_out_dout[32'd131];

assign tmp_265_fu_1515_p3 = layer3_out_dout[32'd141];

assign tmp_266_fu_1533_p3 = add_ln52_36_fu_1527_p2[32'd9];

assign tmp_267_fu_1635_p3 = layer3_out_dout[32'd174];

assign tmp_269_fu_1653_p3 = layer3_out_dout[32'd156];

assign tmp_270_fu_1661_p3 = layer3_out_dout[32'd166];

assign tmp_271_fu_1679_p3 = add_ln52_37_fu_1673_p2[32'd9];

assign tmp_272_fu_1781_p3 = layer3_out_dout[32'd199];

assign tmp_274_fu_1799_p3 = layer3_out_dout[32'd181];

assign tmp_275_fu_1807_p3 = layer3_out_dout[32'd191];

assign tmp_276_fu_1825_p3 = add_ln52_38_fu_1819_p2[32'd9];

assign tmp_277_fu_1927_p3 = layer3_out_dout[32'd224];

assign tmp_279_fu_1945_p3 = layer3_out_dout[32'd206];

assign tmp_280_fu_1953_p3 = layer3_out_dout[32'd216];

assign tmp_281_fu_1971_p3 = add_ln52_39_fu_1965_p2[32'd9];

assign tmp_282_fu_2073_p3 = layer3_out_dout[32'd249];

assign tmp_284_fu_2091_p3 = layer3_out_dout[32'd231];

assign tmp_285_fu_2099_p3 = layer3_out_dout[32'd241];

assign tmp_286_fu_2117_p3 = add_ln52_40_fu_2111_p2[32'd9];

assign tmp_287_fu_2219_p3 = layer3_out_dout[32'd274];

assign tmp_289_fu_2237_p3 = layer3_out_dout[32'd256];

assign tmp_290_fu_2245_p3 = layer3_out_dout[32'd266];

assign tmp_291_fu_2263_p3 = add_ln52_41_fu_2257_p2[32'd9];

assign tmp_292_fu_2365_p3 = layer3_out_dout[32'd299];

assign tmp_294_fu_2383_p3 = layer3_out_dout[32'd281];

assign tmp_295_fu_2391_p3 = layer3_out_dout[32'd291];

assign tmp_296_fu_2409_p3 = add_ln52_42_fu_2403_p2[32'd9];

assign tmp_297_fu_2511_p3 = layer3_out_dout[32'd324];

assign tmp_299_fu_2529_p3 = layer3_out_dout[32'd306];

assign tmp_300_fu_2537_p3 = layer3_out_dout[32'd316];

assign tmp_301_fu_2555_p3 = add_ln52_43_fu_2549_p2[32'd9];

assign tmp_302_fu_2657_p3 = layer3_out_dout[32'd349];

assign tmp_304_fu_2675_p3 = layer3_out_dout[32'd331];

assign tmp_305_fu_2683_p3 = layer3_out_dout[32'd341];

assign tmp_306_fu_2701_p3 = add_ln52_44_fu_2695_p2[32'd9];

assign tmp_307_fu_2803_p3 = layer3_out_dout[32'd374];

assign tmp_309_fu_2821_p3 = layer3_out_dout[32'd356];

assign tmp_310_fu_2829_p3 = layer3_out_dout[32'd366];

assign tmp_311_fu_2847_p3 = add_ln52_45_fu_2841_p2[32'd9];

assign tmp_312_fu_2949_p3 = layer3_out_dout[32'd399];

assign tmp_314_fu_2967_p3 = layer3_out_dout[32'd381];

assign tmp_315_fu_2975_p3 = layer3_out_dout[32'd391];

assign tmp_316_fu_2993_p3 = add_ln52_46_fu_2987_p2[32'd9];

assign tmp_317_fu_3095_p3 = layer3_out_dout[32'd424];

assign tmp_319_fu_3113_p3 = layer3_out_dout[32'd406];

assign tmp_320_fu_3121_p3 = layer3_out_dout[32'd416];

assign tmp_321_fu_3139_p3 = add_ln52_47_fu_3133_p2[32'd9];

assign tmp_322_fu_3241_p3 = layer3_out_dout[32'd449];

assign tmp_324_fu_3259_p3 = layer3_out_dout[32'd431];

assign tmp_325_fu_3267_p3 = layer3_out_dout[32'd441];

assign tmp_326_fu_3285_p3 = add_ln52_48_fu_3279_p2[32'd9];

assign tmp_327_fu_3387_p3 = layer3_out_dout[32'd474];

assign tmp_329_fu_3405_p3 = layer3_out_dout[32'd456];

assign tmp_330_fu_3413_p3 = layer3_out_dout[32'd466];

assign tmp_331_fu_3431_p3 = add_ln52_49_fu_3425_p2[32'd9];

assign tmp_332_fu_3533_p3 = layer3_out_dout[32'd499];

assign tmp_334_fu_3551_p3 = layer3_out_dout[32'd481];

assign tmp_335_fu_3559_p3 = layer3_out_dout[32'd491];

assign tmp_336_fu_3577_p3 = add_ln52_50_fu_3571_p2[32'd9];

assign tmp_337_fu_3679_p3 = layer3_out_dout[32'd524];

assign tmp_339_fu_3697_p3 = layer3_out_dout[32'd506];

assign tmp_340_fu_3705_p3 = layer3_out_dout[32'd516];

assign tmp_341_fu_3723_p3 = add_ln52_51_fu_3717_p2[32'd9];

assign tmp_342_fu_3825_p3 = layer3_out_dout[32'd549];

assign tmp_344_fu_3843_p3 = layer3_out_dout[32'd531];

assign tmp_345_fu_3851_p3 = layer3_out_dout[32'd541];

assign tmp_346_fu_3869_p3 = add_ln52_52_fu_3863_p2[32'd9];

assign tmp_347_fu_3971_p3 = layer3_out_dout[32'd574];

assign tmp_349_fu_3989_p3 = layer3_out_dout[32'd556];

assign tmp_350_fu_3997_p3 = layer3_out_dout[32'd566];

assign tmp_351_fu_4015_p3 = add_ln52_53_fu_4009_p2[32'd9];

assign tmp_352_fu_4117_p3 = layer3_out_dout[32'd599];

assign tmp_354_fu_4135_p3 = layer3_out_dout[32'd581];

assign tmp_355_fu_4143_p3 = layer3_out_dout[32'd591];

assign tmp_356_fu_4161_p3 = add_ln52_54_fu_4155_p2[32'd9];

assign tmp_357_fu_4263_p3 = layer3_out_dout[32'd624];

assign tmp_359_fu_4281_p3 = layer3_out_dout[32'd606];

assign tmp_360_fu_4289_p3 = layer3_out_dout[32'd616];

assign tmp_361_fu_4307_p3 = add_ln52_55_fu_4301_p2[32'd9];

assign tmp_362_fu_4409_p3 = layer3_out_dout[32'd649];

assign tmp_364_fu_4427_p3 = layer3_out_dout[32'd631];

assign tmp_365_fu_4435_p3 = layer3_out_dout[32'd641];

assign tmp_366_fu_4453_p3 = add_ln52_56_fu_4447_p2[32'd9];

assign tmp_367_fu_4555_p3 = layer3_out_dout[32'd674];

assign tmp_369_fu_4573_p3 = layer3_out_dout[32'd656];

assign tmp_370_fu_4581_p3 = layer3_out_dout[32'd666];

assign tmp_371_fu_4599_p3 = add_ln52_57_fu_4593_p2[32'd9];

assign tmp_372_fu_4701_p3 = layer3_out_dout[32'd699];

assign tmp_374_fu_4719_p3 = layer3_out_dout[32'd681];

assign tmp_375_fu_4727_p3 = layer3_out_dout[32'd691];

assign tmp_376_fu_4745_p3 = add_ln52_58_fu_4739_p2[32'd9];

assign tmp_377_fu_4847_p3 = layer3_out_dout[32'd724];

assign tmp_379_fu_4865_p3 = layer3_out_dout[32'd706];

assign tmp_380_fu_4873_p3 = layer3_out_dout[32'd716];

assign tmp_381_fu_4891_p3 = add_ln52_59_fu_4885_p2[32'd9];

assign tmp_382_fu_4993_p3 = layer3_out_dout[32'd749];

assign tmp_383_fu_5011_p3 = layer3_out_dout[32'd731];

assign tmp_384_fu_5019_p3 = layer3_out_dout[32'd741];

assign tmp_385_fu_5037_p3 = add_ln52_60_fu_5031_p2[32'd9];

assign tmp_386_fu_5139_p3 = layer3_out_dout[32'd774];

assign tmp_387_fu_5157_p3 = layer3_out_dout[32'd756];

assign tmp_388_fu_5165_p3 = layer3_out_dout[32'd766];

assign tmp_389_fu_5183_p3 = add_ln52_61_fu_5177_p2[32'd9];

assign tmp_390_fu_5285_p3 = layer3_out_dout[32'd799];

assign tmp_391_fu_5303_p3 = layer3_out_dout[32'd781];

assign tmp_392_fu_5311_p3 = layer3_out_dout[32'd791];

assign tmp_393_fu_5329_p3 = add_ln52_62_fu_5323_p2[32'd9];

assign tmp_59_fu_957_p4 = {{layer3_out_dout[49:42]}};

assign tmp_60_fu_1103_p4 = {{layer3_out_dout[74:67]}};

assign tmp_61_fu_1249_p4 = {{layer3_out_dout[99:92]}};

assign tmp_62_fu_1395_p4 = {{layer3_out_dout[124:117]}};

assign tmp_63_fu_1541_p4 = {{layer3_out_dout[149:142]}};

assign tmp_64_fu_1687_p4 = {{layer3_out_dout[174:167]}};

assign tmp_65_fu_1833_p4 = {{layer3_out_dout[199:192]}};

assign tmp_66_fu_1979_p4 = {{layer3_out_dout[224:217]}};

assign tmp_67_fu_2125_p4 = {{layer3_out_dout[249:242]}};

assign tmp_68_fu_2271_p4 = {{layer3_out_dout[274:267]}};

assign tmp_69_fu_2417_p4 = {{layer3_out_dout[299:292]}};

assign tmp_70_fu_2563_p4 = {{layer3_out_dout[324:317]}};

assign tmp_71_fu_2709_p4 = {{layer3_out_dout[349:342]}};

assign tmp_72_fu_2855_p4 = {{layer3_out_dout[374:367]}};

assign tmp_73_fu_3001_p4 = {{layer3_out_dout[399:392]}};

assign tmp_74_fu_3147_p4 = {{layer3_out_dout[424:417]}};

assign tmp_75_fu_3293_p4 = {{layer3_out_dout[449:442]}};

assign tmp_76_fu_3439_p4 = {{layer3_out_dout[474:467]}};

assign tmp_77_fu_3585_p4 = {{layer3_out_dout[499:492]}};

assign tmp_78_fu_3731_p4 = {{layer3_out_dout[524:517]}};

assign tmp_79_fu_3877_p4 = {{layer3_out_dout[549:542]}};

assign tmp_80_fu_4023_p4 = {{layer3_out_dout[574:567]}};

assign tmp_81_fu_4169_p4 = {{layer3_out_dout[599:592]}};

assign tmp_82_fu_4315_p4 = {{layer3_out_dout[624:617]}};

assign tmp_83_fu_4461_p4 = {{layer3_out_dout[649:642]}};

assign tmp_84_fu_4607_p4 = {{layer3_out_dout[674:667]}};

assign tmp_85_fu_4753_p4 = {{layer3_out_dout[699:692]}};

assign tmp_86_fu_4899_p4 = {{layer3_out_dout[724:717]}};

assign tmp_87_fu_5045_p4 = {{layer3_out_dout[749:742]}};

assign tmp_88_fu_5191_p4 = {{layer3_out_dout[774:767]}};

assign tmp_89_fu_5337_p4 = {{layer3_out_dout[799:792]}};

assign tmp_fu_759_p3 = layer3_out_dout[32'd24];

assign tmp_s_fu_811_p4 = {{layer3_out_dout[24:17]}};

assign trunc_ln44_31_fu_453_p4 = {{layer3_out_dout[74:50]}};

assign trunc_ln44_32_fu_463_p4 = {{layer3_out_dout[99:75]}};

assign trunc_ln44_33_fu_473_p4 = {{layer3_out_dout[124:100]}};

assign trunc_ln44_34_fu_483_p4 = {{layer3_out_dout[149:125]}};

assign trunc_ln44_35_fu_493_p4 = {{layer3_out_dout[174:150]}};

assign trunc_ln44_36_fu_503_p4 = {{layer3_out_dout[199:175]}};

assign trunc_ln44_37_fu_513_p4 = {{layer3_out_dout[224:200]}};

assign trunc_ln44_38_fu_523_p4 = {{layer3_out_dout[249:225]}};

assign trunc_ln44_39_fu_533_p4 = {{layer3_out_dout[274:250]}};

assign trunc_ln44_40_fu_543_p4 = {{layer3_out_dout[299:275]}};

assign trunc_ln44_41_fu_553_p4 = {{layer3_out_dout[324:300]}};

assign trunc_ln44_42_fu_563_p4 = {{layer3_out_dout[349:325]}};

assign trunc_ln44_43_fu_573_p4 = {{layer3_out_dout[374:350]}};

assign trunc_ln44_44_fu_583_p4 = {{layer3_out_dout[399:375]}};

assign trunc_ln44_45_fu_593_p4 = {{layer3_out_dout[424:400]}};

assign trunc_ln44_46_fu_603_p4 = {{layer3_out_dout[449:425]}};

assign trunc_ln44_47_fu_613_p4 = {{layer3_out_dout[474:450]}};

assign trunc_ln44_48_fu_623_p4 = {{layer3_out_dout[499:475]}};

assign trunc_ln44_49_fu_633_p4 = {{layer3_out_dout[524:500]}};

assign trunc_ln44_50_fu_643_p4 = {{layer3_out_dout[549:525]}};

assign trunc_ln44_51_fu_653_p4 = {{layer3_out_dout[574:550]}};

assign trunc_ln44_52_fu_663_p4 = {{layer3_out_dout[599:575]}};

assign trunc_ln44_53_fu_673_p4 = {{layer3_out_dout[624:600]}};

assign trunc_ln44_54_fu_683_p4 = {{layer3_out_dout[649:625]}};

assign trunc_ln44_55_fu_693_p4 = {{layer3_out_dout[674:650]}};

assign trunc_ln44_56_fu_703_p4 = {{layer3_out_dout[699:675]}};

assign trunc_ln44_57_fu_713_p4 = {{layer3_out_dout[724:700]}};

assign trunc_ln44_58_fu_723_p4 = {{layer3_out_dout[749:725]}};

assign trunc_ln44_59_fu_733_p4 = {{layer3_out_dout[774:750]}};

assign trunc_ln44_60_fu_743_p4 = {{layer3_out_dout[799:775]}};

assign trunc_ln44_fu_439_p1 = layer3_out_dout[24:0];

assign trunc_ln44_s_fu_443_p4 = {{layer3_out_dout[49:25]}};

assign trunc_ln4_fu_767_p4 = {{layer3_out_dout[16:7]}};

assign trunc_ln52_31_fu_1059_p4 = {{layer3_out_dout[66:57]}};

assign trunc_ln52_32_fu_1205_p4 = {{layer3_out_dout[91:82]}};

assign trunc_ln52_33_fu_1351_p4 = {{layer3_out_dout[116:107]}};

assign trunc_ln52_34_fu_1497_p4 = {{layer3_out_dout[141:132]}};

assign trunc_ln52_35_fu_1643_p4 = {{layer3_out_dout[166:157]}};

assign trunc_ln52_36_fu_1789_p4 = {{layer3_out_dout[191:182]}};

assign trunc_ln52_37_fu_1935_p4 = {{layer3_out_dout[216:207]}};

assign trunc_ln52_38_fu_2081_p4 = {{layer3_out_dout[241:232]}};

assign trunc_ln52_39_fu_2227_p4 = {{layer3_out_dout[266:257]}};

assign trunc_ln52_40_fu_2373_p4 = {{layer3_out_dout[291:282]}};

assign trunc_ln52_41_fu_2519_p4 = {{layer3_out_dout[316:307]}};

assign trunc_ln52_42_fu_2665_p4 = {{layer3_out_dout[341:332]}};

assign trunc_ln52_43_fu_2811_p4 = {{layer3_out_dout[366:357]}};

assign trunc_ln52_44_fu_2957_p4 = {{layer3_out_dout[391:382]}};

assign trunc_ln52_45_fu_3103_p4 = {{layer3_out_dout[416:407]}};

assign trunc_ln52_46_fu_3249_p4 = {{layer3_out_dout[441:432]}};

assign trunc_ln52_47_fu_3395_p4 = {{layer3_out_dout[466:457]}};

assign trunc_ln52_48_fu_3541_p4 = {{layer3_out_dout[491:482]}};

assign trunc_ln52_49_fu_3687_p4 = {{layer3_out_dout[516:507]}};

assign trunc_ln52_50_fu_3833_p4 = {{layer3_out_dout[541:532]}};

assign trunc_ln52_51_fu_3979_p4 = {{layer3_out_dout[566:557]}};

assign trunc_ln52_52_fu_4125_p4 = {{layer3_out_dout[591:582]}};

assign trunc_ln52_53_fu_4271_p4 = {{layer3_out_dout[616:607]}};

assign trunc_ln52_54_fu_4417_p4 = {{layer3_out_dout[641:632]}};

assign trunc_ln52_55_fu_4563_p4 = {{layer3_out_dout[666:657]}};

assign trunc_ln52_56_fu_4709_p4 = {{layer3_out_dout[691:682]}};

assign trunc_ln52_57_fu_4855_p4 = {{layer3_out_dout[716:707]}};

assign trunc_ln52_58_fu_5001_p4 = {{layer3_out_dout[741:732]}};

assign trunc_ln52_59_fu_5147_p4 = {{layer3_out_dout[766:757]}};

assign trunc_ln52_60_fu_5293_p4 = {{layer3_out_dout[791:782]}};

assign trunc_ln52_s_fu_913_p4 = {{layer3_out_dout[41:32]}};

assign xor_ln52_100_fu_1003_p2 = (tmp_242_fu_905_p3 ^ 1'd1);

assign xor_ln52_101_fu_1119_p2 = (tmp_250_fu_1077_p3 ^ 1'd1);

assign xor_ln52_102_fu_1137_p2 = (1'd1 ^ and_ln52_67_fu_1131_p2);

assign xor_ln52_103_fu_1149_p2 = (tmp_247_fu_1051_p3 ^ 1'd1);

assign xor_ln52_104_fu_1265_p2 = (tmp_255_fu_1223_p3 ^ 1'd1);

assign xor_ln52_105_fu_1283_p2 = (1'd1 ^ and_ln52_69_fu_1277_p2);

assign xor_ln52_106_fu_1295_p2 = (tmp_252_fu_1197_p3 ^ 1'd1);

assign xor_ln52_107_fu_1411_p2 = (tmp_260_fu_1369_p3 ^ 1'd1);

assign xor_ln52_108_fu_1429_p2 = (1'd1 ^ and_ln52_71_fu_1423_p2);

assign xor_ln52_109_fu_1441_p2 = (tmp_257_fu_1343_p3 ^ 1'd1);

assign xor_ln52_110_fu_1557_p2 = (tmp_265_fu_1515_p3 ^ 1'd1);

assign xor_ln52_111_fu_1575_p2 = (1'd1 ^ and_ln52_73_fu_1569_p2);

assign xor_ln52_112_fu_1587_p2 = (tmp_262_fu_1489_p3 ^ 1'd1);

assign xor_ln52_113_fu_1703_p2 = (tmp_270_fu_1661_p3 ^ 1'd1);

assign xor_ln52_114_fu_1721_p2 = (1'd1 ^ and_ln52_75_fu_1715_p2);

assign xor_ln52_115_fu_1733_p2 = (tmp_267_fu_1635_p3 ^ 1'd1);

assign xor_ln52_116_fu_1849_p2 = (tmp_275_fu_1807_p3 ^ 1'd1);

assign xor_ln52_117_fu_1867_p2 = (1'd1 ^ and_ln52_77_fu_1861_p2);

assign xor_ln52_118_fu_1879_p2 = (tmp_272_fu_1781_p3 ^ 1'd1);

assign xor_ln52_119_fu_1995_p2 = (tmp_280_fu_1953_p3 ^ 1'd1);

assign xor_ln52_120_fu_2013_p2 = (1'd1 ^ and_ln52_79_fu_2007_p2);

assign xor_ln52_121_fu_2025_p2 = (tmp_277_fu_1927_p3 ^ 1'd1);

assign xor_ln52_122_fu_2141_p2 = (tmp_285_fu_2099_p3 ^ 1'd1);

assign xor_ln52_123_fu_2159_p2 = (1'd1 ^ and_ln52_81_fu_2153_p2);

assign xor_ln52_124_fu_2171_p2 = (tmp_282_fu_2073_p3 ^ 1'd1);

assign xor_ln52_125_fu_2287_p2 = (tmp_290_fu_2245_p3 ^ 1'd1);

assign xor_ln52_126_fu_2305_p2 = (1'd1 ^ and_ln52_83_fu_2299_p2);

assign xor_ln52_127_fu_2317_p2 = (tmp_287_fu_2219_p3 ^ 1'd1);

assign xor_ln52_128_fu_2433_p2 = (tmp_295_fu_2391_p3 ^ 1'd1);

assign xor_ln52_129_fu_2451_p2 = (1'd1 ^ and_ln52_85_fu_2445_p2);

assign xor_ln52_130_fu_2463_p2 = (tmp_292_fu_2365_p3 ^ 1'd1);

assign xor_ln52_131_fu_2579_p2 = (tmp_300_fu_2537_p3 ^ 1'd1);

assign xor_ln52_132_fu_2597_p2 = (1'd1 ^ and_ln52_87_fu_2591_p2);

assign xor_ln52_133_fu_2609_p2 = (tmp_297_fu_2511_p3 ^ 1'd1);

assign xor_ln52_134_fu_2725_p2 = (tmp_305_fu_2683_p3 ^ 1'd1);

assign xor_ln52_135_fu_2743_p2 = (1'd1 ^ and_ln52_89_fu_2737_p2);

assign xor_ln52_136_fu_2755_p2 = (tmp_302_fu_2657_p3 ^ 1'd1);

assign xor_ln52_137_fu_2871_p2 = (tmp_310_fu_2829_p3 ^ 1'd1);

assign xor_ln52_138_fu_2889_p2 = (1'd1 ^ and_ln52_91_fu_2883_p2);

assign xor_ln52_139_fu_2901_p2 = (tmp_307_fu_2803_p3 ^ 1'd1);

assign xor_ln52_140_fu_3017_p2 = (tmp_315_fu_2975_p3 ^ 1'd1);

assign xor_ln52_141_fu_3035_p2 = (1'd1 ^ and_ln52_93_fu_3029_p2);

assign xor_ln52_142_fu_3047_p2 = (tmp_312_fu_2949_p3 ^ 1'd1);

assign xor_ln52_143_fu_3163_p2 = (tmp_320_fu_3121_p3 ^ 1'd1);

assign xor_ln52_144_fu_3181_p2 = (1'd1 ^ and_ln52_95_fu_3175_p2);

assign xor_ln52_145_fu_3193_p2 = (tmp_317_fu_3095_p3 ^ 1'd1);

assign xor_ln52_146_fu_3309_p2 = (tmp_325_fu_3267_p3 ^ 1'd1);

assign xor_ln52_147_fu_3327_p2 = (1'd1 ^ and_ln52_97_fu_3321_p2);

assign xor_ln52_148_fu_3339_p2 = (tmp_322_fu_3241_p3 ^ 1'd1);

assign xor_ln52_149_fu_3455_p2 = (tmp_330_fu_3413_p3 ^ 1'd1);

assign xor_ln52_150_fu_3473_p2 = (1'd1 ^ and_ln52_99_fu_3467_p2);

assign xor_ln52_151_fu_3485_p2 = (tmp_327_fu_3387_p3 ^ 1'd1);

assign xor_ln52_152_fu_3601_p2 = (tmp_335_fu_3559_p3 ^ 1'd1);

assign xor_ln52_153_fu_3619_p2 = (1'd1 ^ and_ln52_101_fu_3613_p2);

assign xor_ln52_154_fu_3631_p2 = (tmp_332_fu_3533_p3 ^ 1'd1);

assign xor_ln52_155_fu_3747_p2 = (tmp_340_fu_3705_p3 ^ 1'd1);

assign xor_ln52_156_fu_3765_p2 = (1'd1 ^ and_ln52_103_fu_3759_p2);

assign xor_ln52_157_fu_3777_p2 = (tmp_337_fu_3679_p3 ^ 1'd1);

assign xor_ln52_158_fu_3893_p2 = (tmp_345_fu_3851_p3 ^ 1'd1);

assign xor_ln52_159_fu_3911_p2 = (1'd1 ^ and_ln52_105_fu_3905_p2);

assign xor_ln52_160_fu_3923_p2 = (tmp_342_fu_3825_p3 ^ 1'd1);

assign xor_ln52_161_fu_4039_p2 = (tmp_350_fu_3997_p3 ^ 1'd1);

assign xor_ln52_162_fu_4057_p2 = (1'd1 ^ and_ln52_107_fu_4051_p2);

assign xor_ln52_163_fu_4069_p2 = (tmp_347_fu_3971_p3 ^ 1'd1);

assign xor_ln52_164_fu_4185_p2 = (tmp_355_fu_4143_p3 ^ 1'd1);

assign xor_ln52_165_fu_4203_p2 = (1'd1 ^ and_ln52_109_fu_4197_p2);

assign xor_ln52_166_fu_4215_p2 = (tmp_352_fu_4117_p3 ^ 1'd1);

assign xor_ln52_167_fu_4331_p2 = (tmp_360_fu_4289_p3 ^ 1'd1);

assign xor_ln52_168_fu_4349_p2 = (1'd1 ^ and_ln52_111_fu_4343_p2);

assign xor_ln52_169_fu_4361_p2 = (tmp_357_fu_4263_p3 ^ 1'd1);

assign xor_ln52_170_fu_4477_p2 = (tmp_365_fu_4435_p3 ^ 1'd1);

assign xor_ln52_171_fu_4495_p2 = (1'd1 ^ and_ln52_113_fu_4489_p2);

assign xor_ln52_172_fu_4507_p2 = (tmp_362_fu_4409_p3 ^ 1'd1);

assign xor_ln52_173_fu_4623_p2 = (tmp_370_fu_4581_p3 ^ 1'd1);

assign xor_ln52_174_fu_4641_p2 = (1'd1 ^ and_ln52_115_fu_4635_p2);

assign xor_ln52_175_fu_4653_p2 = (tmp_367_fu_4555_p3 ^ 1'd1);

assign xor_ln52_176_fu_4769_p2 = (tmp_375_fu_4727_p3 ^ 1'd1);

assign xor_ln52_177_fu_4787_p2 = (1'd1 ^ and_ln52_117_fu_4781_p2);

assign xor_ln52_178_fu_4799_p2 = (tmp_372_fu_4701_p3 ^ 1'd1);

assign xor_ln52_179_fu_4915_p2 = (tmp_380_fu_4873_p3 ^ 1'd1);

assign xor_ln52_180_fu_4933_p2 = (1'd1 ^ and_ln52_119_fu_4927_p2);

assign xor_ln52_181_fu_4945_p2 = (tmp_377_fu_4847_p3 ^ 1'd1);

assign xor_ln52_182_fu_5061_p2 = (tmp_384_fu_5019_p3 ^ 1'd1);

assign xor_ln52_183_fu_5079_p2 = (1'd1 ^ and_ln52_121_fu_5073_p2);

assign xor_ln52_184_fu_5091_p2 = (tmp_382_fu_4993_p3 ^ 1'd1);

assign xor_ln52_185_fu_5207_p2 = (tmp_388_fu_5165_p3 ^ 1'd1);

assign xor_ln52_186_fu_5225_p2 = (1'd1 ^ and_ln52_123_fu_5219_p2);

assign xor_ln52_187_fu_5237_p2 = (tmp_386_fu_5139_p3 ^ 1'd1);

assign xor_ln52_188_fu_5353_p2 = (tmp_392_fu_5311_p3 ^ 1'd1);

assign xor_ln52_189_fu_5371_p2 = (1'd1 ^ and_ln52_125_fu_5365_p2);

assign xor_ln52_190_fu_5383_p2 = (tmp_390_fu_5285_p3 ^ 1'd1);

assign xor_ln52_96_fu_845_p2 = (1'd1 ^ and_ln52_fu_839_p2);

assign xor_ln52_97_fu_857_p2 = (tmp_fu_759_p3 ^ 1'd1);

assign xor_ln52_98_fu_973_p2 = (tmp_245_fu_931_p3 ^ 1'd1);

assign xor_ln52_99_fu_991_p2 = (1'd1 ^ and_ln52_65_fu_985_p2);

assign xor_ln52_fu_827_p2 = (tmp_240_fu_785_p3 ^ 1'd1);

assign zext_ln52_32_fu_939_p1 = tmp_244_fu_923_p3;

assign zext_ln52_33_fu_1085_p1 = tmp_249_fu_1069_p3;

assign zext_ln52_34_fu_1231_p1 = tmp_254_fu_1215_p3;

assign zext_ln52_35_fu_1377_p1 = tmp_259_fu_1361_p3;

assign zext_ln52_36_fu_1523_p1 = tmp_264_fu_1507_p3;

assign zext_ln52_37_fu_1669_p1 = tmp_269_fu_1653_p3;

assign zext_ln52_38_fu_1815_p1 = tmp_274_fu_1799_p3;

assign zext_ln52_39_fu_1961_p1 = tmp_279_fu_1945_p3;

assign zext_ln52_40_fu_2107_p1 = tmp_284_fu_2091_p3;

assign zext_ln52_41_fu_2253_p1 = tmp_289_fu_2237_p3;

assign zext_ln52_42_fu_2399_p1 = tmp_294_fu_2383_p3;

assign zext_ln52_43_fu_2545_p1 = tmp_299_fu_2529_p3;

assign zext_ln52_44_fu_2691_p1 = tmp_304_fu_2675_p3;

assign zext_ln52_45_fu_2837_p1 = tmp_309_fu_2821_p3;

assign zext_ln52_46_fu_2983_p1 = tmp_314_fu_2967_p3;

assign zext_ln52_47_fu_3129_p1 = tmp_319_fu_3113_p3;

assign zext_ln52_48_fu_3275_p1 = tmp_324_fu_3259_p3;

assign zext_ln52_49_fu_3421_p1 = tmp_329_fu_3405_p3;

assign zext_ln52_50_fu_3567_p1 = tmp_334_fu_3551_p3;

assign zext_ln52_51_fu_3713_p1 = tmp_339_fu_3697_p3;

assign zext_ln52_52_fu_3859_p1 = tmp_344_fu_3843_p3;

assign zext_ln52_53_fu_4005_p1 = tmp_349_fu_3989_p3;

assign zext_ln52_54_fu_4151_p1 = tmp_354_fu_4135_p3;

assign zext_ln52_55_fu_4297_p1 = tmp_359_fu_4281_p3;

assign zext_ln52_56_fu_4443_p1 = tmp_364_fu_4427_p3;

assign zext_ln52_57_fu_4589_p1 = tmp_369_fu_4573_p3;

assign zext_ln52_58_fu_4735_p1 = tmp_374_fu_4719_p3;

assign zext_ln52_59_fu_4881_p1 = tmp_379_fu_4865_p3;

assign zext_ln52_60_fu_5027_p1 = tmp_383_fu_5011_p3;

assign zext_ln52_61_fu_5173_p1 = tmp_387_fu_5157_p3;

assign zext_ln52_62_fu_5319_p1 = tmp_391_fu_5303_p3;

assign zext_ln52_fu_793_p1 = tmp_239_fu_777_p3;

endmodule //wedrowiec_hls_axi_relu_array_ap_fixed_32u_array_ap_fixed_10_4_0_0_0_32u_relu_config4_s
