

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "7", "8", "11", "12", "15", "16", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"],
		"CDFG" : "wedrowiec_hls",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "23", "EstimateLatencyMax" : "23",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "1", "Name" : "dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0"}],
		"OutputProcess" : [
			{"ID" : "16", "Name" : "dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0"}],
		"Port" : [
			{"Name" : "input_layer", "Type" : "Axis", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0", "Port" : "input_layer"}]},
			{"Name" : "layer9_out", "Type" : "Axis", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "16", "SubInstance" : "dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0", "Port" : "layer9_out"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0", "Parent" : "0", "Child" : ["2", "4", "6"],
		"CDFG" : "dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "17", "EstimateLatencyMax" : "17",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_layer", "Type" : "Axis", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_dense_array_array_ap_fixed_32u_config3_Pipeline_DataPrepare_fu_295", "Port" : "input_layer", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "layer3_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["7"], "DependentChan" : "20", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer3_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0.grp_dense_array_array_ap_fixed_32u_config3_Pipeline_DataPrepare_fu_295", "Parent" : "1", "Child" : ["3"],
		"CDFG" : "dense_array_array_ap_fixed_32u_config3_Pipeline_DataPrepare",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "9", "EstimateLatencyMax" : "9",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_layer", "Type" : "Axis", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "input_layer_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "data_63_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_62_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_61_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_60_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_59_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_58_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_57_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_56_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_55_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_54_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_53_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_52_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_51_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_50_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_49_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_48_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_47_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_46_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_45_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_44_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_43_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_42_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_41_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_40_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_39_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_38_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_37_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_36_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_35_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_34_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_33_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_32_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_30_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_29_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_28_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_27_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_26_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_25_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_24_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_23_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_22_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_21_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_20_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_19_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_18_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_17_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_16_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_14_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_12_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "data_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "DataPrepare", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "3", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0.grp_dense_array_array_ap_fixed_32u_config3_Pipeline_DataPrepare_fu_295.flow_control_loop_pipe_sequential_init_U", "Parent" : "2"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0.grp_dense_latency_wrapper_ap_int_8_ap_fixed_21_19_5_3_0_config3_s_fu_365", "Parent" : "1", "Child" : ["5"],
		"CDFG" : "dense_latency_wrapper_ap_int_8_ap_fixed_21_19_5_3_0_config3_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "3",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val1", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_1_val2", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_2_val3", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_3_val4", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val5", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val6", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val7", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val8", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val9", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val10", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val11", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val12", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val13", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val14", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_14_val15", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val16", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_16_val17", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_17_val18", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_18_val19", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_19_val20", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_20_val21", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_21_val22", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_22_val23", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_23_val24", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_24_val25", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_25_val26", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val27", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_27_val28", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_28_val29", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_29_val30", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_30_val31", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_31_val32", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_32_val33", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_33_val34", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_34_val35", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_35_val36", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_36_val37", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_37_val38", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_38_val39", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_39_val40", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_40_val41", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_41_val42", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_42_val43", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_43_val44", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_44_val45", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_45_val46", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_46_val47", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_47_val48", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_48_val49", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_49_val50", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_50_val51", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_51_val52", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_52_val53", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_53_val54", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_54_val55", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_55_val56", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_56_val57", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_57_val58", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_58_val59", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_59_val60", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_60_val61", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_61_val62", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_62_val63", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_63_val64", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "5", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0.grp_dense_latency_wrapper_ap_int_8_ap_fixed_21_19_5_3_0_config3_s_fu_365.grp_dense_latency_ap_int_8_ap_fixed_21_19_5_3_0_config3_s_fu_524", "Parent" : "4",
		"CDFG" : "dense_latency_ap_int_8_ap_fixed_21_19_5_3_0_config3_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "2",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_16_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_17_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_18_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_19_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_20_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_21_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_22_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_23_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_24_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_25_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_27_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_28_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_29_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_30_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_31_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_32_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_33_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_34_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_35_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_36_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_37_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_38_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_39_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_40_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_41_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_42_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_43_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_44_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_45_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_46_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_47_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_48_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_49_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_50_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_51_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_52_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_53_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_54_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_55_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_56_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_57_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_58_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_59_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_60_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_61_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_62_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_63_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0.regslice_both_input_layer_U", "Parent" : "1"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0", "Parent" : "0",
		"CDFG" : "relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "1",
		"StartFifo" : "start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_U",
		"Port" : [
			{"Name" : "layer3_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "20", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer3_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer4_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["8"], "DependentChan" : "21", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer4_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0", "Parent" : "0", "Child" : ["9"],
		"CDFG" : "dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "5",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "7",
		"StartFifo" : "start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_U",
		"Port" : [
			{"Name" : "layer4_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["7"], "DependentChan" : "21", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer4_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer5_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["11"], "DependentChan" : "22", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer5_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0.grp_dense_latency_wrapper_ap_fixed_ap_fixed_18_14_5_3_0_config5_s_fu_161", "Parent" : "8", "Child" : ["10"],
		"CDFG" : "dense_latency_wrapper_ap_fixed_ap_fixed_18_14_5_3_0_config5_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "2",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val1", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_1_val2", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_2_val3", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_3_val4", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val5", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val6", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val7", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val8", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val9", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val10", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val11", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val12", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val13", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val14", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_14_val15", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val16", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_16_val17", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_17_val18", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_18_val19", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_19_val20", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_20_val21", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_21_val22", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_22_val23", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_23_val24", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_24_val25", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_25_val26", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val27", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_27_val28", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_28_val29", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_29_val30", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_30_val31", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_31_val32", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0.grp_dense_latency_wrapper_ap_fixed_ap_fixed_18_14_5_3_0_config5_s_fu_161.grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_18_14_5_3_0_config5_s_fu_268", "Parent" : "9",
		"CDFG" : "dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_18_14_5_3_0_config5_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_16_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_17_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_18_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_19_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_20_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_21_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_22_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_23_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_24_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_25_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_27_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_28_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_29_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_30_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_31_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0", "Parent" : "0",
		"CDFG" : "relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "8",
		"StartFifo" : "start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_U",
		"Port" : [
			{"Name" : "layer5_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["8"], "DependentChan" : "22", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer5_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer6_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["12"], "DependentChan" : "23", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer6_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0", "Parent" : "0", "Child" : ["13"],
		"CDFG" : "dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "6",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "11",
		"StartFifo" : "start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_U",
		"Port" : [
			{"Name" : "layer6_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["11"], "DependentChan" : "23", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer6_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer7_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["15"], "DependentChan" : "24", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer7_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0.grp_dense_latency_wrapper_ap_fixed_ap_fixed_18_14_5_3_0_config7_s_fu_161", "Parent" : "12", "Child" : ["14"],
		"CDFG" : "dense_latency_wrapper_ap_fixed_ap_fixed_18_14_5_3_0_config7_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "3",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val1", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_1_val2", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_2_val3", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_3_val4", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val5", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val6", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val7", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val8", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val9", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val10", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val11", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val12", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val13", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val14", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_14_val15", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val16", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_16_val17", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_17_val18", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_18_val19", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_19_val20", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_20_val21", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_21_val22", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_22_val23", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_23_val24", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_24_val25", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_25_val26", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val27", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_27_val28", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_28_val29", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_29_val30", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_30_val31", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_31_val32", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "14", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0.grp_dense_latency_wrapper_ap_fixed_ap_fixed_18_14_5_3_0_config7_s_fu_161.grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_18_14_5_3_0_config7_s_fu_268", "Parent" : "13",
		"CDFG" : "dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_18_14_5_3_0_config7_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "2",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_16_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_17_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_18_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_19_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_20_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_21_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_22_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_23_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_24_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_25_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_26_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_27_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_28_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_29_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_30_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_31_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0", "Parent" : "0",
		"CDFG" : "relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "12",
		"StartFifo" : "start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_U",
		"Port" : [
			{"Name" : "layer7_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["12"], "DependentChan" : "24", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer7_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer8_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["16"], "DependentChan" : "25", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer8_out_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0", "Parent" : "0", "Child" : ["17", "19"],
		"CDFG" : "dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "6",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "15",
		"StartFifo" : "start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_U",
		"Port" : [
			{"Name" : "layer8_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["15"], "DependentChan" : "25", "DependentChanDepth" : "1", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "layer8_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "layer9_out", "Type" : "Axis", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "layer9_out_TDATA_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0.grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105", "Parent" : "16", "Child" : ["18"],
		"CDFG" : "dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "2",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val1", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_1_val2", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_2_val3", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_3_val4", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val5", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val6", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val7", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val8", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val9", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val10", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val11", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val12", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val13", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val14", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_14_val15", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val16", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0.grp_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s_fu_105.grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140", "Parent" : "17",
		"CDFG" : "dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "data_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "data_15_val", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0.regslice_both_layer9_out_U", "Parent" : "16"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer3_out_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer4_out_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer5_out_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer6_out_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer7_out_U", "Parent" : "0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer8_out_U", "Parent" : "0"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_U", "Parent" : "0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_U", "Parent" : "0"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_U", "Parent" : "0"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_U", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_U", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_U", "Parent" : "0"}]}
