// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="wedrowiec_hls_wedrowiec_hls,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.549250,HLS_SYN_LAT=23,HLS_SYN_TPT=18,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=9021,HLS_SYN_LUT=35093,HLS_VERSION=2025_1}" *)

module wedrowiec_hls (
        input_layer_TDATA,
        layer9_out_TDATA,
        ap_clk,
        ap_rst_n,
        input_layer_TVALID,
        input_layer_TREADY,
        ap_start,
        layer9_out_TVALID,
        layer9_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [63:0] input_layer_TDATA;
output  [127:0] layer9_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   input_layer_TVALID;
output   input_layer_TREADY;
input   ap_start;
output   layer9_out_TVALID;
input   layer9_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_start;
wire    dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_done;
wire    dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_continue;
wire    dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_idle;
wire    dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_ready;
wire    dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_start_out;
wire    dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_start_write;
wire    dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_input_layer_TREADY;
wire   [671:0] dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_layer3_out_din;
wire    dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_layer3_out_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_start;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_done;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_continue;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_idle;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_ready;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_start_out;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_start_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_layer3_out_read;
wire   [191:0] relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_layer4_out_din;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_layer4_out_write;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_start;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_done;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_continue;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_idle;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_ready;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_start_out;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_start_write;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_layer4_out_read;
wire   [575:0] dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_layer5_out_din;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_layer5_out_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_start;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_done;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_continue;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_idle;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_ready;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_start_out;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_start_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_layer5_out_read;
wire   [191:0] relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_layer6_out_din;
wire    relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_layer6_out_write;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_start;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_done;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_continue;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_idle;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_ready;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_start_out;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_start_write;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_layer6_out_read;
wire   [287:0] dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_layer7_out_din;
wire    dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_layer7_out_write;
wire    relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_start;
wire    relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_done;
wire    relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_continue;
wire    relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_idle;
wire    relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_ready;
wire    relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_start_out;
wire    relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_start_write;
wire    relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_layer7_out_read;
wire   [95:0] relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_layer8_out_din;
wire    relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_layer8_out_write;
wire    dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_start;
wire    dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_done;
wire    dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_continue;
wire    dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_idle;
wire    dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_ready;
wire    dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_layer8_out_read;
wire   [127:0] dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_layer9_out_TDATA;
wire    dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_layer9_out_TVALID;
wire    layer3_out_full_n;
wire   [671:0] layer3_out_dout;
wire    layer3_out_empty_n;
wire   [1:0] layer3_out_num_data_valid;
wire   [1:0] layer3_out_fifo_cap;
wire    layer4_out_full_n;
wire   [191:0] layer4_out_dout;
wire    layer4_out_empty_n;
wire   [1:0] layer4_out_num_data_valid;
wire   [1:0] layer4_out_fifo_cap;
wire    layer5_out_full_n;
wire   [575:0] layer5_out_dout;
wire    layer5_out_empty_n;
wire   [1:0] layer5_out_num_data_valid;
wire   [1:0] layer5_out_fifo_cap;
wire    layer6_out_full_n;
wire   [191:0] layer6_out_dout;
wire    layer6_out_empty_n;
wire   [1:0] layer6_out_num_data_valid;
wire   [1:0] layer6_out_fifo_cap;
wire    layer7_out_full_n;
wire   [287:0] layer7_out_dout;
wire    layer7_out_empty_n;
wire   [1:0] layer7_out_num_data_valid;
wire   [1:0] layer7_out_fifo_cap;
wire    layer8_out_full_n;
wire   [95:0] layer8_out_dout;
wire    layer8_out_empty_n;
wire   [1:0] layer8_out_num_data_valid;
wire   [1:0] layer8_out_fifo_cap;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_din;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_dout;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_din;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_dout;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_din;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_dout;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_din;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_dout;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_din;
wire    start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_dout;
wire    start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_din;
wire    start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_dout;
wire    start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_empty_n;

wedrowiec_hls_dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_s dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_full_n),
    .ap_done(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_done),
    .ap_continue(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_continue),
    .ap_idle(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_idle),
    .ap_ready(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_ready),
    .start_out(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_start_out),
    .start_write(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_start_write),
    .input_layer_TDATA(input_layer_TDATA),
    .input_layer_TVALID(input_layer_TVALID),
    .input_layer_TREADY(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_input_layer_TREADY),
    .layer3_out_din(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_layer3_out_din),
    .layer3_out_full_n(layer3_out_full_n),
    .layer3_out_write(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_layer3_out_write),
    .layer3_out_num_data_valid(layer3_out_num_data_valid),
    .layer3_out_fifo_cap(layer3_out_fifo_cap)
);

wedrowiec_hls_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_s relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_full_n),
    .ap_done(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_ready),
    .start_out(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_start_out),
    .start_write(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_start_write),
    .layer3_out_dout(layer3_out_dout),
    .layer3_out_empty_n(layer3_out_empty_n),
    .layer3_out_read(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_layer3_out_read),
    .layer3_out_num_data_valid(layer3_out_num_data_valid),
    .layer3_out_fifo_cap(layer3_out_fifo_cap),
    .layer4_out_din(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_layer4_out_din),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_layer4_out_write),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap)
);

wedrowiec_hls_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_s dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_full_n),
    .ap_done(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_ready),
    .start_out(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_start_out),
    .start_write(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_start_write),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_layer4_out_read),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer5_out_din(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_layer5_out_din),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_layer5_out_write),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap)
);

wedrowiec_hls_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_s relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_full_n),
    .ap_done(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_ready),
    .start_out(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_start_out),
    .start_write(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_start_write),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_layer5_out_read),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer6_out_din(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_layer6_out_din),
    .layer6_out_full_n(layer6_out_full_n),
    .layer6_out_write(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_layer6_out_write),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap)
);

wedrowiec_hls_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_s dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_full_n),
    .ap_done(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_ready),
    .start_out(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_start_out),
    .start_write(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_start_write),
    .layer6_out_dout(layer6_out_dout),
    .layer6_out_empty_n(layer6_out_empty_n),
    .layer6_out_read(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_layer6_out_read),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer7_out_din(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_layer7_out_din),
    .layer7_out_full_n(layer7_out_full_n),
    .layer7_out_write(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_layer7_out_write),
    .layer7_out_num_data_valid(layer7_out_num_data_valid),
    .layer7_out_fifo_cap(layer7_out_fifo_cap)
);

wedrowiec_hls_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_s relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_full_n),
    .ap_done(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_ready),
    .start_out(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_start_out),
    .start_write(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_start_write),
    .layer7_out_dout(layer7_out_dout),
    .layer7_out_empty_n(layer7_out_empty_n),
    .layer7_out_read(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_layer7_out_read),
    .layer7_out_num_data_valid(layer7_out_num_data_valid),
    .layer7_out_fifo_cap(layer7_out_fifo_cap),
    .layer8_out_din(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_layer8_out_din),
    .layer8_out_full_n(layer8_out_full_n),
    .layer8_out_write(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_layer8_out_write),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap)
);

wedrowiec_hls_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_s dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_start),
    .ap_done(dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_ready),
    .layer8_out_dout(layer8_out_dout),
    .layer8_out_empty_n(layer8_out_empty_n),
    .layer8_out_read(dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_layer8_out_read),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer9_out_TDATA(dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_layer9_out_TDATA),
    .layer9_out_TVALID(dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_layer9_out_TVALID),
    .layer9_out_TREADY(layer9_out_TREADY)
);

wedrowiec_hls_fifo_w672_d1_S layer3_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_layer3_out_din),
    .if_full_n(layer3_out_full_n),
    .if_write(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_layer3_out_write),
    .if_dout(layer3_out_dout),
    .if_empty_n(layer3_out_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_layer3_out_read),
    .if_num_data_valid(layer3_out_num_data_valid),
    .if_fifo_cap(layer3_out_fifo_cap)
);

wedrowiec_hls_fifo_w192_d1_S layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_empty_n(layer4_out_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_layer4_out_read),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap)
);

wedrowiec_hls_fifo_w576_d1_S layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_empty_n(layer5_out_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_layer5_out_read),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap)
);

wedrowiec_hls_fifo_w192_d1_S layer6_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_layer6_out_din),
    .if_full_n(layer6_out_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_layer6_out_write),
    .if_dout(layer6_out_dout),
    .if_empty_n(layer6_out_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_layer6_out_read),
    .if_num_data_valid(layer6_out_num_data_valid),
    .if_fifo_cap(layer6_out_fifo_cap)
);

wedrowiec_hls_fifo_w288_d1_S layer7_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_layer7_out_din),
    .if_full_n(layer7_out_full_n),
    .if_write(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_layer7_out_write),
    .if_dout(layer7_out_dout),
    .if_empty_n(layer7_out_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_layer7_out_read),
    .if_num_data_valid(layer7_out_num_data_valid),
    .if_fifo_cap(layer7_out_fifo_cap)
);

wedrowiec_hls_fifo_w96_d1_S layer8_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_layer8_out_din),
    .if_full_n(layer8_out_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_layer8_out_write),
    .if_dout(layer8_out_dout),
    .if_empty_n(layer8_out_empty_n),
    .if_read(dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_layer8_out_read),
    .if_num_data_valid(layer8_out_num_data_valid),
    .if_fifo_cap(layer8_out_fifo_cap)
);

wedrowiec_hls_start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0 start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_full_n),
    .if_write(dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_ready)
);

wedrowiec_hls_start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0 start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_ready)
);

wedrowiec_hls_start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0 start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_full_n),
    .if_write(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_ready)
);

wedrowiec_hls_start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0 start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_ready)
);

wedrowiec_hls_start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0 start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_full_n),
    .if_write(dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_ready)
);

wedrowiec_hls_start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0 start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_empty_n),
    .if_read(dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_ready)
);

assign ap_done = dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_done;

assign ap_idle = (relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_idle & relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_idle & relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_idle & dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_idle & dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_idle & dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_idle & dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_idle);

assign ap_ready = dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_ap_start = start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_empty_n;

assign dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_ap_start = start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_empty_n;

assign dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_ap_start = start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_empty_n;

assign dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_continue = 1'b1;

assign dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_ap_start = ap_start;

assign input_layer_TREADY = dense_array_ap_int_8_8u_array_ap_fixed_21_19_5_3_0_32u_config3_U0_input_layer_TREADY;

assign layer9_out_TDATA = dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_layer9_out_TDATA;

assign layer9_out_TVALID = dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_layer9_out_TVALID;

assign relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_ap_start = start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_empty_n;

assign relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_ap_start = start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_empty_n;

assign relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_ap_start = start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_empty_n;

assign start_for_dense_array_ap_fixed_16u_array_ap_fixed_17_13_5_3_0_4u_config9_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_16u_config7_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_32u_array_ap_fixed_18_14_5_3_0_32u_config5_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_16u_array_ap_fixed_6_4_0_0_0_16u_relu_config8_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config4_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_32u_array_ap_fixed_6_4_0_0_0_32u_relu_config6_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "wedrowiec_hls_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "wedrowiec_hls_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //wedrowiec_hls

