// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module wedrowiec_hls_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_val1,
        data_1_val2,
        data_2_val3,
        data_3_val4,
        data_4_val5,
        data_5_val6,
        data_6_val7,
        data_7_val8,
        data_8_val9,
        data_9_val10,
        data_10_val11,
        data_11_val12,
        data_12_val13,
        data_13_val14,
        data_14_val15,
        data_15_val16,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] data_0_val1;
input  [5:0] data_1_val2;
input  [5:0] data_2_val3;
input  [5:0] data_3_val4;
input  [5:0] data_4_val5;
input  [5:0] data_5_val6;
input  [5:0] data_6_val7;
input  [5:0] data_7_val8;
input  [5:0] data_8_val9;
input  [5:0] data_9_val10;
input  [5:0] data_10_val11;
input  [5:0] data_11_val12;
input  [5:0] data_12_val13;
input  [5:0] data_13_val14;
input  [5:0] data_14_val15;
input  [5:0] data_15_val16;
output  [16:0] ap_return_0;
output  [16:0] ap_return_1;
output  [16:0] ap_return_2;
output  [16:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[16:0] ap_return_0;
reg[16:0] ap_return_1;
reg[16:0] ap_return_2;
reg[16:0] ap_return_3;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_start;
wire    grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done;
wire    grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_idle;
wire    grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_ready;
wire   [16:0] grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_0;
wire   [16:0] grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_1;
wire   [16:0] grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_2;
wire   [16:0] grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_3;
reg    grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [16:0] ap_return_0_preg;
reg   [16:0] ap_return_1_preg;
reg   [16:0] ap_return_2_preg;
reg   [16:0] ap_return_3_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_start_reg = 1'b0;
#0 ap_return_0_preg = 17'd0;
#0 ap_return_1_preg = 17'd0;
#0 ap_return_2_preg = 17'd0;
#0 ap_return_3_preg = 17'd0;
end

wedrowiec_hls_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_start),
    .ap_done(grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done),
    .ap_idle(grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_idle),
    .ap_ready(grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_ready),
    .data_0_val(data_0_val1),
    .data_1_val(data_1_val2),
    .data_2_val(data_2_val3),
    .data_3_val(data_3_val4),
    .data_4_val(data_4_val5),
    .data_5_val(data_5_val6),
    .data_6_val(data_6_val7),
    .data_7_val(data_7_val8),
    .data_8_val(data_8_val9),
    .data_9_val(data_9_val10),
    .data_10_val(data_10_val11),
    .data_11_val(data_11_val12),
    .data_12_val(data_12_val13),
    .data_13_val(data_13_val14),
    .data_14_val(data_14_val15),
    .data_15_val(data_15_val16),
    .ap_return_0(grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 17'd0;
    end else begin
        if (((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_return_0_preg <= grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 17'd0;
    end else begin
        if (((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_return_1_preg <= grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 17'd0;
    end else begin
        if (((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_return_2_preg <= grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 17'd0;
    end else begin
        if (((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_return_3_preg <= grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_ready == 1'b1)) begin
            grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_return_0 = grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_0;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_return_1 = grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_1;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_return_2 = grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_2;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_return_3 = grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_return_3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_start = grp_dense_latency_ap_fixed_6_4_0_0_0_ap_fixed_17_13_5_3_0_config9_s_fu_140_ap_start_reg;

endmodule //wedrowiec_hls_dense_latency_wrapper_ap_fixed_ap_fixed_17_13_5_3_0_config9_s
