#ifndef INTERRUPTS_H
#define INTERRUPTS_H

#include <stdint.h>
#include "xscugic.h"

/******************************************************************************
 * Interrupt Controller Module
 *
 * Configures the Generic Interrupt Controller (GIC) of the Zynq-7000 to
 * handle the FPGA-to-PSI (F2P) interrupt generated by the NN accelerator.
 *
 * When the accelerator finishes classification and majority-voting across
 * 5 frames it asserts IRQ_F2P[0] (interrupt ID 61). The ISR sets the
 * volatile flag fpga_finished, which the main loop polls.
 ******************************************************************************/

/* FPGA-to-PSI interrupt ID connected to the NN accelerator */
#define FPGA_INTR_ID        61

/* GIC device ID as defined in xparameters.h */
#define INTC_DEVICE_ID      XPAR_SCUGIC_SINGLE_DEVICE_ID

/******************************************************************************
 * Shared state
 ******************************************************************************/

/**
 * Volatile flag set by the ISR when the FPGA accelerator completes
 * a classification cycle. Must be declared extern for access from
 * main.c. Cleared by the main loop after consuming the result.
 */
extern volatile uint8_t fpga_finished;

/******************************************************************************
 * Public API
 ******************************************************************************/

/**
 * Init_Interrupts() - Initialise the GIC and register the FPGA ISR.
 *
 * Performs the full interrupt subsystem setup:
 *   1. Look up and configure the SCU GIC controller.
 *   2. Connect the FPGA ISR handler to interrupt ID FPGA_INTR_ID.
 *   3. Enable the interrupt at the GIC.
 *   4. Register the GIC handler with the ARM exception table and enable
 *      interrupts globally.
 *
 * @return  XST_SUCCESS  on successful initialisation,
 *          XST_FAILURE  if any step fails.
 */
int Init_Interrupts(void);

#endif /* INTERRUPTS_H */